### ISSUE TITLE
Partial implementation of privileged actions should be completed

### ISSUE THREAD

**Issue by jamezp** [eclipse-ee4j/jaxrs-api#1004]
In the various `FactoryFinder`'s there is a privileged action used to get the context class loader. However, there is no such privileged action around the service loader which could fail if the security manager is enabled and read access is not explicitly granted to the implementation JAR.

The `ClientBuilder` could also fail with a security issue while attempting to throw a `LinkageError` if the security manager is enabled and the correct permissions are not defined.

**Comment by arjantijms** [comment]
> which could fail if the security manager is enabled 

Just note that the security manager is deprecated for removal in JDK 17, so eventually and sooner than later we need to remove all those actions.

**Comment by jamezp** [comment]
Yes. Until then though this would allow, at least RESTEasy, it allows us to stop using a fork of the spec API.

**Comment by arjantijms** [comment]
> Yes. Until then though this would allow, at least RESTEasy, it allows us to stop using a fork of the spec API.

I understand, though alternatively you can grant all permissions or just not enable the security manager? 

I know that last bit sounds overly simplistic, but whatever code thinks it needs the security manager needs to rethink that decision pretty soon anyway. The problem here is that we have tons and tons of code just like this, and preparing to remove it will take a long time. 

That's why I'm advocating to start this process already instead of waiting until JDK ~19+ rolls around and then finding out Jakarta EE can't run it, and can't run on it for some years to come as all implementations slowly migrate away only then.

**Comment by jamezp** [comment]
> I know that last bit sounds overly simplistic, but whatever code thinks it needs the security manager needs to rethink that decision pretty soon anyway. The problem here is that we have tons and tons of code just like this, and preparing to remove it will take a long time.
> 
> That's why I'm advocating to start this process already instead of waiting until JDK ~19+ rolls around and then finding out Jakarta EE can't run it, and can't run on it for some years to come as all implementations slowly migrate away only then.

This cannot be done for all customers. Some customers are required to use a security manager. Trust me I wish it was that simple :) We (Red Hat) have put a lot of effort into running with the security manager enabled for these customers. I assume other vendors have done the same as well.

**Comment by arjantijms** [comment]
> Some customers are required to use a security manager.

I wonder what their plan is then, stay on JDK 16 or maybe 17 forever?

Of course I know it's not that easy to tell customers, but isn't it a little similar to customers that were required to use applets even a few years ago still? Eventually those were full removed as well, and whether customers required applets or not didn't change the fact.

**Comment by jamezp** [comment]
For sure something is gonna have to happen. I don't know what the plan is there TBH.
