### ISSUE TITLE
Reduce boilerplate when using SeBootstrap

### ISSUE THREAD

**Issue by spericas** [eclipse-ee4j/jaxrs-api#1009]
As shown in our examples:

https://github.com/eclipse-ee4j/jaxrs-api/tree/master/examples/src/main/java/jaxrs/examples/bootstrap

there is a significant amount of boilerplate for starting and stopping, and it is almost identical in all examples.

Some new methods could greatly improve readability without introducing new semantics. I'd like to propose going from this:

```
        final SeBootstrap.Configuration requestedConfiguration = SeBootstrap.Configuration.builder().build();

        SeBootstrap.start(application, requestedConfiguration).thenAccept(instance -> {
            Runtime.getRuntime()
                    .addShutdownHook(new Thread(() -> instance.stop()
                            .thenAccept(stopResult -> System.out.printf("Stop result: %s [Native stop result: %s].%n",
                                    stopResult, stopResult.unwrap(Object.class)))));

            final Configuration actualConfigurarion = instance.configuration();
            final URI uri = UriBuilder.newInstance().scheme(actualConfigurarion.protocol().toLowerCase())
                    .host(actualConfigurarion.host()).port(actualConfigurarion.port())
                    .path(actualConfigurarion.rootPath()).build();
            System.out.printf("Instance %s running at %s [Native handle: %s].%n", instance, uri,
                    instance.unwrap(Object.class));
            System.out.println("Send SIGKILL to shutdown.");
        });
```

to this 

```
        SeBootstrap.start(application).thenAccept(instance -> {
            instance.exitOnShutdown(stopResult ->
                    System.out.printf("Stop result: %s [Native stop result: %s].%n", stopResult,
                            stopResult.unwrap(Object.class)));
            final URI uri = instance.configuration().appUri();
            System.out.printf("Instance %s running at %s [Native handle: %s].%n", instance, uri,
                    instance.unwrap(Object.class));
            System.out.println("Send SIGKILL to shutdown.");
        });
```

**Comment by mkarg** [comment]
I am not a big friend of changing the API years after its adoption, and just weeks before GA.

I do not see that it is the job of JAX-RS to handle JVM shutdowns. We should not mix JVM concerns with JAX-RS concerns. Not everbody wants to use shutdown handlers nor will there be a major crowd asking for the app URI. In fact, so least people asked for that in the past years, that Jersey till today did not add it. So we shouldn't impose methods to the API before there is an actual implementation proving the actual demand ("Code First").

For that reasons I am -1 regarding the introduction of `exitOnShutdown`.

**Comment by spericas** [comment]
Years of adoption? We haven't released yet. There's way too much boilerplate as shown in all the examples, this is the time to fix not later. These are very simple additions, and I actually don't think we should go GA without some boilerplate reduction.

**Comment by andymc12** [comment]
I like the proposal. I'm +1 for it as is, but would suggest using `baseUri` instead of `appUri` for consistency with other APIs like [UriInfo](https://jakarta.ee/specifications/restful-ws/3.0/apidocs/jakarta/ws/rs/core/uriinfo#getBaseUri()).

**Comment by jamezp** [comment]
I think this looks much better. I think having a hook into the shutdown is extremely valuable. Much better than a shutdown hook.

**Comment by mkarg** [comment]
> Years of adoption? We haven't released yet. There's way too much boilerplate as shown in all the examples, this is the time to fix not later. These are very simple _additions_, and I actually don't think we should go GA without some boilerplate reduction.

Yes, we all agreed on the PR as-is *after* a phase of discussion, and part of that discussion was to copy the behavior of Jersey mostly *and* it was in particular your and / or Jan's personal request to use explicitly shutdown hooks!

**Comment by spericas** [comment]
As I said, the proposed changes are fully backward compatible, they don't change anything that was already there, only add and simplify. APIs are there to evolve and improve and this does not go against anything that was already agreed before.

**Comment by mkarg** [comment]
@spericas AFAIK this issue is finished?

**Comment by spericas** [comment]
PR #1010
