### ISSUE TITLE
TCK migration : Migrate all standalone tests from jakartaee-tck

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jaxrs-api#1015]
The PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1002 migrated tests from below folders in https://github.com/eclipse-ee4j/jakartaee-tck 
jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core/responsebuilder (15)
jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core/responsebuilder (85)
jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core/uribuilder (128)
jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/core/request (28)
jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/client/asyncinvoker (147)

All the remaining tests in jakartaee-tck/src/com/sun/ts/tests/jaxrs & jakartaee-tck/src/com/sun/ts/tests/signaturetest/jaxrs need to be migrated except the below folders which are part of platform tests. These should ideally remain within platform TCK bundle only.
    -jakartaee-tck/src/com/sun/ts/tests/jaxrs/jaxrs21/platform
    -jakartaee-tck/src/com/sun/ts/tests/jaxrs/platform

Can use wiki https://github.com/alwin-joseph/jaxrs-api/wiki/REST-TCK-separation-from-JakartaEE-TCK-repo/  for reference on how to move the tests.

**Comment by alwin-joseph** [comment]
I am currently working on jakartaee-tck/src/com/sun/ts/tests/jaxrs/spec tests.

**Comment by jelemux** [comment]
Hi, @mkarg already mentioned that I'm interested in helping out on this.  
I'm currently working on the remaining [jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core tests](https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/jaxrs/api/rs/core). I hope that's okay!  
You can have a look at my progress [here](https://github.com/jelemux/jaxrs-api/tree/tck-migration), if you're interested.

One small issue I'm currently having is with the newcookie tests: They're testing against the deprecated `valueOf` and `toString` methods of `NewCookie`. Now I'm unsure if anything should be changed here or left as-is.

**Comment by jelemux** [comment]
Also in the newcookie `equalsTest`, `NewCookie.hashcode()` throws a NullPointerException because `sameSite` is null.  
Is this an error in the test or in `NewCookie`?

**Comment by jelemux** [comment]
Generally, what should I do if I find such things?  
Should I leave them, just report them or is there anything else I can do?

**Comment by mkarg** [comment]
> Generally, what should I do if I find such things?
> Should I leave them, just report them or is there anything else I can do?

We opened this thread for the discussion of the migration, so it is pretty much the best place to just ask questions like this one.

Typically on would **not** fix anything as part of the migration itself, but separate the fixes in a separate PR. The reason is that they need to be discussed more intensively, so you would slow down your migration PRs without a need.

**Comment by mkarg** [comment]
> Also in the [newcookie equalsTest](https://github.com/jelemux/jaxrs-api/blob/4d8a312e7400a37708bb564198cded085d55ba95/jaxrs-tck/src/main/java/jakarta/ws/rs/tck/api/rs/core/newcookie/JAXRSClientIT.java#L896), `NewCookie.hashcode()` throws a NullPointerException because `sameSite` is null.
> Is this an error in the test or in `NewCookie`?

@chkal I think you can answer this question better than me as you were involved in the `sameSite` PR. :-)

**Comment by jelemux** [comment]
> Typically on would not fix anything as part of the migration itself, but separate the fixes in a separate PR.

Ok, so I'll just migrate the tests and document my problems. Once the initial PR has been merged, I'll make a DRAFT-PR with all the accumulated documentation and we can discuss those problems there. Is that alright?

**Comment by mkarg** [comment]
> > Typically on would not fix anything as part of the migration itself, but separate the fixes in a separate PR.
> 
> Ok, so I'll just migrate the tests and document my problems. Once the initial PR has been merged, I'll make a DRAFT-PR with all the accumulated documentation and we can discuss those problems there. Is that alright?

Sounds good *for me*, but OTOH others might have different opinions, so let's see who chimes into this thread. :-)

**Comment by alwin-joseph** [comment]
**Current Status** 

Completed : 
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core/responsebuilder (15)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core/responseclient (85)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core/uribuilder (128)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/core/request (28)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/client/asyncinvoker (147)

Test Failures:
-https://github.com/eclipse-ee4j/jaxrs-api/issues/1020

Work In Progress : 
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/spec (319) 
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core : (Jeremias)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/core (133)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/client (117)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/ext (118)

Pending tests are in: 
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/jaxrs21
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/servlet
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/resource
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/client

**Comment by jelemux** [comment]
Yesterday I tended to the tests in jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/ext, but now I see that they're listed a WIP here.  
Is someone already working on those?

If not, I'd suggest I'll do all the remaining tests in jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs (there's not that many left).

**Comment by alwin-joseph** [comment]
> Yesterday I tended to the tests in jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/ext, but now I see that they're listed a WIP here.
> Is someone already working on those?
> 
> If not, I'd suggest I'll do all the remaining tests in jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs (there's not that many left).

The tests in jakartaee-tck/src/com/sun/ts/tests/jaxrs/**ee**/rs/ext are WIP. Please continue with any of the remaining tests in jakartaee-tck/src/com/sun/ts/tests/jaxrs/**api**

**Comment by jelemux** [comment]
**Current Status**

Completed :

- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core/responsebuilder (15)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core/responseclient (85)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api/rs/core/uribuilder (126)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/core/request (28)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/client/asyncinvoker (147)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/spec (319)

Test Failures: #1020

Work In Progress :

- jakartaee-tck/src/com/sun/ts/tests/jaxrs/api : #1030
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/core (133) , jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/client (117), jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/ext (118) : PR #1029
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/jaxrs21 (242)
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs/beanparam(118),constrainedto(8),container(106),cookieparam(43),delete(4) : PR #1031
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/servlet3 : #1035 
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/rs
- jakartaee-tck/src/com/sun/ts/tests/jaxrs/ee/resource: #1036 

No pending tests

**Comment by alwin-joseph** [comment]
Some pending items to be addressed immediately post migration other than test failures :

1. Post merge of https://github.com/eclipse-ee4j/jaxrs-api/pull/1030 the test java files without *IT should be removed from api/ folder as they were added by https://github.com/eclipse-ee4j/jaxrs-api/pull/1029 for resolving dependencies.  
2. https://github.com/eclipse-ee4j/jaxrs-api/pull/1029#discussion_r731347166 
3. https://github.com/eclipse-ee4j/jaxrs-api/pull/1031#discussion_r729248922

**Comment by alwin-joseph** [comment]
> Some pending items to be addressed immediately post migration other than test failures :
> 
>     1. Post merge of [TCK Migration: Move pending tests from jakartaee-tck/src/com/sun/ts/tests/jaxrs/api (#1015) #1030](https://github.com/eclipse-ee4j/jaxrs-api/pull/1030) the test java files without *IT should be removed from api/ folder as they were added by [TCK Migration: Move pending jaxrs/ee/rs/core,client,ext tests from jakartaee-tck   #1029](https://github.com/eclipse-ee4j/jaxrs-api/pull/1029) for resolving dependencies.
> 
>     2. [TCK Migration: Move pending jaxrs/ee/rs/core,client,ext tests from jakartaee-tck   #1029 (comment)](https://github.com/eclipse-ee4j/jaxrs-api/pull/1029#discussion_r731347166)
> 

https://github.com/eclipse-ee4j/jaxrs-api/pull/1050 covers 1 & 2. 

> 
>     4. Some of the tests in jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/client/syncinvoker/JAXRSClientIT.java have return types, which need to be removed(void) as to run the tests : Done

This was done

**Comment by alwin-joseph** [comment]
All standalone tests including signature tests were migrated.
