### ISSUE TITLE
TCK Migration : Fix test failures from tck migration

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jaxrs-api#1020]
There are possible test failures that need to be addressed post migrating the tests from jakartaee-tck.
This is to track all such failures that can be revisited to be fixed post migration once all the tests are in. 

The tests are currently disabled by commenting the `@Test ` annotation.

1. 11 test failures in ee/rs/client/asyncinvoker after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1002. The tests are currently disabled by commenting the `@Test ` annotation.
JAXRSClientIT.traceTest:
JAXRSClientIT.traceWhileServerWaitTest
JAXRSClientIT.traceWithCallbackThrowsNoWebApplicationExceptionForResponseTest:
JAXRSClientIT.traceWithCallbackWhileServerWaitTest:
JAXRSClientIT.traceWithClassThrowsNoWebApplicationExceptionForResponseTest:
JAXRSClientIT.traceWithGenericTypeResponseWhileServerWaitTest:
JAXRSClientIT.traceWithGenericTypeThrowsNoWebApplicationExceptionForResponseTest:
JAXRSClientIT.traceWithResponseClassWhileServerWaitTest:
JAXRSClientIT.traceWithGenericTypeStringWhileServerWaitTest:
JAXRSClientIT.traceWithStringCallbackWhileServerWaitTest:
JAXRSClientIT.traceWithStringClassWhileServerWaitTest:

2. jakarta.ws.rs.tck.spec.provider.overridestandard.JAXRSClientIT.readWriteStreamingOutputProviderTest after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1022. 

3. jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/client/syncinvoker/JAXRSClientIT.traceWithResponseClassThrowsNoWebApplicationExceptionTest
jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/client/syncinvoker/JAXRSClientIT.traceWithGenericTypeResponseThrowsNoWebApplicationExceptionTest
jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.basicAuthorizationAdminTest
jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.basicAuthorizationStandardUserTest after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1029

4. jakarta.ws.rs.tck.ee.rs.container.requestcontext.security.getSecurityContextTest after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1031

5. Below failures after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1030 
api/rs/core/newcookie: equalsTest fails because NewCookie.hashcode() throws a NullPointerException because sameSite is null (test disabled)
api/rs/core/linkjaxbadapter: Implementation for jakarta.xml.bind-api cannot be found and I don't know how to add it (tests disabled)
api/rs/ext/interceptor: Tests fail with IllegalStateException: [FATAL] HttpRequest is null (tests disabled)

6.  1 test failure after  https://github.com/eclipse-ee4j/jaxrs-api/pull/1037
jakarta.ws.rs.tck.jaxrs21.ee.sse.ssebroadcaster.JAXRSClientIT.sseBroadcastTest

**Comment by alwin-joseph** [comment]
Current Status  : 6 test failures post TCK migration 

Pending tests failures are currently disabled by commenting the `@Test ` annotation.

1.  Below test fails after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1022. 
- jakarta.ws.rs.tck.spec.provider.overridestandard.JAXRSClientIT.readWriteStreamingOutputProviderTest

2. Below tests fails after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1029
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.basicAuthorizationAdminTest
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.basicAuthorizationStandardUserTest 

3. Below test fails after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1031
- jakarta.ws.rs.tck.ee.rs.container.requestcontext.security.getSecurityContextTest

4. Below failure after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1030 
- api/rs/core/newcookie: equalsTest fails because NewCookie.hashcode() throws a NullPointerException because sameSite is null (test commented)

5.  Below test failure after  https://github.com/eclipse-ee4j/jaxrs-api/pull/1037
- jakarta.ws.rs.tck.jaxrs21.ee.sse.ssebroadcaster.JAXRSClientIT.sseBroadcastTest


Tests that were fixed in recent commits/PRs

1. 11 test failures in ee/rs/client/asyncinvoker fixed by https://github.com/eclipse-ee4j/jaxrs-api/pull/1037
 JAXRSClientIT.traceTest:
JAXRSClientIT.traceWhileServerWaitTest
JAXRSClientIT.traceWithCallbackThrowsNoWebApplicationExceptionForResponseTest:
JAXRSClientIT.traceWithCallbackWhileServerWaitTest:
JAXRSClientIT.traceWithClassThrowsNoWebApplicationExceptionForResponseTest:
JAXRSClientIT.traceWithGenericTypeResponseWhileServerWaitTest:
JAXRSClientIT.traceWithGenericTypeThrowsNoWebApplicationExceptionForResponseTest:
JAXRSClientIT.traceWithResponseClassWhileServerWaitTest:
JAXRSClientIT.traceWithGenericTypeStringWhileServerWaitTest:
JAXRSClientIT.traceWithStringCallbackWhileServerWaitTest:
JAXRSClientIT.traceWithStringClassWhileServerWaitTest:


2. Below failures fixed by https://github.com/eclipse-ee4j/jaxrs-api/pull/1037
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/client/syncinvoker/JAXRSClientIT.traceWithResponseClassThrowsNoWebApplicationExceptionTest
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/client/syncinvoker/JAXRSClientIT.traceWithGenericTypeResponseThrowsNoWebApplicationExceptionTest


3. Below fixed by https://github.com/eclipse-ee4j/jaxrs-api/pull/1045/commits/12961075167911dac104a6f20b3274296147fcbd in https://github.com/eclipse-ee4j/jaxrs-api/pull/1045
- api/rs/core/linkjaxbadapter: 
- api/rs/ext/interceptor:

**Comment by alwin-joseph** [comment]
**Current Status  : 6 test failures post TCK migration** 


**Pending tests failures are currently disabled by commenting the `@Test ` annotation.**

1.  Below test fails after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1022. 
jakarta.ws.rs.tck.spec.provider.overridestandard.JAXRSClientIT.readWriteStreamingOutputProviderTest

2. Below tests fails after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1029
jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.basicAuthorizationAdminTest
jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.basicAuthorizationStandardUserTest 

3. Below test fails after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1031
jakarta.ws.rs.tck.ee.rs.container.requestcontext.security.getSecurityContextTest

4. Below failure after PR https://github.com/eclipse-ee4j/jaxrs-api/pull/1030 
api/rs/core/newcookie: equalsTest fails because NewCookie.hashcode() throws a NullPointerException because sameSite is null (test commented)

5.  Below test failure after  https://github.com/eclipse-ee4j/jaxrs-api/pull/1037
jakarta.ws.rs.tck.jaxrs21.ee.sse.ssebroadcaster.JAXRSClientIT.sseBroadcastTest

**Comment by alwin-joseph** [comment]
> 
>     1. Below tests fails after PR [TCK Migration: Move pending jaxrs/ee/rs/core,client,ext tests from jakartaee-tck   #1029](https://github.com/eclipse-ee4j/jaxrs-api/pull/1029)
>        jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.basicAuthorizationAdminTest
>        jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.basicAuthorizationStandardUserTest
> 
>     2. Below test fails after PR [TCK Migration : Move a set of jaxrs/ee/rs/ tests from jakartaee-tck #1031](https://github.com/eclipse-ee4j/jaxrs-api/pull/1031)
>        jakarta.ws.rs.tck.ee.rs.container.requestcontext.security.getSecurityContextTest
> 

> 
>     4. Below test failure after  [TCK Migration: Move jaxrs21/ tests from jakartaee-tck #1037](https://github.com/eclipse-ee4j/jaxrs-api/pull/1037)
>        jakarta.ws.rs.tck.jaxrs21.ee.sse.ssebroadcaster.JAXRSClientIT.sseBroadcastTest

These failures were fixed by https://github.com/eclipse-ee4j/jaxrs-api/pull/1061/

**Comment by alwin-joseph** [comment]
> 
>     3. Below failure after PR [TCK Migration: Move pending tests from jakartaee-tck/src/com/sun/ts/tests/jaxrs/api (#1015) #1030](https://github.com/eclipse-ee4j/jaxrs-api/pull/1030)
>        api/rs/core/newcookie: equalsTest fails because NewCookie.hashcode() throws a NullPointerException because sameSite is null (test commented).
>        This seems to be related to the new api change due to [d4a883d#diff-0ccdc7eda3bc0e665408f1cb47ad205f46fd294d133d9ef2993d65a91d110804](https://github.com/eclipse-ee4j/jaxrs-api/commit/d4a883dfcdc4777067c8a94e666bfcfc3f75df01#diff-0ccdc7eda3bc0e665408f1cb47ad205f46fd294d133d9ef2993d65a91d110804).
> 

Fixed by https://github.com/eclipse-ee4j/jaxrs-api/pull/1056

**Comment by alwin-joseph** [comment]
Closing this as all the failing tests related to migration of TCK are fixed now.

**Comment by mkarg** [comment]
@alwin-joseph I think there is something wrong with the project book keeping. This issue is contained on both projects, EE 9 and EE 10. But it is Done in one and In Progress in the other. Is that by intention?

**Comment by alwin-joseph** [comment]
> @alwin-joseph I think there is something wrong with the project book keeping. This issue is contained on both projects, EE 9 and EE 10. But it is Done in one and In Progress in the other. Is that by intention?

We were following the project board https://github.com/orgs/eclipse-ee4j/projects/22 (Jakarta 10) to track some of the TCK work where it was updated as _Done_ correctly.

I do not have the rights to change it in project board https://github.com/eclipse-ee4j/jaxrs-api/projects/3, owned by jaxrs team. Not sure if they are supposed to be updated automatically when the issue is closed.
