### ISSUE TITLE
CD job for the API publishing does not publish parent pom to staging

### ISSUE THREAD

**Issue by senivam** [eclipse-ee4j/jaxrs-api#1253]
The job that is being used to publish API to staging does not properly publish the parent pom to the staging. In order to work correctly the job shall be modified to run the build using 
`-pl .,:jakarta.ws.rs-api` from the root project folder (`${WORKSPACE}`) or `-pl :project,:jakarta.ws.rs-api` from within the `${BUILD_DIR}` which is defined as `"${WORKSPACE}/jaxrs-api/"` otherwise job wont publish the parent pom again and the #1252 would be reopened

**Comment by spericas** [comment]
@senivam New run has pushed parent pom. Could you check this again?

**Comment by senivam** [comment]
now we fixed it with @jim-krueger So, confirmed as fixed
