### ISSUE TITLE
Clarify if Feature implementations can be auto-discovered via @Provider

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/jaxrs-api#583]
I already brought up this issue on the mailing list in early 2017. Please see [this discussion](http://download.oracle.com/javaee-archive/jax-rs-spec.java.net/users/2017/04/4281.html) for reference.

The javadocs of most providers (like `MessageBodyWriter`, `ContainerResponseFilter`, `DynamicFeature`, etc) explicitly mention that implementations can be automatically discovered if annotated with `@Provider`.

Unfortunately the docs of `Feature` does not mention this, which may lead to the impression, that automatic discovery of `Feature` is not supported. However, automatic discovery works fine in Jersey. And people may expect auto-discovery to work for `Feature`, because it is explicitly supported for `DynamicFeature`.

One argument that came up in the discussion was that `Feature` can be used both on the server and on the client side, but auto-discovery only works on the server. However, I really think that this can be explained in the docs with something like:

> Features implementing this interface MAY be annotated with `@Provider` annotation in order to be discovered by JAX-RS runtime when scanning for resources and providers. Please note that this will only work for server side features. Features for the JAX-RS client must always be registered programmatically.

What do you think?

**Comment by mkarg** [comment]
Still collecting more implementors, stay tuned. :-)

**Comment by chkal** [comment]
No problem. I just wanted to file this as an issue and request for clarification, because back then I just posted on the EG list.

**Comment by spericas** [comment]
A lot of providers can be used in the client and the server, so that's really not a very good argument. I think this is likely an omission; I recall that Feature and DynamicFeature were somewhat of a late addition.

**Comment by mkarg** [comment]
Maybe our project is the wrong place for this issue, as it feels more like a spec issue to me, and the spec will IIRC into a different project. It might be correct to suspend this thread and move it into that other project later?

**Comment by chkal** [comment]
Actually most issues will affect all three repositories: The API, the spec document and the TCK. I guess the question is where the issues which affect multiple repositories should be managed.

Apart from that: AFAIK the issue discussed here just affects the javadocs of the `Feature` interface. So IMO it is the correct place for this issue.

**Comment by chkal** [comment]
@spericas So are you +1 for adding a note about the support for auto-discovery via `@Provider` on the server side to the javadocs of the `Feature` interface? If so, I would love to provide a pull request against `2.2-SNAPSHOT`.

**Comment by spericas** [comment]
@chkal Yes, I am. However, it would nice to review the behavior in the major implementations. I believe @mkarg said he was collecting that info.

On the topic of issues, let's all file them here. Perhaps we can uses labels: "api", "spec" and "tck" or something similar.

**Comment by mkarg** [comment]
I will talk to CXF and RESTeasy but as of today I am still searching for the correct person at CXF - the ones I asked so far had no clue; I'm iterating down the list of CXF PMC members currently. Stay tuned. :-)

**Comment by mkarg** [comment]
@asoldano Great to have you here! Can you please review _this_ issue, and #565, from RESTeasy's angle of view? That would be terrific! :-)

**Comment by chkal** [comment]
@mkarg Thanks a lot for taking care of this.

**Comment by asoldano** [comment]
@mkarg AFAIK, when it comes to RESTEasy, the @Provider annotated features are registered here https://github.com/resteasy/Resteasy/blob/4.0.0.Beta2/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java#L401 . That means, the behavior is affected by the way the rest application has been deployed; this said, in the common JAX-RS scenarios, scanning should be enabled, so the annotated server side features are auto-discovered.

**Comment by spericas** [comment]
I think we should add the statement proposed by @chkal unless there are any strong objections.

**Comment by chkal** [comment]
@spericas: I could prepare a pull request. We could then let everyone vote on it!?

**Comment by johnament** [comment]
So with this change, any `@Provider` must be discovered automatically, correct?  E.g. If it implements one of the server side providers, when the server boots it must be registered.

**Comment by chkal** [comment]
@johnament: That's the behavior already specified today. See JAX-RS 2.1 chapter 4:

> All application-supplied providers implement interfaces in the JAX-RS API and MAY be annotated with `@Provider` for automatic discovery purposes; the integration of pre-packaged providers into the JAX-RS runtime is implementation dependent.

This issue is just about the fact that all server-side SPIs except for `Feature` explicitly mention the support for auto-discovery in the javadocs.

**Comment by mkarg** [comment]
@chkal Still want to prepare a PR?

**Comment by chkal** [comment]
@mkarg Yeah, sure! Sorry about the delay. I'm quite busy working on the JSR371 TCK at the moment.

**Comment by chkal** [comment]
Please see #620 for the corresponding pull request.

**Comment by mkarg** [comment]
Closing this issue, as it has been fixed in 2.1.1.
