### ISSUE TITLE
[INFO] "There are 984 checkstyle errors"

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#587]
```
[INFO] --- maven-checkstyle-plugin:2.12.1:checkstyle (default) @ javax.ws.rs-api ---
C:\Users\Markus\git\jaxrs-api\jaxrs-api\src\main\java\javax\ws\rs\client\FactoryFinder.java:48:76: unexpected token: )
C:\Users\Markus\git\jaxrs-api\jaxrs-api\src\main\java\javax\ws\rs\core\Response.java:1230:9: unexpected token: public
C:\Users\Markus\git\jaxrs-api\jaxrs-api\src\main\java\javax\ws\rs\ext\FactoryFinder.java:48:76: unexpected token: )
C:\Users\Markus\git\jaxrs-api\jaxrs-api\src\main\java\javax\ws\rs\ext\MessageBodyWriter.java:83:5: unexpected token: public
C:\Users\Markus\git\jaxrs-api\jaxrs-api\src\main\java\javax\ws\rs\sse\FactoryFinder.java:48:76: unexpected token: )
C:\Users\Markus\git\jaxrs-api\jaxrs-api\src\main\java\javax\ws\rs\sse\Sse.java:47:5: expecting RCURLY, found 'default'
C:\Users\Markus\git\jaxrs-api\jaxrs-api\src\main\java\javax\ws\rs\sse\SseEventSource.java:239:5: unexpected token: default
[INFO]
[INFO] There are 984 checkstyle errors.
```

**Comment by mkarg** [comment]
It would be great if somebody would find the time to fix this **984** checkstyle errors! :-)

**Comment by chkal** [comment]
Maybe we could just adjust the checkstyle config. Usually the default configuration is a bit "strict". :laughing:

**Comment by spericas** [comment]
+1 on adjusting the config

**Comment by mkarg** [comment]
@chkal Any proposal for a _wise_ config?

**Comment by chkal** [comment]
My guess is that there are some rules which are violated VERY often which causes this high number of violations. I'll try to find some time in the next days to have a deeper look at it.

Can you assign this issue to me although I'm not a committer? Not sure if GitHub allows this.

**Comment by spericas** [comment]
@chkal We should nominate you as a committer.

**Comment by chkal** [comment]
@spericas: Thanks a lot! I would be happy to join!

**Comment by mkarg** [comment]
@chkal I tried to assign the issue to you but Githab does not accept that.

@spericas I support your proposal and would like to nominate Christian using the "officially" intended way, but I do not understand how and where I have to send the nomination. Do we simply vote on the dev mailing list, or do I have to use a special EF resource to nominate him for election?

**Comment by chkal** [comment]
I just had a quick look at the Checkstyle results. I updated Checkstyle to the latest version, removed/adjusted some rules that are violated very often ("lines not longer than 120 characters" or "parameters should be final") and we are down to 88 violations. I'll create a PR against `2.2-SNAPSHOT` if you agree. I'll list the adjustments in the PR so we can discuss them if desired.

**Comment by mkarg** [comment]
@chkal Please assign issue back to you as soon as Github lists you as a commiter. :-)

**Comment by mkarg** [comment]
PR #677 would reduce the actual number of checkstyle errors from 260 to 50, so I think it would be a good thing to continue the open discussion in #601 and replace "historic Oracle style" by "EE4J style" as the next measure w.r.t #587.

**Comment by arjantijms** [comment]
PR #667 has been merged. Closing this issue.
