### ISSUE TITLE
Provide api to allow SseBroadcaster.close without cascading effect  

### ISSUE THREAD

**Issue by jimma** [eclipse-ee4j/jaxrs-api#597]
When there is a sink that is used via a broadcaster but also outside of it, close broadcaster will close this sink now. We need an api to do close without  a cascading effect

**Comment by spericas** [comment]
Created PR https://github.com/eclipse-ee4j/jaxrs-api/pull/603

**Comment by mkarg** [comment]
Closing this issue as I merged Santiago's PR #603 into master already.
