### ISSUE TITLE
Clarification on the way to handle various HTTP response codes

### ISSUE THREAD

**Issue by NicoNes** [eclipse-ee4j/jaxrs-api#606]
Can the JAVA SSE spec be more clear on how to handle all various response codes possible, the way  https://html.spec.whatwg.org/multipage/server-sent-events.html does ?

The java SSE spec only talks about 503 but what   about others response codes:

**1.** 204

According to WHATWG spec:

> Clients will reconnect if the connection is closed; a client can be told to stop reconnecting using the HTTP 204 No Content response code.

- Does JAXRS SSE impl should interpret this code the same way ?

- If true should we close the SseEventSource and invoke the completion listener/onComplete to notify user about the eventSource completion?

- Should 204 be treated as unrecoverrable error =>  Do we have to notify error callback ? 

**2.** 503

- Do we have to notify error callback wheither the "retry-after" is set or not? Or just when the "retry-after" is not set.

**3.** Response code other than 200, 204 and 503

According to WHATWG spec (https://html.spec.whatwg.org/multipage/server-sent-events.html#sse-processing-model):

> Any other HTTP response code not listed here, as well as the cancelation of the fetch algorithm by the user agent (e.g. in response to window.stop() or the user canceling the network connection manually) must cause the user agent to fail the connection.

- Should JAXRS impl do the same and only accept 200, 204 and 503?
- If true  should those response codes be treated as unrecoverrable error =>  Do we have to notify error callback ?

A more general question:

Once SseEventSource is closed should the completion callback be always invoked even if no event consumer has never been triggered ?

Thanks

**Comment by mkarg** [comment]
@NicoNes Can you please a bit more specific what you propose to be changed in the spec?

**Comment by NicoNes** [comment]
You're right it was not that clear.

As it is done by the HTML5 SSE spec, I would like the JAVA SSE spec to be explicit on how SseEventSource must handle various HTTP response codes.

To do so and in order not to be that far form the HTML5 spec,  I suggest to follow its rules as much as possible.

So to be specific, I would like the spec to state that:

- On HTTP 204 response code

```
The SseEventSource must close itself and not try to reconnect.
It must invoke:
- completion handlers since no further events will be received.
```

- On HTTP 200 response code **with Content-Type set to text/event-stream** ( ignoring any MIME type parameters)

```
The SseEventSource must start processing incoming events.
It must invoke:
- event consumers each time a new event is received.
- error consumers when the SseEventSource encounter any uncoverable error. 
  And in this error case, it must close itself and invoke completion handlers since no
  further events will be received.
```

- On  HTTP 200 response code **with Content-Type other than text/event-stream**

```
The SseEventSource must close itself and not try to reconnect.
It must invoke:
- error handlers since it is an unrecoverable error. (Contrary to the 204 wich is a valid response)
- completion handlers since no further events will be received.
```

- On HTTP 503 **with retry-after set**

```
The SseEventSource must try to reconnect itself using the delay set in the retry-after header.
It must NOT  invoke:
- error handlers since it is not an unrecoverable error given that the recovery mechanism is
  reconnect.
- nor completion handlers since further events will be received
```

- On HTTP 503 **without retry-after**

```
The SseEventSource must close itself and not try to reconnect.
It must invoke:
- error handlers since it is an unrecoverable error.
- completion handlers since no further events will be received.
```

- On any HTTP response code other than the ones listed above

```
The SseEventSource must close itself and not try to reconnect.
It must invoke:
- error handlers since it is an unrecoverable error.
- completion handlers since no further events will be received.
```

Does those spec changes/clarification seems reasonable to you ?

**Comment by mkarg** [comment]
@NicoNes @deki @jansupol @andymc12 I think this should be discussed among vendors mostly.

**Comment by andymc12** [comment]
Today, it looks like Apache CXF handles the 204 as stated above (closes the connection, does not reconnect).  We are in the process of implementing the 503 behavior - if Retry-After is specified, set the appropriate reconnect delay.  

On a 503 with no Retry-After specified, I think the current behavior would be to try to reconnect using the current reconnectDelay setting (500ms by default).  It sounds like this is probably not the ideal behavior.  

Also, I think CXF will attempt to read events from any response code (other than 204 or 503+Retry-After).  This may also be compliant with the JAX-RS spec, but not the behavior expected by HTML5.

In general, I agree with this proposal.  I think we should also be tolerant of redirects (301 and 307) - either automatically follow redirects or surface an error so that the app could retry with the new location.

**Comment by mkarg** [comment]
@andymc12 Will you sponsor this issue? So I would assign it to you now.

**Comment by andymc12** [comment]
@mkarg Sure, I can take this issue.  

@spericas, all, do you agree with the proposal from @NicoNes ? Basically:

| Response Code is: | Client Behavior is: |
| ------------------------ | ----------------------- |
| 200                         | Listen for events until closed - reconnect (using default or configured reconnect delay) on network issue until client source is closed |
| 204                         | Do not listen - do not reconnect |
| 503 - `Retry-After` set to valid value | Automatically change the reconnect delay to the value set in `Retry-After` and reconnect unless the client source has closed prior to reconnecting |
| 503 - No or invalid `Retry-After` set | Do not listen - do not reconnect |
| 301 / 307                | Automatically follow re-direct? Surface the redirect URI so the client knows it needs to change? |
| All others                 | Do not listen - do not reconnect |

Thanks, Andy

**Comment by NicoNes** [comment]
Hi guys,

Thank you for taking this issue. 
In addition to global client behavior, do you also agree with completion/error handlers notification policy described for each response code?

**Comment by NicoNes** [comment]
Any answer guys ?

**Comment by andymc12** [comment]
@spericas that was my recollection also.  I'll try to have a PR to "spec-ify"  this behavior soon (hopefully by the end of the week).

**Comment by andymc12** [comment]
I still think this is a good thing to clarify, but as I mentioned in the [PR](https://github.com/eclipse-ee4j/jaxrs-api/pull/670#issuecomment-442965532), I don't have time to complete it.  I'm unassigning myself, but somebody else is more than welcome to use what I've contributed so far to complete this.

**Comment by andymc12** [comment]
During the code review for the CXF implementation of this feature, @reta noticed that the implementation is calling both `onError` and `onComplete` callbacks.  This behavior is correct now that #670 is merged, but his concern is that we should only be calling one or the other, not both in order to stay consistent with the Java 9 Flow API.  I was not involved with the expert group in the 2.1 early stages, but it does seems like many of the of SSE APIs were intended to be consistent with Flow.

For those who were involved with the code review for #670 (@spericas, @asoldano  - and @NicoNes for proposing these clarifications), do you think we should change the javadoc to state that only one callback `onError` _or_ `onComplete` is invoked?

Thanks, Andy

**Comment by NicoNes** [comment]
Yep I think that it will be better to make it clear in the doc that  `onError` must only be invoked in case of exceptional completion and `on Complete` in case of normal completion.

**Comment by spericas** [comment]
As stated in the spec document, the inspiration for the API was really JavaScript's `EventSource`, except that there is no `onComplete` there if I recall correctly. Restricting the calls of `onError` and `onComplete` to be mutually exclusive would only make sense if all errors are unrecoverable, which I don't think is the case here. 

Perhaps someone can double check this in the SSE spec, but I think errors can be reported for, say, an individual message without the connection being close. I.e.,
```
onOpen (onEvent | onError)* onComplete
```

**Comment by NicoNes** [comment]
> As stated in the spec document, the inspiration for the API was really JavaScript's EventSource, except that there is no `onComplete ` there if I recall correctly

Right 

--

According to the JavaScript `EventSource` spec, the `onError` is invoked when the connection fails to be opened. Theres is two cases :

- "Network errors that prevents the connection from being established in the first place (e.g. DNS errors), should cause the user agent to reestablish the connection in parallel, unless the user agent knows that to be futile, in which case the user agent may fail the connection."

- "fail of connection" due to : 
   - "HTTP 200 OK responses that have a Content-Type specifying an unsupported type, or that have no Content-Type at all, must cause the user agent to fail the connection."
  - "Any other HTTP response code not listed here, as well as the cancelation of the fetch algorithm by the user agent (e.g. in response to window.stop() or the user canceling the network connection manually) must cause the user agent to fail the connection."
  - Unrecoverable network error. (see first case)

So based on my interpretation of the JavaScript `EventSource` spec, the `onError` is really for unrecoverable error, except first case of recoverable network error leading the user agent to reestablish the connection in parallel.

So let's go back to our JAVA api:

- `onComplete` is to be invoked in case of normal completion due to 204 response or `close()` invocation
- `onError` is to be invoked in case of uncoverable error leading to connection not established at all. This can be due to response other than 200 or response with the wrong media type or network error at connection time.
 I don't think that the case of recoverable network error  leading to the user agent to reestablishing the connection in parallel worth to be handled by the JAVA SSE API. Because most of the time the underlying client implementation used by the `SseEventSource` will perform retry automatically before throwing any network error. So I  think that it is acceptable to consider all network exception at connectiontime, as unrecoverable and any new connection attempt as futile since underlying client already tried before throwing network error.

WDYT?

**Comment by reta** [comment]
@NicoNes sound it, moreover the JAX-RS javadocs are explicitly pointing to (https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/sse/SseEventSource.html):

> Event consumer is invoked once per each received event, Throwable consumer is invoked invoked upon a unrecoverable error encountered by a SseEventSource, onComplete callback is invoked when there are no further events to be received.

Thank you.

**Comment by spericas** [comment]
@NicoNes Yeap, that seems to be correct. It is the WebSockets API that allows for `onError` to be called in the way I was thinking about. I'm OK with the proposed update then.

**Comment by andymc12** [comment]
The behavior (including a note about onComplete vs onError) has been clarified in the 3.0 (master) and 3.1 (3.1-SNAPSHOT) streams.  

@NicoNes do you agree that we can close this issue?  Thanks!

**Comment by NicoNes** [comment]
Hey @andymc12,

Yes, this one can be close. Thanks :+1:

**Comment by mkarg** [comment]
Do we need to mention this in the spec, at least in the history appendix?
