### ISSUE TITLE
Query parameter ordering not guaranteed to stay the same

### ISSUE THREAD

**Issue by cowwoc** [eclipse-ee4j/jaxrs-api#613]
Some use-cases (e.g. https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#signed-trade-and-user_data-endpoint-security) requires one to be able to look up the query parameter string and request body before actually sending out the request. In the aforementioned case, we are supposed to use these values to generate a hash where ordering maters.

Looking at the Javadoc, there doesn't seem to be any explicit guarantee that the constructed URI will maintain the ordering of the query parameters. Specifically, nothing guarantees that `getUri()` will return the same ordering every time, nor that ordering will be kept when I add a new query parameter (e.g. `signature`). I am worried that `a=1&b=2&c=3` could turn into `b=2&c=3&a=1&signature=<hash>`.

Is there a reasonably safe way for the specification to support this use-case?

**Comment by mkarg** [comment]
Is there a RFC that guarantees order of parameters?

**Comment by cowwoc** [comment]
@mkarg The only guarantee that binance seems to ask for is that the signature corresponds to the order of parameters that the client sends (what the server does with it is another story). Are you saying that if there are intermediate gateways they might reorder the parameters?

**Comment by chkal** [comment]
I think @mkarg is thinking about the HTTP or some other RFC and what they write about query parameter ordering...

**Comment by mkarg** [comment]
As long as there is no RFC guaranteeing such a preserve-of-order, any intermediate party (like proxies, routers, gateways, etc.) is allows to reorder as wanted. So it makes no sense to enforce something in the backend only.

It makes no sense to collect a proof for actual reordering. This is an API Specification project, so we have to think revers: We need a proof that no party might reorder.

**Comment by mkarg** [comment]
@cowwoc Well... does "the aren't interested in further discussion" mean that I can close this issue now?

**Comment by cowwoc** [comment]
> @cowwoc Well... does "the aren't interested in further discussion" mean that I can close this issue now?

Sadly, yes. Thanks for the clarification.
