### ISSUE TITLE
Missing Committer's Paperwork

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#617]
There is a strong discrepancy between the list of [official commiters](https://projects.eclipse.org/projects/ee4j.jaxrs/who) (Eclipse Foundation) and the list of [actual committers](https://github.com/orgs/eclipse-ee4j/teams/eclipse-jaxrs/members) (Github). We should try to get both lists look the same, so if your name is on *just one* list (i. e. missing on the other):
* If you do **not** want to be a committer anymore, please express your will by writing to emo@eclipse-foundation.
* If you **want** to be a committer, please file the needed paperworks.

If you need help with either of these, just answer here and I will try to help you.

_Don't get me wrong: I do **not** want anybody to get out of the boat, but I want to everybody get into the boat **now** so we can increase project progress! :-)_

**To speed things up, please don't mind me nudging you a bit with this thread! :-)**

**Comment by mkarg** [comment]
@arjantijms Please file your paperworks! :-)

**Comment by arjantijms** [comment]
I should have filed all the paperwork there is to file. Which ones are missing?

**Comment by arjantijms** [comment]
At least all the Eclipse paperwork should be okay, as I got confirmation and I'm listed for both JAX-RS and Jersey: https://accounts.eclipse.org/users/atijmse7y#tab-projects

I'm not listed here though: https://github.com/orgs/eclipse-ee4j/people

Who do I ask for that?

**Comment by mkarg** [comment]
@waynebeaton Wayne, can you please help? Why is Arjan not a JAX-RS committer in Github?

**Comment by waynebeaton** [comment]
AFAICT, @arjantijms needs to specify his GitHub ID on his Eclipse Foundation account.

https://accounts.eclipse.org/user

**Comment by mkarg** [comment]
@waynebeaton Thanks a lot! :-)
@arjantijms Did you do that?

**Comment by arjantijms** [comment]
Well, yes and no. My GitHub ID was associated with another account I have on eclipse.org and eclipse.org didn't allow me to make the association. But I removed it from the other account and added it to the current account. So hopefully all is well now.

Thx!

**Comment by waynebeaton** [comment]
If you're still having trouble, connect with webmaster@eclipse.org

**Comment by arjantijms** [comment]
@waynebeaton @mkarg Thanks to both of you, it now seems to work. I got the group invitation for EE4J on GitHub :)

**Comment by mkarg** [comment]
@waynebeaton Thanks for helping! :-)
@arjantijms As you're now listed on Github (https://github.com/orgs/eclipse-ee4j/teams/eclipse-jaxrs/members) you should have the power to officially **review and assign** PRs. We love to see your votes! :-)

**Comment by arjantijms** [comment]
Closing issue as everything seems to be fine now, thanks again to all involved.

**Comment by arjan** [comment]
wrong guy :-P

**Comment by arjantijms** [comment]
Believe it or not, but there are more Arjans in the world :P In fact, it's quite a common name in the Netherlands ;)

**Comment by mkarg** [comment]
@asoldano Apparently you have not finished the EF paperworks. Can I help you with that? I assume you really like to have committer status in Github, not only being listed as a committer on the EF page?

**Comment by asoldano** [comment]
@mkarg I definitely want to have committer status on Github too. This said, I believe I completed the paperworks weeks ago. I've just re-checked and I had empty fields in the "social media" section, which also includes github. I've added my gihub id there, so I hope everything's fine now. Can you double check that? Note, I get a 404 error when trying opening the https://github.com/orgs/eclipse-ee4j/teams/eclipse-jaxrs link you mentioned above.

**Comment by rogergl** [comment]
@mkarg not sure if I did all the paperwork. So far I only signed the ' Eclipse Contributor Agreement'.

**Comment by mkarg** [comment]
@rogergl As your current target role is _Contributor_ only (not _Committer_), filing the ECA (Eclipse Contributor Agreement) is sufficient. You can now simply join the ongoing discussions in the mailing list / issue tracker / PRs, or ask to get issues assigned to you so you can prepare solutions and file PRs. :-)

**Comment by mkarg** [comment]
@asoldano You should be able to assign issues / PRs to you and be a Github reviewer now. Welcome! :-)

**Comment by mkarg** [comment]
@kwsutter Kevin, I wonder why you are listed as JAX-RS committer on the Eclipse Project page, but not on the Github Project page. As you are a PMC member I assume this is by intention?

**Comment by chkal** [comment]
AFAIK this happens if the GitHub username is missing in the Eclipse account settings.

**Comment by mkarg** [comment]
FYI: Tody I triggered the process to get all _still_ missing contributors listed on the Eclipse project page into the Github boat with the kind help of @m0mus and webmaster@eclipse.org. I hope that in few weeks all of them finally are here, because I think it is an essential step towards leaving incubator status to reach congruency between the Eclipse Foundation's files and Github's configuration. I'm trying to keep everybody informed, but for those who like to observe, just frequently check https://github.com/orgs/eclipse-ee4j/teams/eclipse-jaxrs/members. :-)

**Comment by mkarg** [comment]
Welcome committers @yuHe1 and @weijuntian on GitHub! Please be so kind to shortly introduce yourself to the other committers on the existing welcome round thread on the developer's mailing list! :-)

**Comment by mkarg** [comment]
@eclipsewebmaster: Still missing PMC Member Kevin Sutter @kwsutter, Steven Liu @liuxiangde and Yan Gao.

**Comment by liuxiangde** [comment]
@mkarg, I should have finished the committer paperwork weeks ago and my eclipse account setting is associated with my github ID. Is there something missing and what I should do? Thanks

**Comment by liuxiangde** [comment]
BTW, I got 404 when I access https://github.com/orgs/eclipse-ee4j/teams/eclipse-jaxrs/members

**Comment by gaoyan-gao** [comment]
@mkarg , I am listed for both [official commiters](https://projects.eclipse.org/projects/ee4j.jaxrs/who) (Eclipse Foundation) and the list of [actual committers](https://github.com/orgs/eclipse-ee4j/teams/eclipse-jaxrs/members) (Github). My ID is "yan gao" in Eclipse Foundation list. And my ID is "gaoyan-gao" in Github.

**Comment by gaoyan-gao** [comment]
And all my Eclipse paperwork should be okay, as I got confirmation and I'm listed for both JAX-RS and Jersey. https://accounts.eclipse.org/users/ygao#tab-projects

**Comment by gaoyan-gao** [comment]
@mkarg I am also listed for https://github.com/orgs/eclipse-ee4j/people .
Thanks.

**Comment by edbratt** [comment]
Steven,
You should have received an e-mail notifying you that you have been 
invited to the eclipse-jaxrs project. I can see your invitation is still 
pending your acceptance. Once you accept that invitation, you should be 
good to go.
-- Ed

**Comment by mkarg** [comment]
@gaoyan-gao Thank you for your answer. I found you in the list now. My fault. Sorry for the confusion. :-)

**Comment by mkarg** [comment]
@liuxiangde Can you please accept the invitation Ed sent you report here when done? So I can check whether your listed now as committer on Github then. Thanks.

**Comment by liuxiangde** [comment]
Thanks @edbratt, 

@mkarg I missed the invitation sent to my email associated with my github account. I accept the invitation now and I can see I'm listed in https://github.com/orgs/eclipse-ee4j/teams/eclipse-jaxrs/members and https://github.com/orgs/eclipse-ee4j/people now.

**Comment by mkarg** [comment]
Welcome committers @kwsutter and @liuxiangdeon GitHub! Please be so kind to shortly introduce yourself to the other committers on the existing welcome round thread on the developer's mailing list! :-)

**Comment by mkarg** [comment]
Thank you everybody for your patience. I will double-check tomorrow but I think all initial committers are actual Github committers now! Welcome, again! :-)

**Comment by mkarg** [comment]
Unfortunately there still is one person missing. Does somebody have a current contact address of Rebecca Searls? Thanks. :-)

**Comment by mkarg** [comment]
Welcome committer @rsearls! Please be so kind to shortly introduce yourself to the other committers on the existing welcome round thread on the developer's mailing list! :-)

**Comment by mkarg** [comment]
@eclipse-ee4j/eclipse-jaxrs Welcome all committers! If not done yet, please shortly introduce yourself on the existing welcome round thread on the developer's mailing list! :-)

As the last missing paperwork was done, were complete now. I am happy that everybody proposed by the EF is onboard of GitHub now. So I am glad to close this ticket finally. :-)
