### ISSUE TITLE
Non-blocking client API

### ISSUE THREAD

**Issue by cowwoc** [eclipse-ee4j/jaxrs-api#626]
According to http://download.oracle.com/javaee-archive/jax-rs-spec.java.net/users/2017/01/4079.html (and looking at the source-code of Jersey) the RX client implementation is really just `CompletionStage` bolted on top of a blocking request.

Please add the ability to issue non-blocking HTTP calls that return `CompletionStage` on the client.

**Comment by mkarg** [comment]
Feel free to send a PR. :-)

**Comment by mkarg** [comment]
@cowwoc Do you really think this is an issue of the JAX-RS API, or are you talking about Jersey-specific implementation?

**Comment by cowwoc** [comment]
@mkarg It could be Jersey-specific. That said, I am not aware of what the other implementations do. Are you aware of any of them implementing `CompletionStage` on top of a non-blocking / NIO.2 architecture?

**Comment by mkarg** [comment]
@cowwoc I am not aware of any vendor's internals. So let's just ask them directly: @deki @jansupol @asoldano @andymc12.

**Comment by deki** [comment]
Well the discussion in the mailinglist was initiated by Sergey who was implementing the stuff for CXF. CXF has multiple extensions for NIO: 
http://cxf.apache.org/docs/jax-rs-rxjava.html, http://cxf.apache.org/docs/jax-rs-project-reactor-support.html and http://cxf.apache.org/docs/jax-rs-nio.html (for the server side)

**Comment by cowwoc** [comment]
@deki Please excuse my ignorance on the matter but in the case of Jersey there is no relationship between Async, CompletionStage responses and the actual request being non-blocking. Out of the 3 documents you linked to, only the 3rd one talks about non-blocking communication. Hence, I don't think there is any guarantee that the client-side is in fact non-blocking.

**Comment by deki** [comment]
I agree that reactive and non-blocking stuff was mixed up, but as far as I can see the RX/ Reactor client stuff is implemented in a non-blocking way. Async Http Client is used for that: http://cxf.apache.org/docs/asynchronous-client-http-transport.html

**Comment by mkarg** [comment]
@cowwoc The API only defines the programming _interface_. _How_ the interface is fulfiled is part of the particular product design. We do not intend to mandate _particular_ designs.

**Comment by cowwoc** [comment]
@mkarg I understand that and did not mean to imply otherwise. I just want to make sure that nothing in the interface prevents one from implementing a non-blocking Async and Rx requests.

**Comment by mkarg** [comment]
@cowwoc Please check the spec PDF and the Javadocs. Only these are normative. :-)

**Comment by cowwoc** [comment]
@mkarg I feel like we're going in circles. I know that only the spec is normative.

Sometimes one publishes out a design that theoretically should support (say) non-blocking I/O but in practice when one tries to implement it you discover that something in the design makes this difficult or impossible. I am asking about concrete implementations simply to rule out this possibility.

On the topic of whether JAX-RS should mandate whether the implementation uses a blocking or non-blocking API: shouldn't the user be able to choose the desired behavior? After all, if this wasn't important why would `CompletableFuture` let users choose? Certainly such a decision has an important performance impact.

**Comment by asoldano** [comment]
This looks indeed implementation specific. RESTEasy, for example, allows to plug in different client http engines; there's a default async/NIO one based on Apache Async Http Client (http://docs.jboss.org/resteasy/docs/3.5.1.Final/userguide/html/RESTEasy_Client_Framework.html#apache_asynch), alternatively users can provide their engine implementation. A implementation based on Jetty 9 is coming in next release, for example.

**Comment by cowwoc** [comment]
Okay, I'll go ahead and close this issue then.
