### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#634]
Nightly builds are an open source best practice.

**Comment by mkarg** [comment]
I'm already in contact with the EF admins to set this up using the EF's internal infrastructure (Jenkins + Nexus) and currently learning how to do it with Multi-Branch-Plugin+Jenkinsfile.

**Comment by mkarg** [comment]
From EF Admins:
>https://bugs.eclipse.org/bugs/show_bug.cgi?id=535778
>Product/Component: Community / Nexus
>
>--- Comment #21 from Frederic Gurr <frederic.gurr@eclipse-foundation.org> --- The JAX-RS JIPP is now setup at https://ci.eclipse.org/jaxrs/
>
>Committers should now be able to login and create jobs. Please note that you will need to login with your _email_ address as your username.
>
>If you require additional plugins feel free to reopen this bug and list them.
>
>Finally we can optionally allow the JIPP user to have write access anywhere the project group has access to including downloads area. We can also give it write permissions to your git repositories. This could be useful if you'd like to use Jenkins for automated build promotion, but keep in mind there is some risk in giving Jenkins more permissions than it needs. If you'd like to to enable this please reopen and let us know.
>
>
>To publish nightly builds, please follow the instructions here: 
>https://wiki.eclipse.org/Services/Nexus
>

**Comment by mkarg** [comment]
From EF Admins:
>The following repos were created for JAX-RS API.
>
>group:     https://repo.eclipse.org/content/repositories/jax-rs-api/
>releases:  https://repo.eclipse.org/content/repositories/jax-rs-api-releases/
>snapshots: https://repo.eclipse.org/content/repositories/jax-rs-api-snapshots/
>
>Details on how to use repo.eclipse.org can be found on the wiki at >https://wiki.eclipse.org/Services/Nexus

**Comment by chkal** [comment]
@mkarg Thanks, Markus! The login works fine for me.

Is this a Jenkins instance from the new setup the `ee4j-build` guys are working on?

**Comment by chkal** [comment]
> I will now set up a multi-branch pipeline and a PR for Jenkinsfile stored within Github code repo (right now reading the docs for that), i. e. resembling the Travis CI file.

Awesome! Thanks a lot!

> FYI, this week I had several meetings with the EF (Mike, Ralph, Gael). They explain that the EF accepts that we use Github, but in fact they copy everything in their own infrastructure to be independent.

Makes sense to me. I would also be fine with using Jenkins instead of Travis if we get the same feature set (getting builds for pull requests, building against multiple JDKs, etc.).

**Comment by mkarg** [comment]
Using _only_ Jenkins is problematic because it can only use _either_ pipelines _or_ matrix. So with all the JDKs you like to test, Jenkinsfile will end in a mess.

**Comment by chkal** [comment]
> Using only Jenkins is problematic because it can only use either pipelines or matrix. So with all the JDKs you like to test, Jenkinsfile will end in a mess.

Ok. Agreed. IMO it is fine to use both. Jenkins for publishing snapshots and maybe other special builds and Travis for running tests for pull requests.

**Comment by mkarg** [comment]
Nightly builds (**Bleeding-edge CI snapshots for developers and early adopters**) to be found here since today: https://repo.eclipse.org/content/repositories/jax-rs-api-snapshots.

**These files are not intended for end-users. It is not a release.**

**Comment by spericas** [comment]
Markus,

 See e-mail from Dmitry on the other thread. 

— Santiago
