### ISSUE TITLE
Build the project with JDK11 fails

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/jaxrs-api#636]
Currently the build does NOT work when using the latest EA version of JDK11. See [this Travis build](https://travis-ci.org/chkal/jaxrs-api/builds/401181471) for details.

**Comment by chkal** [comment]
I guess this is caused by JDK11 not including JAXB any more, so the following config doesn't work any more:

https://github.com/eclipse-ee4j/jaxrs-api/blob/5ca037f209e916e4fff9df647ef0055dc9722b6b/jaxrs-api/pom.xml#L130-L135

**Comment by mkarg** [comment]
Right, simply *enabling* `javax.xml.bind` will *definitively* not work anymore on JDK 11. We must replace it by a Maven dependency on JAXB 2.3.1 or JAXB 2.4.0-SNAPSHOT. I assume the scope should be `provided`?

**Comment by chkal** [comment]
AFAIK the dependency is only required for the tests, so `test` would be a better fit.

BTW: I don't think it is a good idea to always add JAXB as a dependency, because it may cause weird effects with JDK8. So perhaps we should use profiles?

  * JDK8: No JAXB dependency and no `--add-modules` for surefire.
  * JDK9+: Add JAXB dependency and no `--add-modules` for surefire

Thoughts?

**Comment by spericas** [comment]
> On Sep 13, 2018, at 3:02 AM, Christian Kaltepoth <notifications@github.com> wrote:
> 
> AFAIK the dependency is only required for the tests, so test would be a better fit.
> 
> BTW: I don't think it is a good idea to always add JAXB as a dependency, because it may cause weird effects with JDK8. So perhaps we should use profiles?
> 
> JDK8: No JAXB dependency and no --add-modules for surefire.
> JDK9+: Add JAXB dependency and no --add-modules for surefire
> Thoughts?
> 
> 
 
 +1 for profiles.

— Santiago

**Comment by mkarg** [comment]
+1 for profiles. I have to go deeper into the code to see whether really only the tests are in trouble or whether we e. g. have a reference in Javadocs, too.

**Comment by mkarg** [comment]
I can certify that Christian's assumption was absolutely right, and that the cause *definitively* is the excession of JAXB out of the JRE since version 11:
```
[ERROR] /home/travis/build/mkarg/jaxrs-api/jaxrs-api/src/main/java/javax/ws/rs/core/Link.java:[26,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/travis/build/mkarg/jaxrs-api/jaxrs-api/src/main/java/javax/ws/rs/core/Link.java:[27,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/travis/build/mkarg/jaxrs-api/jaxrs-api/src/main/java/javax/ws/rs/core/Link.java:[28,42] package javax.xml.bind.annotation.adapters does not exist
[ERROR] /home/travis/build/mkarg/jaxrs-api/jaxrs-api/src/main/java/javax/ws/rs/core/Link.java:[560,45] cannot find symbol
[ERROR]   symbol:   class XmlAdapter
[ERROR]   location: class javax.ws.rs.core.Link
[ERROR] /home/travis/build/mkarg/jaxrs-api/jaxrs-api/src/main/java/javax/ws/rs/core/Link.java:[465,10] cannot find symbol
[ERROR]   symbol:   class XmlAttribute
[ERROR]   location: class javax.ws.rs.core.Link.JaxbLink
[ERROR] /home/travis/build/mkarg/jaxrs-api/jaxrs-api/src/main/java/javax/ws/rs/core/Link.java:[475,10] cannot find symbol
[ERROR]   symbol:   class XmlAnyAttribute
[ERROR]   location: class javax.ws.rs.core.Link.JaxbLink
[ERROR] /home/travis/build/mkarg/jaxrs-api/jaxrs-api/src/main/java/javax/ws/rs/core/Link.java:[568,9] method does not override or implement a method from a supertype
```

I'll now provide a PR with a profile-base fix, unless someone else tells me he already started this.

**Comment by chkal** [comment]
I was planning to prepare a PR in the next days. But I didn't start yet. So if you find some time to work on this, go ahead! That would be awesome!

**Comment by mkarg** [comment]
Done in private fork. But now it fails with missing Java Activation Framework. Heck! Why do we need JAF?!

**Comment by mkarg** [comment]
Found out that we need JAF because JAXB needs it, but the JAXB POM does not contain this dependency (in latest = 2.3.0). I checked current SNAPSHOT for JAXB (2.4.0) and it seems they solved that. So I assume we can remove the dependency once JAXB 2.4.0 is published.

**Comment by mkarg** [comment]
PR #660 is in second review week but has not enough approvals. I hope somebody chimes in and approves it besides myself, so I could effectively merge it next week.
