### ISSUE TITLE
Jakarta EE 8: Release JAX-RS 2.1.1

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#638]
The Eclipse Foundation aims to provide a common Jakarta EE 8 release, which means we should release JAX-RS 2.1.1 (i. e. more or less JAX-RS 2.1 + EPL + Essential Bug Fixes + our share of the TCK, hence content of our repo's `EE4J_8` branch).

This issue serves as a place for planning and performing that release.

Issues for this particular release can be found here: https://github.com/eclipse-ee4j/jaxrs-api/milestone/7.

**Comment by mkarg** [comment]
Is somebody already preparing this?

**Comment by spericas** [comment]
@mkarg Yes, I can work on this one. I will be running signature tests with the TCKs to make sure we can release this.

**Comment by mkarg** [comment]
@spericas Great! Thanks! :-)

**Comment by mkarg** [comment]
@spericas I have prepared nightly builds (see #643) on EF infrastructure, just in case you're ready to commit the TCK. :-)

**Comment by spericas** [comment]
@mkarg :-) Thanks, I will take a look.

**Comment by mkarg** [comment]
Now that we have nightly builds in EF Nexus and the release pipeline in OSSRH set up, what is open wrt the release? TCK? Spec? Bug collections? What shall people help with?

**Comment by spericas** [comment]
@mkarg With the help of @jansupol it was verified that 2.1.1-SNAPSHOT passes the TCKs. I think we should drop SNAPSHOT via a PR and start with the voting to push 2.1.1 to OSSRH (unless I'm missing some other step).

**Comment by mkarg** [comment]
@spericas Sounds good, but can we wait with this final PR until the weekend? I'd like to add some of the bug fixes we merged into 2.2-SNAPSHOT. I would send you a list with the commit IDs so you can add them to your PR. Or did you already do that (I did not find any in the EE4J branch)?

**Comment by spericas** [comment]
@mkarg I thought we had merged those when deleting 2.1.1-SNAPSHOT, but I guess they were not there. Yes, let's get those in and prepare the branch to kick off the release. I'll look for those commit IDs, but if you have them handy please paste them here.

**Comment by spericas** [comment]
I believe these are the two commits:

https://github.com/eclipse-ee4j/jaxrs-api/commit/c8e9d188767778a04c547d7b24e0ce885bd3a1e9
https://github.com/eclipse-ee4j/jaxrs-api/commit/4880f9ce2f41a2c70e91dd95edd3d7fbe7ee0535

Agreed?

**Comment by mkarg** [comment]
We could possibly merge more. What about adding these, too?

https://github.com/eclipse-ee4j/jaxrs-api/commit/82496b3d76f8339af444700ed8a2f540401310e4
https://github.com/eclipse-ee4j/jaxrs-api/commit/a292276056f0a8d938a62ec2abd3a9d3d07baec9
https://github.com/eclipse-ee4j/jaxrs-api/commit/a046a50d0dfc60c8e24002aa7a437b20ddcc9e91
https://github.com/eclipse-ee4j/jaxrs-api/commit/e781b332843f00c8776cd47c718008a676d9c75a
https://github.com/eclipse-ee4j/jaxrs-api/commit/5afcef5a33ad65554fef382593c7ec7c5bd850f5
50cab0b0a3ae69f8ebf2768ab5661c946f847428

**Comment by spericas** [comment]
@mkarg I have the last two ready in my fork. The other ones are OK except for e781b33 since I believe there was some discrepancy in the implementations and moving from 2.1 to 2.1.1 should require no changes IMO.

**Comment by mkarg** [comment]
@spericas Agreed, let's keep e781 out. Ok, so after few cherry-picks on your side we're ready to release, right? What about that EF release review stuff, is that ready or shall I prepare something?

**Comment by spericas** [comment]
@mkarg The commit message for this one:

https://github.com/eclipse-ee4j/jaxrs-api/commit/82496b3d76f8339af444700ed8a2f540401310e4

mentions version 2.2. I sort of understand why and would suggest that we leave it out as well for 2.1.1. Other than that, the PR is ready on my end.

**Comment by mkarg** [comment]
That was a typo. Actually it should read "According to JAX-RS 2.1 specification". So we could add it to 2.1.1.

**Comment by spericas** [comment]
@mkarg Ok, PR has been submitted.

**Comment by mkarg** [comment]
Release staged on OSSRH and passed validation: https://ci.eclipse.org/jaxrs/job/Publish%20Release/11/.
Next step is IP Approval and Release Review, according to https://docs.google.com/drawings/d/1ZoEf7lvzBOB1PIq7q7JdFbTvTlAgzCkvIiEDH-CYJL4/edit.

**Comment by spericas** [comment]
@mkarg My understanding is that we are on step 6 here:

https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects

So just need to kick off a new release on our project page. I'm confused about the IP Approval that you mentioned. What is that?

**Comment by mkarg** [comment]
@spericas I assume the term "IP Approval" found in the chart means step 9 in Dmiry's list.

**Comment by mkarg** [comment]
@spericas Ok, just ping me when I shall do something.

**Comment by spericas** [comment]
https://projects.eclipse.org/projects/ee4j.jaxrs/releases/2.1.1

@mkarg Do you have full access to view and edit the release?

**Comment by mkarg** [comment]
@spericas Yes, I could press "Save" (without changing anything) and it says "Updated release".

**Comment by spericas** [comment]
@mkarg Great, I filled out some basic info about the release now. If you want to start with (2) and (3) from your list, go ahead. Otherwise, I'll get back to this later.

**Comment by mkarg** [comment]
Okay I will do (2) and (3).

**Comment by mkarg** [comment]
@spericas (2) is done (https://projects.eclipse.org/projects/ee4j.jaxrs/releases/2.1.1/iplog/preview; https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17366).

**Comment by mkarg** [comment]
@spericas (3) is done (https://projects.eclipse.org/projects/ee4j.jaxrs/reviews/2.1.1-release-review; mail sent to PMC and EMO)

**Comment by mkarg** [comment]
@spericas (2) IP log is approved. http://dev.eclipse.org/ipzilla/show_bug.cgi?id=17366

**Comment by mkarg** [comment]
@spericas (3) PMC has approved release 2.1.1. Still waiting for EMO approval (review still is in pending state)

**Comment by mkarg** [comment]
@spericas (3) EF release review is successfully finished since yesterday (https://bugs.eclipse.org/bugs/show_bug.cgi?id=538340), so as announces I will technically release JAX-RS 2.1.1 to Maven Central on 2018-09-10. If you know any showstoppers then please let me know, otherwise this is the point of no return, as we cannot remove or update artifacts on Maven Central.

**Comment by spericas** [comment]
@mkarg No showstoppers that I know, green light!

**Comment by mkarg** [comment]
@spericas Pressed the button. It will take a while to sync. Should be available at The Central Repository on Monday (or even on Sunday).

**Comment by mkarg** [comment]
@spericas Wow, sync was pretty fast: Building Jersey mvn tells me `Downloaded from central: https://repo.maven.apache.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1.1/javax.ws.rs-api-2.1.1.jar (127 kB at 220 kB/s)`!

**Closing this issue with your kind permission, as this proofs we just successfully published our first release!**

**Comment by chkal** [comment]
Awesome! Thanks @mkarg!

BTW: AFAIK the sync to Maven central only takes about one hour. But the update of the search index on search.maven.org takes much longer.

**Comment by spericas** [comment]
Awesome, great job!

**Comment by mkarg** [comment]
Tagged as "2.1.1" so it shows up in Github "Releases" view now.
