### ISSUE TITLE
Deprecate @Context annotations

### ISSUE THREAD

**Issue by ggam** [eclipse-ee4j/jaxrs-api#639]
Once we have a complete CDI replacement for `@Context` annotations (tentatively on 3.0), they should be deprecated as a first step before removal on a later release.

**Comment by arjantijms** [comment]
@ggam isn't that replacement already available in the form of `@Inject`?

**Comment by ggam** [comment]
@arjantijms I'm actually with you. I think `@Inject` could deprecate `@Context` even on 2.2, but I think there's some consensus that 2.2 is too early.

This issue is just to trigger the needed discussions to make it happen as soon as possible. For me that would be 2.2, but we need to get @Path as a bean defining annotation (perhaps via a  `@Stereotype`), which I don't see done for 2.2.

**Comment by arjantijms** [comment]
Thanks @ggam 

I'm not really sure that there is much consensus that 2.2 is too early, especially when we have no idea yet when we're even able to release a 2.2.

Having `@Path` being bean defining or effectively causing beans with that annotation to be scanned is more of a nice to have than a big requirement IMHO. Might be worth it though to double check how this is done in the MVC spec with @chkal.

The reason why I'm pushing this a little is that I've seen how always thinking that it's too early has delayed this by many years in JSF. The native managed beans could already have been replaced by CDI in JSF 2.0 (2009), and when that window of opportunity was missed surely in JSF 2.2 (2013). But people kept being afraid that it was "too soon", meanwhile causing quite a bit of confusion. I'm fairly sure that if I didn't finally deprecate managed beans in JSF 2.3, they still wouldn't be deprecated today.

Although I think `@Path` doesn't have to be bean defining for a 2.2 release, it might be quite doable to have beans with the `@Path` annotation scanned by making use of a CDI extension, or indeed a stereo type.

**Comment by mkarg** [comment]
The point with 2.2 is that CDI is optional still in that release. If you want to deprecate @Context in favor of @Inject, this implies that you want to deprecate non-CDI in favor of CDI. It is a paradoxon to do that without making CDI mandatory.

**Comment by arjantijms** [comment]
The idea is to have `@Context` formally deprecated by actually putting an `@Deprecated` annotation on it, and then using an `@deprecated` annotation in Javadoc pointing to the usage of CDI.

In that case, of course, CDI *MUST* be supported by the implementations. User code however that doesn't use CDI (yet) can still run unchanged, as `@Context`, even though being deprecated still works.

`@Context` can then be actually removed (pruned) in 3.0.

**Comment by ggam** [comment]
I totally agree with you. In the last days of 2.1 I researched myself a bit
but I couldn't find a way to *portably* get @Path beans scanned by an
extension.

It is done in WildFly via propietary APIs. It's not the best solution and
it wasn't received with too much enthusiasm when I proposed it dor 2.1, but
would be a transitory solution. I opened a CDI issue related to this some
time ago: https://issues.jboss.org/browse/CDI-701

Provided that we find a way to get resources automatically detected as CDI
beans, I think we can deprecate the old DI on 2.2.

**Comment by mkarg** [comment]
While I understand your dreams and hopes (which I do share), just voting for a plan does not make it fulfilled in short term: You still need vendors willing to fill in human resources into that project in short term. Otherwise you would still need to wait. And so far I have not heared officially in this forum that any vendor agreed to our CDI-mandatory-for-vendors idea. So just +1'ing on the API project does not change much, unfortunately.

-Markus

**Comment by spericas** [comment]
We had some earlier discussions about this already. Even if we assume that all implementations support CDI (as stated in the spec today), the transition from `@Context` to `@Inject` is not as straightforward. That is, if a developer gets a deprecated message about `@Context`, it may take more than replacing it by `@Inject` for the application to work. 

As I argued before, we need to have a recipe that explains how to transition from one DI to another, and this is more than a simple annotation replacement:

 1. `@Context` in param position
 2. `@Context` with ContextResolvers
 3. ContextResolvers to configuration implementations (JAXB etc)
 4. Using `@Inject` for JAX-RS types like UriInfo, SecurityContext

And there's likely more.

**Comment by arjantijms** [comment]
>So if you want to follow that plan (which I second), please set up an official vote, so we have confidence.

vs

>So just +1'ing on the API project does not change much, unfortunately.

Am I the only one who sees some potentially conflicting statements there? If they're not conflicting, please explain ;) It's not a bad idea to start a vote about this.

Anyway, Payara, which uses Jersey, and to which we contribute, is in favour of CDI support in JAX-RS. If I'm not mistaken we have mentioned this before.

There's not that much for Jersey to change there anyway, as it supports CDI already today.

**Comment by arjantijms** [comment]
>As I argued before, we need to have a recipe that explains how to transition from one DI to another, and this is more than a simple annotation replacement:

> @Context in param position
> @Context with ContextResolvers
> ContextResolvers to configuration implementations (JAXB etc)
> Using @Inject for JAX-RS types like UriInfo, SecurityContext
> And there's likely more.
> 

I agree, so it's a case of carefully analysing each of those.

There's a few things I'm sure we can do regardless, even when we ultimately decide not to use the `@Deprecate` annotation just yet.

For instance, saying that implementations *MUST* support CDI is quite close to what the spec already asks. I have to look up the exact wording, maybe it's even already fine as it is.

Adding built-in beans for JAX-RS types like UriInfo, SecurityContext is probably quite doable and doesn't break anything else. It would just mean that one can use either `@Context` or `@Inject`. Shall I create a separate issue just for that?

**Comment by mkarg** [comment]
@arjantijms What I wanted to tell with that statements is that I would be happy to have an official vote resulting in the fact that *the majority of the committers* wants to make CDI mandatory in 3.0, but that we have to understand that still *all vendors* have to implement CDI if not done already. For Jersey, CDI is done _in part_ (not _completely_: at least not for the _standalone_ server backends but only for the _containers_ like used in Payara; and you cannot use an already existing `SeContainerInitializer` which is needed once you run _standalone_ without Payara). Anyways, a standard is only good if more than one product supports them, and until yet, nobody besides Jersey spoke up here.

**Comment by mkarg** [comment]
>There's a few things I'm sure we can do regardless, even when we ultimately decide not to use the @Deprecate annotation just yet.

I agree, but _this_ issue discusses explicitly `@Deprecate`, so all the rest of the discussion has to go in its own issue. :-)

**Comment by spericas** [comment]
@arjantijms I think rather than creating more issues, and then having these isolated discussions started again, we should create a wiki and analyze all the `@Context` use cases and propose alternatives using CDI machinery. From that discussion, we should be able to create additional requirements for the spec. Any volunteers?

**Comment by mkarg** [comment]
@arjantijms Maybe you simply like to open a PR that shows us how easy and safe all your ideas fit into JAX-RS 2.2? So we know exactly what you do propose.

**Comment by arjantijms** [comment]
>@arjantijms I think rather than creating more issues, and then having these isolated discussions started again, we should create a wiki and analyze all the @Context use cases and propose alternatives using CDI machinery. From that discussion, we should be able to create additional requirements for the spec. Any volunteers?

It's true that we don't want too many isolated discussions where the same things are repeated.  Definitely +1 for that.

On the other hand, there's the well known divide and conquer tactics, which of course everyone here knows about it.

Fully deprecating `@Context` is, as you mentioned, a potentially bigger task than it seems. Just doing a single part of it that can be done regardless of the other difficulties and has value by itself, may not hurt there.

I'll start an initial wiki page then based on your list presented here, and will update that with some of discussions we already had about it.

**Comment by mkarg** [comment]
Great, thanks! Until then, I assume we will keep my initial setting that _this_ issue has to stay with 3.0 and _cannot_ be done earlier, just as I said from the start. ;-)

**Comment by mkarg** [comment]
@arjantijms Sad but true, this one more proofs that Oracle & EF really have to find an agreement soon regarding the spec documents. We simple need them ASAP.

**Comment by asoldano** [comment]
@arjantijms @spericas +1 on creating the wiki page to deal with all @context usecases, thanks

**Comment by jansupol** [comment]
AFAIK, the Eclipse Foundation has a process that recommends a release once per 3 months (did not check). Should the 2.2 release take place in autumn and 3.0 in mid 19, I see a room for 1 - 2 additional JAXRS releases that can actually deprecate @Context (at that time the impls can have both @Context and @Inject working). I do not see an urge to do so in 2.2.

**Comment by arjantijms** [comment]
>I see a room for 1 - 2 additional JAXRS releases that can actually deprecate @context (at that time the impls can have both @context and @Inject working). I do not see an urge to do so in 2.2.

Given that we indeed go for 1 or 2 additional releases (say 2.3, 2.4), then I agree and we can do it in 2.3 if needed.

My main point is we can start working on it now, and whether it will be included in 2.2 or 2.3 is another question. I don't see much need to wait (e.g. until 3.0) just for the sake of waiting, especially if it's not clear what we'd be exactly waiting for.

**Comment by mkarg** [comment]
Yes, you can start working on it now, and depending on when it is finished and how much breaking it really is we can decide _then_ into which development stream (next major or next minor) we have to merge it. _Until then_, the only realistic option is to deprecate in 3.0. Hence, again, _this_ issue #639) has to be on hold for the time being.

**Comment by FroMage** [comment]
Last time I checked, CDI did not support injecting in method parameters, where `@Context` had to be used. Did that change?

**Comment by FroMage** [comment]
Sorry I just now realised that was discussed already here and in #569. My personal opinion is that method param injection alone is a good reason to keep `@Context` because moving to a field injection is more verbose, less local, and potentially more costly because not every method need every injected field, not to mention more messy with variable proliferation.

As an added benefit we have with `@Context`: in RESTEasy we were able to implement pluggable async injection, where producers of async types (such as `CompletionStage` but extensible to RxJava and others) can be first resolved to their actual value (asynchronously) and only then injected in the resource. CDI does not support async injection ATM, and it's pretty much trivial to implement in JAX-RS implementations with `@Context`. Dropping this means less rapid innovation too.

**Comment by FroMage** [comment]
Well, yes we can do the injection ourselves for method parameters, but I'm not sure we can do async injection for fields anymore if CDI is in charge. I'd have to check that.

**Comment by arjantijms** [comment]
@fromage what’s an async injection?

**Comment by FroMage** [comment]
What I described above, which is _very_ useful in reactive programming:

> in RESTEasy we were able to implement pluggable async injection, where producers of async types (such as CompletionStage but extensible to RxJava and others) can be first resolved to their actual value (asynchronously) and only then injected in the resource. CDI does not support async injection ATM, and it's pretty much trivial to implement in JAX-RS implementations with @Context

**Comment by spericas** [comment]
> What I described above, which is _very_ useful in reactive programming:
> 
> > in RESTEasy we were able to implement pluggable async injection, where producers of async types (such as CompletionStage but extensible to RxJava and others) can be first resolved to their actual value (asynchronously) and only then injected in the resource. CDI does not support async injection ATM, and it's pretty much trivial to implement in JAX-RS implementations with @context

What is the use case for that?

**Comment by arjantijms** [comment]
Does it mean that when there's a producer for say `Future<Bar>` you can `@Inject Bar bar`?

**Comment by mkarg** [comment]
IIUC the asynchronity simply calls the *producers* in a parallel way, so it does not really *inject* parallel? Or is the injected value actually just a "laziness wrapper" of the same type which effectively calls the *producers* at the time of first access?

**Comment by FroMage** [comment]
> Does it mean that when there's a producer for say Future<Bar> you can @Inject Bar bar?

Well, no, that's much less useful because `Future` is blocking async: you can't register a listener for it: you have to block the current thread to wait for it, which is not usable in reactive applications.

It's rather for non-blocking async types such as `CompletionStage` (by default) and RxJava's `Single` (by extension) which support non-blocking async resolving.

**Comment by ggam** [comment]
@fromage I guess this is related to this PR of you https://github.com/weld/core/pull/1828

So, it's impossible to create that feature portably right now? Have this been talked about on the CDI EG? If not, it would be good to open an issue to gather some feedback.

**Comment by FroMage** [comment]
It is related, but much simpler to implement in jax-rs. We are going to discuss it as part of CDI, though. Meanwhile it already is supported for a while by RESTEasy thanks to `@Context`.

**Comment by FroMage** [comment]
No, there is no original caller of method: that injection happens before the resource method is invoked.

**Comment by arjantijms** [comment]
>No, there is no original caller of method: that injection happens before the resource method is invoked.

But isn't resolving the actual target of the injection supposed to be done lazy for normal scoped types?

I mean, the fields are originally only set to a lightweight proxy, and only when the code inside the class actually calls a method on that proxy is the underlying object being produced, right?

So this would only be needed for dependent scoped types?

**Comment by FroMage** [comment]
Laziness does not really come into it: it's about blocking vs non-blocking. If the event-loop model that executes the request must block in order to resolve an async value that will be provided by that same event-loop later, you can't use blocking to resolve it. In reactive non-blocking models you don't want to introduce blocking anywhere in your application: you have to rely on non-blocking async such as `CompletionStage` support and in the case of injection: non-blocking async injection.

**Comment by arjantijms** [comment]
>Laziness does not really come into it

Are you sure? Since now you're resolving dependencies that aren't used I think.

**Comment by FroMage** [comment]
Hence the use of method parameters to distinguish things that are really going to get used.

It's simply impossible to do non-blocking async injection lazily, because proxies are blocking by nature. Until Loom comes along with fibers…

**Comment by arjantijms** [comment]
>Hence the use of method parameters to distinguish things that are really going to get used.

Even method parameters don't all have to be used. If you inject say 3 method parameters, it can still depend on the logic in the method which one it actually needs and uses.

**Comment by arjantijms** [comment]
Btw, instantiating an object or finding it in a scope, which is what the overwhelming majority of resolving is about, is that really worth it in practice to do eagerly, but asynchronously?

I guess your answer will be "yes" of course, but is there any benchmarking done here?

**Comment by FroMage** [comment]
> Even method parameters don't all have to be used

If you're not sure to use it, you can always resolve it yourself in the method by returning a `CompletionStage`.

> instantiating an object or finding it in a scope, which is what the overwhelming majority of resolving is about

I gave the example of obtaining a DB connection, but the same is true of looking up permissions. In non-blocking reactive settings, you should just never block. Applications are entirely meant to not block, in order to maximise CPU usage and minimise thread count/resources.

**Comment by arjantijms** [comment]
>I gave the example of obtaining a DB connection, but the same is true of looking up permissions.

I personally think it's rather rare for an injected dependency to do that in its `@PostConstruct`. Most would rather make use of a (implicit) connection pool, and then make use of the pool as part of a method on it being executed.

If you really need to eagerly create beans and their dependencies, I guess your target would be more directed at the moment the scope is created though. 

> minimise thread count/resources.

At the cost of open callbacks and events needed to be checked? But that's a bit offtopic here ;)

**Comment by arjantijms** [comment]
p.s.

Deprecating and providing CDI alternatives doesn't mean that `@Context` is gone immediately. Most people can start using the CDI versions them, and the (I assume) very small number of people that know about this asynchronously eager instantiation can keep using @Context for that.

**Comment by derekm** [comment]
Pardon me for being slightly off-topic here, but I use sub-resource locators a lot, and the way I use them it requires I initialize my subresources first with CDI and then with JAX-RS.

E.g.,
```
@Inject
SubResource subResource;
@Context
ResourceContext resourceCtx;

@Path(“{id}”)
public SubResource() {
  return resourceCtx.initResource(subResource);
}
```

Would be awesome if a JAX-RS to CDI bridge could entirely handle this without manual intervention from me, but I’m not sure how it would be possible.

**Comment by spericas** [comment]
> > IIUC the asynchronity simply calls the producers in a parallel way, so it does not really inject parallel? Or is the injected value actually just a "laziness wrapper" of the same type which effectively calls the producers at the time of first access?
> 
> No, this is not about parallel execution: it's about non-blocking async injection.
> 
> The idea is that if you're trying to inject a value of type `Foo` and all you find are non-blocking async producers for the type `CompletionStage<Foo>` (or other such types), the framework then turns the request async, and registers as a listener for the completion of the non-blocking async type, then it stops processing the request entirely and returns control to the container.
> 
> At that point, the container is then free to serve other requests, or complete any non-blocking async values is has received (event-loop way, such as Vert.x).
> 
> When the non-blocking async value is finally resolved, the injection listeners get notified and resume injection. If all non-blocking async injected values are resolved, the request is resumed, injection is resumed, and the resource method can be invoked.

 So, if I understand this correctly, this is the use case of a service_A depending on, say, values from service_B and service_C. If `CompletionStage<B>` and `CompletionStage<C>` are injected, it would be the responsibility of service_A to define its resource method using `@Asynchronous` and registering callbacks so that a response is only produced when B and C become available (likely on a different thread because of `@Asynchronous`). 

So the proposal is to instead directly inject B and C and have the _framework_ change the method to asynchronous (a bit of magic) and wait for the `CompletionStage`'s to complete before resuming execution (a bit more of magic). Honestly, this is one of those features that adds a good amount of _magic_ only saving the developer a few lines of code. 

I can see the importance of the use case, but at first glance I'm just a bit skeptical that developers really need more framework intervention to support it.

**Comment by ggam** [comment]
El vie., 12 oct. 2018 15:29, Arjan Tijms <notifications@github.com>
escribió:

> I gave the example of obtaining a DB connection, but the same is true of
> looking up permissions.
>
> I personally think it's rather rare for an injected dependency to do that
> in its @PostConstruct. Most would rather make use of a (implicit)
> connection pool, and then make use of the pool as part of a method on it
> being executed.
>
@arjantijms I imagine his usecase accounts for the injcetion of e.g. an
EntityManager that obtains the connection from a pool and possibly has to
wait for some connection to be free.

**Comment by FroMage** [comment]
> and possibly has to wait for some connection to be free.

Or the DB to answer, or using an async DB. Lots of use-cases :)

**Comment by FroMage** [comment]
> it would be the responsibility of service_A to define its resource method using @Asynchronous and registering callbacks so that a response is only produced when B and C become available (likely on a different thread because of @Asynchronous).

Except we're not relying on `@Asynchronous` because the injected value is produced as a `CompletionStage` so it's up to the producer to produce it in any non-blocking way it wants. It can really be produced by the current thread after it has registered its listeners and made the request asynchronous.

> have the framework change the method to asynchronous (a bit of magic) and wait for the CompletionStage's to complete before resuming execution (a bit more of magic)

The exact same amount of magic that does this for resource methods that return a `CompletionStage` in JAX-RS 2.1 :)

**Comment by FroMage** [comment]
But look, this isn't about async injection, sorry to have derailed the thread. I just wanted to illustrate that `@Context` has allowed us to have a great feature in RESTEasy where CDI could not provide a solution, so that was a data point in favour of not ditching `@Context` entirely.

**Comment by ggam** [comment]
The topic is still worthy to be discussed though. Would you mind moving it
to the mailing list?

**Comment by ggam** [comment]
If I'm understanding him correctly, this is not truly about JAX-RS, but
about non blocking injection in general. They have done it on their JAX-RS
cause it was the only place they could do it.

But once the resource method is invoked, provided that it is not
asyncronous, it can always call some CDI beans which use a DB connection
that the thread needa to wait for, blocking the request thread again.

So this is really about treating CompletionStage producers in CDI in a
special way in order to do non blocking injection, and not about JAX-RS
producing an async response.

Is my understanding correct, @formage? In that case, would it be enough for
CDI to implement such a non blocking injection, and JAX-RS implementations
wouldn't need any other change, no? (I'm asking to better understand the
implications)

**Comment by arjantijms** [comment]
>I imagine his usecase accounts for the injcetion of e.g. an
EntityManager that obtains the connection from a pool and possibly has to
wait for some connection to be free.

But how often does one uses an entity manager in the `@PostContruct` method?

The injection of just the entity manager doesn't do anything yet. It's a very lightweight object.

For example:

```
@RequestScoped
public class SomeService {
    @Inject
     EntityManager entityManager;

      public List<User> getAll() {
          return entityManager.createNamedQuery("User.getAll", User.class)
                            .getResultList();
    }
}
```

When you're doing `@Inject SomeService someService` somewhere else, there's no connection to be allocated yet.

It depends on whether `someService` is actually used, but if it is, a connection is only accessed when the call to `getResultList()` happens.

**Comment by arjantijms** [comment]
>So this is really about treating CompletionStage producers in CDI in a
special way in order to do non blocking injection, and not about JAX-RS
producing an async response.

The injection itself would rarely be blocking. Only if it was a dependent scoped bean, that performs logic involving an (external) other system in its `@PostConstruct` method would that happen.

**Comment by arjantijms** [comment]
>It's one of the RESTEasy reactive features that we did not think to bring to the spec at this point

So if it does not depend on the spec, you can just use the same RESTEasy internals for it that `@Context` in RESTEasy now depends upon, doesn't it?

**Comment by FroMage** [comment]
@ggam yes, except that CDI would have to change API to support it: it couldn't be doing `Object get()` to get the resource, but would need to be non-blocking async: `CompletionStage<Object> get()` to support async injection. And then the container would still have to figure out if there's async injection and if yes turn the connection async like it does for resource methods that return `CompletionStage` so there's still things to be done in JAX-RS even if CDI ends up supporting it.

**Comment by FroMage** [comment]
@arjantijms in the reactive world there are lots of things you want injected that might actually block (anything that might hit the network).

> So if it does not depend on the spec, you can just use the same RESTEasy internals for it that @Context in RESTEasy now depends upon, doesn't it?

It works right now, but only if you don't remove `@Context`, or at least if you don't remove the possibility of JAX-RS injection.

**Comment by arjantijms** [comment]
> in the reactive world there are lots of things you want injected that might actually block (anything that might hit the network).

I understand, but what I mean is that during injection it would be awkward at best if a dependency would start hitting the network. There's really only two things potentially executed when a dependent s scoped dependency is injected during injection time; the constructor and the `@PostConstruct` method. 

Accessing the network from those methods is not super common I think (of course, it's possible).

But, injecting dependent scoped objects themselves is already relatively rare. If you inject normal scoped, there's nothing executed during injection time at all, as you get a lightweight proxy.

The resources that such dependency uses are typically prepared way upfront. E.g. connection are allocated during startup of the server and put into a connection pool.

I do see why you'd want to have an instance injected that has eagerly resolved all of its potentially heavyweight (custom) dependencies, but as I mentioned, constantly eagerly instantiating has its costs too if the dependency is not always actually used.

**Comment by ggam** [comment]
Well, true, but at some point the proxied will need to instantiate its
proxied value.

You are right about the EntityManager example and indeed you don't usually
inject a db connection, but a DataSource from which you get and release a
collection only when you need it. That example wasn't so good.

But you can easily inject a config property that tries to get a value from
an external server and after failling, falls back to the db. Injection
won't block as it will only create the proxy, but at some point your code
will try to get the value from that proxy and the blocking connections will
need to be done.

If you need to inject a "User" bean in a stateless service which doesn't
have a session, such injection will probably need to hit the db or even
another microservice handling the user details.

Perhaps injection time is not the moment for it, but proxied objet
construction time. But I think there are valid usecases (more related to
CDI than JAX-RS in particular, which will only handle injection of a few
objects).

**Comment by ggam** [comment]
It's rare to hit the network during construction, but what about @Produces?
It can be done exactly for such dynamic cases. Still a lightweight proxy
will be injected, but before using it, the producer code will need to be
invoked. I personally don't consider producers with network dependencies a
bad practice.

**Comment by spericas** [comment]
> > it would be the responsibility of service_A to define its resource method using @asynchronous and registering callbacks so that a response is only produced when B and C become available (likely on a different thread because of @asynchronous).
> 
> Except we're not relying on `@Asynchronous` because the injected value is produced as a `CompletionStage` so it's up to the producer to produce it in any non-blocking way it wants. It can really be produced by the current thread after it has registered its listeners and made the request asynchronous.

 Right, understood.

> 
> > have the framework change the method to asynchronous (a bit of magic) and wait for the CompletionStage's to complete before resuming execution (a bit more of magic)
> 
> The exact same amount of magic that does this for resource methods that return a `CompletionStage` in JAX-RS 2.1 :)

 Exactly, and without looking at an example (do you have one?), if feels that the potential code simplification provided by async injection is minimal over the standard JAX-RS 2.1 API.

 As you said, this is a bit off-topic, but these are the type of discussions that help improve specifications, so definitely worth having them ;)

**Comment by arjantijms** [comment]
> but before using it, the producer code will need to be
invoked. I personally don't consider producers with network dependencies a
bad practice.

Absolutely correct, but then we do come back to the question whether the injected bean will indeed be used.

Just an example:

```
@RequestScoped
public void SomeThing {

    @Inject 
    UserService service;

    public void persistUser(SomeParam param) {
        if (param == ... && foo == ...) {
             service.persist(...);
         }
    }
}
```

In that case, you will not always actually hit the `UserService`. So in the example of FroMage, `SomeThing` would be asynchronously instantiated, and all its dependencies, which is `UserService` here cascade into being asynchronously instantiated as well, and its dependencies too, etc.

Potentially a lot of work.

If you use a dependency all the time, or most of the time it could be worth it. If not, it's a wasted effort.

**Comment by mkarg** [comment]
Instead of trying to convince *us* to keep `@Context` wouldn't it be a better idea to convince the *CDI team* to support this scenario?

**Comment by ggam** [comment]
Agreed. But if object construction is now done only when the proxy is first
used, wouldn't that work still in this non blocking way?

You get an empty proxy and once you try to use if, its CompletionStage is
used to create it asyncronously.

That's different from what @formage has explained, as it misses the
opportunity to create all objects on the same pipeline, and has the
potential outcome of going to another thread a lot of times. But as you
also said, it's not so common to inject network dependent objects so this
would only affect the few arfitacts you are wrapping on a CompletionStage.

**Comment by FroMage** [comment]
> If you use a dependency all the time, or most of the time it could be worth it. If not, it's a wasted effort.

Our usage samples reveal that method-injection (of async types) helped a lot for readability for methods where those async types where always used, especially when there were several of them.

**Comment by FroMage** [comment]
> Instead of trying to convince us to keep @Context wouldn't it be a better idea to convince the CDI team to support this scenario?

That's also an effort underway, but I had to point out that until this is resolved in CDI, `@Context` is very useful for reactive applications.

**Comment by spericas** [comment]
> > If you use a dependency all the time, or most of the time it could be worth it. If not, it's a wasted effort.
> 
> Our usage samples reveal that method-injection (of async types) helped a lot for readability for methods where those async types where always used, especially when there were several of them.

Show us the samples!! :-)

**Comment by chkal** [comment]
I just wanted to share an [interesting discussion](https://groups.google.com/forum/#!topic/microprofile/gvj94XBhtvM) about the JAX-RS <-> CDI integration from the MicroProfile mailing list. Especially, because it lists some important edge cases.

**Comment by andymc12** [comment]
Hi All,

Related (only partially) to the topic of async injection, would we need some sort of CDI thread context propagation mechanism?  I bring this up due to some discussion in the MP Concurrency about whether they should support JAX-RS specific thread context propagation, or just rely on CDI propagation - see [here](https://github.com/eclipse/microprofile-concurrency/issues/134#issuecomment-472592134) for more details of the MP discussion.

I envision a scenario like this:
```
@Context // to be replaced with @Inject
HttpHeaders headers;

@GET
public void myResourceMethod(@Suspended AsyncResponse ar) {
    ExecutorService executor = getSomeManagedExecutorService();
    executor.submit( () -> {
        String myHeader = headers.getHeaderString("AnImportantHeader"); // <-- what do we get back here?
        ar.resume( processBasedOnHeader(myHeader) );
    });
}
```

If we assume that HttpHeaders is request scoped, then this works just fine for synchronous resource methods (we get the header value for the request), but what about asynchronous methods like the above?  The call to HttpHeaders is on another thread, so CDI won't know that it is associated with the same request from the initial thread.

Today `@Context` works because the JAX-RS implementations are responsible for making it work, but I'm not sure how those implementations would make this work if CDI is responsible for managing the injection - how will CDI know which HttpHeader proxy is associated with which requests?

Thanks, Andy

**Comment by spericas** [comment]
Thanks for bringing this up @andymc12. Clearly, all this works fine in the synchronous case. For async, I see two separate cases: the `ExecutorService` is under the JAX-RS implementation control or it isn't. 

If the JAX-RS implementation does _not_ manage the executor service, then I don't see how the code above would work even if you use `@Context` (as a side note, Jersey has an annotation called `ManagedAsync` for this purpose I believe). Does it really work? 

If the JAX-RS implementation _does_ manage the executor service, then it can make sure the original "request scope" is available when the new thread runs, and a similar mechanism would be required for CDI --this is all handwavy, there may be difficult technical details that need to be resolved for this to happen.

**Comment by FroMage** [comment]
@andymc12 note that using MP-Context-Propagation (formerly MP-Concurrency) this works with RESTEasy because it defines a `ThreadContextProvider` for the state it needs for `@Context` to work. We believe this is enough.

**Comment by spericas** [comment]
Lots of interesting discussions here, but the original purpose of the issue was about deprecation of `@Context`. This was done in the spec document already.
