### ISSUE TITLE
Clarification about SseEventSource default retry delay override

### ISSUE THREAD

**Issue by NicoNes** [eclipse-ee4j/jaxrs-api#644]
Hi,

According to **javax.ws.rs.sse.SseEventSource** documentation, there are two ways to override the default retry delay:

- Using 503 response with RETRY AFTER header wich is a **one-time** overrride according to the doc:

> JAX-RS SSE event source will automatically schedule a new reconnect attempt and use the received {@value javax.ws.rs.core.HttpHeaders#RETRY_AFTER} HTTP header value as a one-time override of the reconnect delay.

- Using Retry field from received Sse event:

> JAX-RS SseEventSource tracks any received SSE event retry field values set by the endpoint and adjusts the reconnect delay accordingly, using the last received retry field value as the reconnect delay. 

My question is: 

Is the override of the default retry delay using Retry field from Sse event a one time override or not ?

In other world, as suggested by the doc:

should the last received Retry field  become the new SseEventSource default retry delay?

**Comment by NicoNes** [comment]
@andymc12 maybe you can help here ?

Thanks

**Comment by NicoNes** [comment]
Just adding the Reateasy Jira about it with comments: https://issues.jboss.org/browse/RESTEASY-1958?_sscc=t

**Comment by NicoNes** [comment]
Hey @chkal 

Maybe you could also help here to get this move forward ?

Thanks

**Comment by chkal** [comment]
@NicoNes Unfortunately I'm not very familiar with SSE. That's why I didn't respond to this issue yet.

@eclipse-ee4j/eclipse-jaxrs Anyone with more insights on this?

**Comment by jimma** [comment]
@mkarg @spericas  Any comments about this issue ?

**Comment by mkarg** [comment]
@NicoNes Sorry for the very very very long delay. The answer to your question is YES, the last received retry delay is to be used for ALL future reconnects, as clearly found in the JavaDocs: https://github.com/eclipse-ee4j/jaxrs-api/blob/565db8101a01fed275959277dba29f8107b99335/jaxrs-api/src/main/java/javax/ws/rs/sse/SseEventSource.java#L51-L53

**Comment by jimma** [comment]
@mkarg I am thinking about this case :  For example, retry fieldy set by server is intended to let EventSource wait 30 minutes to reconnect; after 30 minutes the connection is established again and EventSource starts to consume the event events, during consuming events if network connection drops, it doesn't make sense it still wait 30 minutes to reconnect.

**Comment by mkarg** [comment]
@jimma I understand your argument, but this issue was titled "Clarification about", not "Enhancement for". So if you want to *change* the text of the JavaDocs, feel free to provide a PR.
