### ISSUE TITLE
Release pipeline for first release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxrs-api#649]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by mkarg** [comment]
Is that two docs an offical PMC rule we MUST follow or is that just your persional proposal how the pipeline COULD work like?

**Comment by m0mus** [comment]
"How to release..." document was discussed and approved by PMC. "JSONP release job" is just a sample which you can use as a reference. Feel free to do it as you wish. When it's done we will publish it as a reference as well.

**Comment by mkarg** [comment]
Understood, thanks! I will look into it ASAP.

**Comment by spericas** [comment]
@mkarg Jenkins jobs appear to work if started manually at least. Will you be creating the job to stage the release?

**Comment by spericas** [comment]
Looking at the JSONP pom and pipeline, it may make sense to revisit the parent pom discussion. It would simplify the release if we can use org.eclipse.ee4j:project as parent.

**Comment by mkarg** [comment]
That's my plan.

**Comment by mkarg** [comment]
Requested GPG and OSSRH (https://bugs.eclipse.org/bugs/show_bug.cgi?id=537834). Waiting for @eclipsewebmaster to set it up.

**Comment by mkarg** [comment]
Done for `EE4J_8` in #652. Keeping this issue open for `2.2-SNAPSHOT`.

**Comment by mkarg** [comment]
Sonatype granted me the right to control the javax.ws.rs space, so I have the trigger for publication on The Central Repository now; now need for the EF admins anymore. :-)

@chkal FYI

**Comment by mkarg** [comment]
Modified title and description as the first release is coverred by #638 already (duplicate issue otherwise).

**Comment by mkarg** [comment]
Closing this issue as the pipeline is set up and tested (Jenkins signed and pushed 2.1.1-SNAPSHOT to OSSRH/snapshots repository).
