### ISSUE TITLE
module-info.java needs "uses" clause

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxrs-api#661]
While working on PR #658, I noticed that the existing module-info.java for 2.2 does not have a `uses javax.ws.rs.client.ClientBuilder;` clause which should be required in order to support `ServiceLoader` lookups of the ClientBuilder implementation in JPMS.  We may also need similar clauses for `RuntimeDelegate`, etc.  

This issue should be considered a sub-task of issue #640.

**Comment by mkarg** [comment]
Thanks for this great bug fix! :-)

**Comment by andymc12** [comment]
Yes.  Thanks for the reminder.
