### ISSUE TITLE
Change Maven coordinates

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxrs-api#663]
All current API libraries shipped must be distributed to Maven Central under a sub-package of the `jakarta` groupId. Before the first release Maven coordinates of this project must be changed as it's described [here](https://github.com/eclipse-ee4j/ee4j/wiki/New-Maven-Coordinates).

**Comment by mkarg** [comment]
1. Your issue description talks in particular about groupId, but the reference page also talks about artifactId. Is my assumption correct that the needed change *includes* also the artifactId?
2. Does this imply that JAX-RS MUST do this change for EE4J_8, and it is *not* early enough to do it EE4J_9?
3. Is this a final and official PMC decision?

**Comment by m0mus** [comment]
1. Both groupId and artifactId have to  be changed.
2. Must do it for EE4J_8. I share your concerns about 'too early', but it was the spec committee decision.
3. Oct 22
4. It was the spec committee decision. Yesterday of the steering committee meeting I'd got a clarification that it must be done.

**Comment by mkarg** [comment]
Ok, thanks. I will skip the diskussion whether the steering committee has the power to give the PMC commands and provide a PR asap. ;-)

**Comment by spericas** [comment]
> On Sep 19, 2018, at 9:51 AM, Dmitry Kornilov <notifications@github.com> wrote:
> 
> Both groupId and artifactId have to be changed.
> Must do it for EE4J_8. I share your concerns about 'too early', but it was the spec committee decision.
> Oct 22
> It was the spec committee decision. Yesterday of the steering committee meeting I'd got a clarification that it must be done.

 I respect the decision, but wish this would have been enforced post EE4J_8.

— Santiago

**Comment by m0mus** [comment]
@spericas I agree and exposed my concerns to PMC. It's not been heard.

**Comment by m0mus** [comment]
Any reason why groupId was changed only in `EE4J_8` branch and not in `master`?

**Comment by mkarg** [comment]
The reason is that *once the release is performed* (i. e. `EE4J_8` will become *static*) I am merging all changes from `EE4J_8` back into `master` in *one single* merge action.

**Comment by m0mus** [comment]
Sounds good, so I am closing this task.

**Comment by mkarg** [comment]
Actually **I** am the assignee of this task, and I left it open *by intention* to remember merging it into master. I really do appreciate your dedication and understand your time pressure, but see, acting hastily within a project without respect for the partcular governance structure of a project implies a bit of chaos for us others. I cannot check the open issues anymore now, so your positive intention actually implies more work for me now.
