### ISSUE TITLE
Implementation Page - Links to project pages instead of source code repos

### ISSUE THREAD

**Issue by rmcdouga** [eclipse-ee4j/jaxrs-api#667]
Wouldn't it be more useful to link directly the various project websites rather than to the underlying github repositories?  

For example, the page currently links to the Jersey github project page instead of the Jersey website ([https://jersey.github.io/](https://jersey.github.io/)).  Oddly, the project page does not link to the web site either, instead choosing to link to the Eclipse page.  This makes it a little harder to locate the website than it should be.

Likewise the RESTEasy link points to the github repository rather than the RESTEasy project page ([https://resteasy.github.io/](https://resteasy.github.io/)) and the CXF points to the github repository rather than the project page ([https://cxf.apache.org/](https://cxf.apache.org/))

If someone is looking for a JAX-RS implementation, then the project websites are probably more immediately useful (they have user guides, examples and javadocs) than the project source code itself.  

Most people looking for implementations are probably not going to be jumping straight into the source code.

**Comment by mkarg** [comment]
Thank you for this enhancement proposal. I have modified [the wiki page](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Implementations) so now you will find separate links for project web site and project source code.

**Comment by rmcdouga** [comment]
You're welcome.  Thanks for making the change!
