### ISSUE TITLE
Travis Build badge seems broken

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jaxrs-api#669]
While the last build looks OK on Travis, the build badge still keeps saying "error", both in the README file and in Travis itself. What causes that and how can it be resolved?

**Comment by mkarg** [comment]
I doubt there is anything we can do about that. The badge ist neither created nor stored by is, it is simply a link to Travis.

**Comment by mkarg** [comment]
I checked that with Travis. The Travis CI page of JAX-RS (https://travis-ci.org/eclipse-ee4j/jaxrs-api) shows also a build failed batch. So your issue is invalid. I think what you noticed simply is a refresh / timing problem of Travis CI itself.

**Comment by keilw** [comment]
Sometimes even different branches can cause weird behavior. Some badges are very buggy and broken, e.g. the javadoc.io one can't handle a "EDR" prefix ;-( I hope you consider also pointing to Jenkins in addition to that?

**Comment by mkarg** [comment]
Feel free to send a PR.
