### ISSUE TITLE
RFC4918

### ISSUE THREAD

**Issue by leewalton** [eclipse-ee4j/jaxrs-api#679]
RFC4918 lists a number of http response codes which are not defined in the jaxrs-api, making it difficult to cleanly respond with these codes to clients that are expecting them.

An example is the TM Forum Open APIs, which make extensive use of a 422 response code in their swagger definitions.

Are there any plans to make the jaxrs-api compliant with RFC4918?

**Comment by derekm** [comment]
I’ve been saying for a while that JAX-RS needs an explicit registry of the RFCs it intends to comply with as a piece of primary documentation.

**Comment by leewalton** [comment]
I've responded to this further on the pull request with my thoughts on this, so I'll just link the comment [here](https://github.com/eclipse-ee4j/jaxrs-api/pull/680#issuecomment-430202333) rather than repeating them.

**Comment by leewalton** [comment]
I've closed the associated pull request, and I'm going to close this issue, as I am going to resolve this through extension of the JAX-RS API, rather than changing the api itself, as per @mkarg's recommendations in the pull request.
