### ISSUE TITLE
Clarify if propertiesProvider takes precedence over property setting in JAXRS.Configuration.Builder

### ISSUE THREAD

**Issue by jimma** [eclipse-ee4j/jaxrs-api#683]
If a property value like port  is already set  with JAXRS.Configuration.Builder#property("port",value) or  JAXRS.Configuration.Builder.port (value) apis, then it loads property values from properyProvider with JAXRS.Configuration.Builder# from(propertiesProvider), does this value take precedence ?  Or the value later loaded/set overwrites previous setting ?

**Comment by mkarg** [comment]
Like rather most builder patterns I know, my intention when designing this API was that an ongoing overwriting will happen when chaining mutators of the the same property. This means "the last one wins". The builder simply accumulates the result of all calls in historic order.

**Comment by jimma** [comment]
If I understand correctly, the propertyProvider function which passed to builder is actually called when read this value  with Configuration#property(name), this is something like : 
```  
       public Object property(String name)
         {
            // set with property is the last one wins
            Object result = properties.get(name);
            if (result == null && propertiesProvider != null)
            {
               result = propertiesProvider.apply(name, Object.class);
               return ((Optional)result).get();
            }
            return result;
         }
```
If we support the last one wins, it has to define some flag to track the historic order, then it knows if the same property value should read from propertyProvider or not.  Is it better we simplify this and define a order in spec ?

**Comment by jimma** [comment]
Thanks for clarifying my doubt . BTW, can you please point me the jersey source code ? I didn't find it from jaxrs2.2 branch : https://github.com/eclipse-ee4j/jersey/tree/JAXRS_2_2

**Comment by mkarg** [comment]
https://github.com/eclipse-ee4j/jersey/pull/3839/files :-)
