### ISSUE TITLE
Activate 'final' profile for EE4J_8 releases

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/jaxrs-api#694]
As already mentioned in #686, we need to activate the `final` profile when performing releases from the `EE4J_8` branch:

https://github.com/eclipse-ee4j/jaxrs-api/blob/20223096b812df674c54cc44d50a7759c56309c5/jaxrs-api/pom.xml#L78-L90

@mkarg Could you perhaps update the Jenkins release job accordingly? I guess you are most familiar with how the release pipeline works. :-)

**Comment by mkarg** [comment]
Okay, so this means when we do a release of JAX-RS we have to decide whether it is a pre-release or not, and we have to modify the Jenkins setup. I really think getting rod of the plugin will be the simplest solution, as we can keept one single Jenkins setup but just modify the pom itself to keep the final values intended in the manifests.
