### ISSUE TITLE
Less is more

### ISSUE THREAD

**Issue by dagnelies** [eclipse-ee4j/jaxrs-api#710]
Hi,

today, I took a look at https://jooby.org/ . I just wanted to try out and since it used `@GET`, `@Path` and the other usual stuff, I thought it would be nice. However, I noticed it states "not JAX-RS compliant" and uses its own set of annotations which is a subset of JAX-RS ...and thought "*why*"?! ...so out of curiosity I digged a little deeper and I found out that the developers didn't want to use the JAX-RS api because users would then complain about this or that missing feature. ...so I thought: isn't JAX-RS just a few simple annotations?!

...then I went here. And OMG, I understand them. I wouldn't want to implement a JAX-RS compliant thing either 😨  ...I wonder if anyone is. It looks uselessly complex, big, and way beyond just simple REST annotations. IMHO, if you continue that way, you're on the best way to become one more legacy EE technology nobody wants to use. My 2 cents as a humble developer.

Seriously folks. I'm sorry if I come off rude and I'm certainly a bit out of line, my apologies, but sometimes less is more as the saying goes.

...I'll now go back to my non JAX-RS compliant project.

**Comment by mkarg** [comment]
Thank you for sharing your opinion. This is an open source project which lives from active participation. So feel free to provide a PR with your intended changes so we can discuss on a more constructive basis.

**Comment by dagnelies** [comment]
I was indeed rather unconstructive. Neither do I have a sensible PR to make. The thing with APIs is that they cannot be trimmed down without breaking backwards compatibility, which would be equally harmful. If you are open to suggestions, the only one I could offer would be to split it in a "basics" and an "extended" version. That way, the barrier of adoption would be lower, while Jersey & Co could still fully benefit of the extended version.... if that makes sense.
