### ISSUE TITLE
Release 2.1.4

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#714]
This is to inform all committers about plans to publish release 2.1.4 on shot notice.

Teams Jersey and Tycho requested changes that might be obstacles towards GlassFish 5.1.

**If nobody rejects this proposal, I will publish JAX-RS 2.1.4 including these changes (https://github.com/eclipse-ee4j/jaxrs-api/milestone/10) on Saturday Dec 15.**

-Markus

**Comment by mkarg** [comment]
Release 2.1.4 is staged on [OSSRH](https://oss.sonatype.org/content/groups/staging/jakarta/ws/rs/jakarta.ws.rs-api/2.1.4/). Please everybody check ASAP for any other known showstoppers, in particular Team GlassFish.

**Comment by chkal** [comment]
I just checked the release and it looks fine. My only concern is actually what I already posted in the comment here: https://github.com/eclipse-ee4j/jaxrs-api/pull/713#issuecomment-447577111

**Comment by mkarg** [comment]
As nobody reporting any showstoppers withing 24 hours, I have published to Maven Central. Release 2.1.4 is hereby done. :-)
