### ISSUE TITLE
Need add method to Add the given, single header value under the given name.

### ISSUE THREAD

**Issue by darklord549** [eclipse-ee4j/jaxrs-api#718]
Not able to add single header value, it is required for unit testing using mockito. 

I researched, that it is available in "org.springframework.http.HttpHeaders" but my project is using "javax.ws.rs.core.HttpHeaders". so need this for implementation of mockito test scripts.

Also if i am using org.springframework.http.HttpHeaders, i am not able to cast (HttpHeaders) httpHeader.

Please help.

**Comment by darklord549** [comment]
@chkal Could you please have look on this

**Comment by chkal** [comment]
The `javax.ws.rs.core.HttpHeaders` interface exposes a read-only view of the request headers for the current JAX-RS request. So it doesn't make any sense to have setters in this interface. You could either implement the interface with a mock class which provides such setters or use Mockito to create a "virtual mock" which provides custom behavior.
