### ISSUE TITLE
Moving Eclipse Jenkins from old infra to new one

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/jaxrs-api#721]
EF is moving old Jenkins instances from old infra to a new infra. The Jenkins is available at https://jenkins.eclipse.org/jaxrs/, the build job has been transferred.

EF is asking whether [it is possible to drop](https://bugs.eclipse.org/bugs/show_bug.cgi?id=541740) the old infra.

@mkarg Can you please check the transferred release job? 

@everyone Can the old infra be disposed in favor of the new one?

**Comment by mkarg** [comment]
Existing infra still working well. New infra failing due to missing JDKs labels. Will fix this after 2.1.5, which I do with the old infra.

**Comment by mkarg** [comment]
@jansupol I am a bit confused. The referenced ticket does not say the EF wants to migrate us, but instead *you explicitly asked* for the migration and in particular, to shutdown the existing and quite fine working Jenkins instance. As I am using that old infra for releasing and was pretty happy with it, I wonder if you like to elaborate a bit why you requested the shutdown of that service without prior discussing us / me *first*?

**Comment by arjantijms** [comment]
@jansupol 
>@everyone Can the old infra be disposed in favor of the new one?

Yes, when everything is transferred please go ahead. It's very confusing to only have JAX-RS on this old infra.

**Comment by mkarg** [comment]
I'm still working on this. Apparently we need to change the supported set of JDKs. Please find PR #724  so I can continue.

**Comment by jansupol** [comment]
I fail to see how removing Oracle JDK from Travis helps with building on Jenkins.

**Comment by mkarg** [comment]
@jansupol Jenkins is improved by replacing Oracle JDK 8 by OpenJDK Latest in the Jenkinsfile. The Travis changes are for Travis probles, not for Jenkins problems. So for #721 we only need one of those fixes, the other fix is needed for Travis problems.

**Comment by jansupol** [comment]
The PR is a bit problematic, There are 3 parts of it, in a single PR:
1) Replacing Oracle JDK by OpenJDK in Jenkins. That's fine. Oracle JDK is available in bash only, it's fine to build the JAX-RS API with OpenJDK.
2) Removing the EA from the build. It's fine, it's causing issues, we can remove it.
3) Removing Oracle JDK 8+. I do not see any rationale behind this. I do not see how this fixes any Travis problem.
I would suggest splitting the commit per the issue it addresses.

**Comment by mkarg** [comment]
**This issue is dependent of #724.**

**Comment by mkarg** [comment]
Nightly builds working incorrectly, still working together with EF admins to solve this. Stay tuned. :-)

**Comment by mkarg** [comment]
The new infrastructure is working well since yestedays tweaks by the Eclipse Foundation admins. Hence I am closing this issue.

WARNING: The job for nightly builds will currently fail on JDK 11 due to this bug https://bugs.openjdk.java.net/browse/JDK-8212233. Don't assume this has to do with the new infra, this is completely independent and just popped up in this environment by incident. I'm working on this with Team JDK and Team Maven, stay tuned in case you use the nightly build job.
