### ISSUE TITLE
Clarification: MessageBodyWriter#writeTo SHOULD NOT / MUST NOT close the stream

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#730]
The JAX-RS 2.1 JavaDocs for `MessageBodyWriter#writeTo` say: _"The implementation should not close the output stream."_.

This is confusing because SHOULD NOT implies that it is allowed for an MBW to actually close the stream. On the other hand, downstream filters do not expect closed streams; in particular their JavaDocs tell _"Get the entity output stream. The JAX-RS runtime is responsible for closing the output stream."_ - which implies that the stream can be expected to be open always and closed automatically _after_ the filter is done with processing.

So for absolute unambiguity we should either change the MBW's JavaDocs from SHOULD NOT to MUST NOT, unless someone outlines a case where it is necessary to for an MBW to close the stream _before_ a filter touches it. In _that_ case, we should clearly tell in the Filter's JavaDocs that the stream MAY be closed to indicate that no filtering is wanted.

**Comment by chkal** [comment]
Good catch. I agree that updating the docs of `MessageBodyWriter#writeTo()` to MUST NOT is a good solution.

**Comment by mkarg** [comment]
Shall we backport this clarification into 2.1.6?

**Comment by chkal** [comment]
I'm not completely sure about that. We actually changed `should` to `must`, which may be more than a simple clarification!?!

**Comment by mkarg** [comment]
I share this opinion.

**Comment by mkarg** [comment]
Closed with #731
