### ISSUE TITLE
Request.evaluatePreconditions(): anything other than "If-None-Match: *" must return 412

### ISSUE THREAD

**Issue by anthonyvdotbe** [eclipse-ee4j/jaxrs-api#747]
The Javadoc for `Request.evaluatePreconditions()` says:

> Note that [...] `If-None-Match: something` will always be considered to have been met

However, [RFC 7232](https://tools.ietf.org/html/rfc7232#section-3.2) says:

> [...] either not having any current representation of the target resource, when the field-value is "*", **or having a selected representation with an entity-tag** that does not match any of those listed in the field-value.

So `Request.evaluatePreconditions()` must return 412 for anything other than "If-None-Match: *"

**Comment by spericas** [comment]
I suspect the original semantics for these methods pre-date RFC 7232, which is from 2014. Perhaps the issue here is updating the JAX-RS spec referring to that RFC? WDYT?

**Comment by anthonyvdotbe** [comment]
Yes, exactly. I created a pull request to update the spec.

**Comment by mkarg** [comment]
Anybody having a list of more RFC 7232 changes, so we could put all of the fixes into the same next version?

**Comment by anthonyvdotbe** [comment]
Each of the new RFCs (7230-7235) has an appendix "Changes from RFC 2616" that can be used as a guidance for required updates to JAX-RS. I agree it would be nice for all updates to go into the same next version.

**Comment by mkarg** [comment]
@anthonyvdotbe Would you be interested to provide more PRs wrt the mentioned RFCs?

**Comment by anthonyvdotbe** [comment]
@mkarg yes, as this seems a good starting point to get more involved, but at the moment I don't want to make any commitments I won't be able to keep
