### ISSUE TITLE
Is generated Javadoc available online?

### ISSUE THREAD

**Issue by FranklinYu** [eclipse-ee4j/jaxrs-api#750]
I can find old versions at https://jax-rs.github.io/apidocs/2.1/ so is new one being built anywhere? If any, it should be mentioned in README.

**Comment by mkarg** [comment]
In fact there is no published JavaDocs currently, but you can simply `git clone... && mvn javadoc:javadoc` them within seconds. :-)

@ivargrimstad Is the PMC having any plans for setting up machine-writeable web sites for all EE4J subprojects? And does the PMC have a Github handle to include them in issue discussions like this one easily?

**Comment by ivargrimstad** [comment]
Hi,

The Jakarta EE Marketing committee is in the process of setting up an
infrastructure for all EE4J projects to have a dedicated page on
https://jakarta.ee, similar to https://microprofile.io/projects/. The PMC
will notify the projects when this is set up and assist in getting the
information out.

Ivar

**Comment by FranklinYu** [comment]
@ivargrimstad I checked https://microprofile.io/projects/ but is it only a single-page README for each project? That would not suffice since JavaDocs is a lot more. It would be cool if every EE4J (Jakarta EE) project gets a URL prefix like https://jakarta.ee/projects/jaxrs-api/.

**Comment by jansupol** [comment]
There is https://jax-rs.github.io/apidocs/2.1/ for current API

**Comment by mkarg** [comment]
@ivargrimstad Any news on this topic?

**Comment by arjantijms** [comment]
Full java docs are available here: https://jakarta.ee/specifications/restful-ws/3.0/apidocs

@FranklinYu This pattern of java docs availability is for all Jakarta EE projects.
