### ISSUE TITLE
Change project name to Jakarta RESTful Web Services

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jaxrs-api#753]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [ ] GitHub
- [ ]  README file
- [ ]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by mkarg** [comment]
-1 as Wayne's personal opinion is not authoritative. Please instead provide a link to the authoritative decision of the EF that this *must* be done.

**Comment by mkarg** [comment]
BTW, is it really needed that someone (don't know who actually) decides about the projects name and the committers of the project are not even considered to get asked for proposals?

**Comment by mkarg** [comment]
Actually @ivargrimstad 's rather brief summary is not the sole truth. As @waynebeaton [commented](https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/#comment-26798) to the above blog entry, in fact the actual name of the project is to be chosen *by us*; the list on his blog was just *his personal proposal*.

@eclipse-ee4j/eclipse-jaxrs Hence all JAX-RS committers are asked hereby to join this discussion to propose the future name of this project. Till now there is no publicly visible reason whether we actually MUST change the project name, nor a deadline until when this MUST be done. So it seems this issue is more like a general discussion than a real to-do.

**Comment by ivargrimstad** [comment]
Hi,

The naming standard has been formed after discussions among all the members
of the Jakarta EE Working Group Steering Committee and Specification
Committee. You are free to come up with your own suggestions, but
ultimately the names must be approved by (I would guess) the Specification
Committee (maybe also the Steering Committee).

Ivar

**Comment by mkarg** [comment]
@ivargrimstad There is a naming *standard*? Can you please link to the published document?

**Comment by mkarg** [comment]
Proposal #1: We keep "JAX-RS" and "Java API for RESTful Web Services" as long as nobody of Oracle officially forbids that.

Proposal #2: Once Oracle officially forbids that, we keep "JAX-RS" with its long form "Jakarta API for RESTful Web Services".

**Comment by ivargrimstad** [comment]
@mkarg I don't think the naming sheet has been published. The naming standard, or pattern, is what Wayne outlined in his blog post.

**Comment by mkarg** [comment]
@ivargrimstad Can we agree upon that Wayne's blog is non-normative, as he explicitly told me that it is solely his personal opinion and not an official EF channel? Can the committees please immediately publish all official decisions somewhere?

**Comment by ivargrimstad** [comment]
The minutes are published here https://jakarta.ee/meeting_minutes/ as soon as they are approved. I will take it up on the next meeting that this information need to be shared as quickly as possible.

**Comment by mkarg** [comment]
@ivargrimstad Great, thanks! :-) In fact it would be goold if all committees would have official announcement channels that post official decision rather immediately after deciding them.

**Comment by ivargrimstad** [comment]
Ooops, sorry clicked the close button by accident :)

**Comment by mkarg** [comment]
:-D

**Comment by chkal** [comment]
My following thoughts are based on the assumption that we aren't allowed to use the Java trademark in the name for the specification anymore. And according to my understanding, that's the current situation and therefore suggestion (1) by @mkarg would not be possible.

In this case I'm voting for:

> Jakarta API for RESTful Web Services

I don't think that dropping the **API for** is a good idea. Keeping it emphasizes that it is an API/specification and not an implementation!

**Comment by ivargrimstad** [comment]
I kind of like keeping it simple. How about simply **Jakarta REST**?

@chkal This would be analog to MVC. When we move that spec over, it would make sense to call it Jakarta MVC and not Jakarta API for MVC, which doesn't really add any value...

**Comment by chkal** [comment]
IMO having API in the name actually adds value, because it makes the specification nature clearer. Or do you think that having Jakarta in the name is sufficient for people to know it is about an API and not an implementation?

I'm not sure if the name must me very short, because people will call it JAX-RS anyway :-)

What about the pattern:

> Jakarta {something} API

That's shorter than the "Jakarta API for ..." scheme. It would create names like:

  * Jakarta Persistence API
  * Jakarta Servlet API (see Greg's proposal on the ee4j-pmc list)
  * Jakarta RESTful Web Services API
  * ...

Just my 2 cents :-)

**Comment by spericas** [comment]
Hi All,

 I agree with Christian about keeping API in the name. So I like the prefix “Jakarta API for …” 

— Santiago

**Comment by arjantijms** [comment]
I don’t like only JAX-RS having “api for” in its name. I believe in some level of consistency. Either all spec projects should have this, or none should.

**Comment by arjantijms** [comment]
@chkal 
>IMO having API in the name actually adds value,

Just wondering, but MVC doesn't have API in its name, does it?

**Comment by chkal** [comment]
I would prefer

> Jakarta {Something} API

over

> Jakarta API for {Something}

But I guess that's mostly a matter of taste.

**Comment by arjantijms** [comment]
@chkal I hear you, but I just wonder if not "Jakarta" signals that it's an API project, since all Jakarta projects are API projects if I'm not mistaken. Implementations use names like GlassFish, TomEE, and what have you.

**Comment by mkarg** [comment]
@arjantijms No, the name "Jakarta" is not enough, as least people in the user community actually know that it *only* contains APIs. Even the Jakarta EE web site points to implementing products: Just press the "products" button and you will see the list of *all* EE4J products, like Jersey! And not even the FAQ restricts the name to "API only"! ;-(

**Comment by arjantijms** [comment]
@mkarg Sorry, which "products" button is that?

All EE4J projects is something else I think. EE4J is not Jakarta EE.

My take on it is that all API projects are renamed to "Jakarta *" projects, obviously Jersey is not a Jakarta project itself, but an implementation of Jakarta REST.

**Comment by mkarg** [comment]
@arjantijms Go to [the official Jakarta EE web site](https://jakarta.ee/) then click the yellow button [Projects] in the middle of that page. You will be navigated to [the EE4J web site](https://projects.eclipse.org/projects/ee4j), so people will definitively think it is the same. As Jersey is found on that page, people definitively will think that Jersey is a Jakarta project.

**Comment by arjantijms** [comment]
>then click the yellow button [Projects

Aha okay, projects, I was looking for products.

That should be easy enough to fix though. If all projects in the ee4j repo that are APIs start with "jakarta" it should be a beginning. FAQs and other info pages can clarify this further.

E.g.

- https://github.com/eclipse-ee4j/jakarta-rest
- https://github.com/eclipse-ee4j/jakarta-security
- https://github.com/eclipse-ee4j/jakarta-faces
- https://github.com/eclipse-ee4j/jakarta-connectors
- https://github.com/eclipse-ee4j/jersey
- https://github.com/eclipse-ee4j/soteria
- https://github.com/eclipse-ee4j/mojarra
- ...

**Comment by bshannon** [comment]
I'm not so worried about distinguishing API from implementation in the "short names"
of these projects, but I would expect the full names to be like:

- Jakarta REST
- Eclipse Jersey

which pretty clearly distinguishes which is API/spec and which is implementation.

**Comment by mkarg** [comment]
@bshannon Maybe for an Eclipse Member, but I doubt the average Joe could separate it.

**Comment by bshannon** [comment]
I'm not sure the average Joe *cares* about the difference between API and implementation.  :-)

When the average Joe needs to decide between downloading Apache this, JBoss that,
or Eclipse whatever, I think the difference will be clear enough.  Downloading Jakarta
REST alone won't be good for much.

**Comment by mkarg** [comment]
As a JUG leader I can tell you: Be sure, the average Joe does! There are many out there who only care for a single API. Besides the big hypes people still build applications around just JPA or just JAX-RS, but still want to be independent of a particular products like Jersey.

**Comment by chkal** [comment]
Maybe we should continue this discussion on the jakarta.ee-community list? IMO consistency between all specs is actually the most important aspect regarding the naming.

**Comment by mkarg** [comment]
@chkal Actually I do not see what actual, measurable benefit naming consistency would bring, or what actual, measurable drawback missing consistency of names would bring. Also Wayne said it is up to the projects to decide. So no, bold -1 for moving the discussion of *our* name to a different community.

**Comment by spericas** [comment]
> On Apr 11, 2019, at 3:33 AM, Christian Kaltepoth <notifications@github.com> wrote:
> 
> Maybe we should continue this discussion on the jakarta.ee-community list? IMO consistency between all specs is actually the most important aspect regarding the naming.
> 
> 

 +1

— Santiago

**Comment by spericas** [comment]
After reading @bshannon's comment, I agree we can drop "API". In fact, the proposed "Jakarta RESTful Web Services" seems perfectly fine to me.

**Comment by m-reza-rahman** [comment]
+1. It's a good name.

**Comment by chkal** [comment]
I'm +0 for "Jakarta RESTful Web Services". I definitely see value in keeping "API" in the name for the reasons mentioned above, but I would also be fine with this name if everyone likes it.

**Comment by mkarg** [comment]
I'm -1 for dropping the word "API", due to the reason already mentioned.

**Comment by spericas** [comment]
So if I understand the discussion and voting so far, the candidates are:

 [1] Jakarta RESTful Web Services
 [2] Jakarta API for RESTful Web Services

I'm honestly fine with either one. OTOH, if JAX-RS ends up being the only project using "API", that would be odd IMO.

**Comment by mkarg** [comment]
I don't have a problem with unaligned names, as we lived with that for many years at the JCP and nobody cared. In the end, Java EE always just was an umbrella around otherwise standalone and often pre-existing APIs; it seems we sometimes forget that _or_ the EF wants to turn that view upside down (JAX-RS only being a _chapter_ Jakarte EE).

Anyways, I think we possibly discuss the wrong thing at all: The request is to change the _project_ name, not the API, apparently. I am +1 for the proposed _project_ name (without the word "API"), I just want to keep the word _API_ in the _API_'s name (in the sense of "The project Eclipse Jakarta RESTful Web Services provides the specification of the Jakarta API for RESTful Web Services").

**Comment by spericas** [comment]
@mkarg Ok, then there are no objections (so far) for "Jakarta RESTful Web Services".

**Comment by andymc12** [comment]
+1 for [1] Jakarta RESTful Web Services - I prefer to be consistent with the other projects.  But I don't really have a strong preference either way.

**Comment by arjantijms** [comment]
Although I'm fine with "Jakarta RESTful Web Services", I think the previously proposed "Jakarta REST" might be even better.

After all, isn't "Web Services" redundant? Do we also have "RESTfull [something else]"?

On the other hand, I do appreciate we have "SOAP Web Services" as well, although we don't have quite that name.

So for me:

* Jakarta RESTful Web Services +1
* Jakarta REST **+10**

**Comment by sdaschner** [comment]
My 2ct's:
- My preference is to keep "API" in the names, since that indicates what it is.
- I definitely would like to have all project names sharing a common patterns.
- I'd prefer "Jakarta API for RESTful Web Services".

**Comment by mkarg** [comment]
@eclipse-ee4j/eclipse-jaxrs As the trademark negotiations [failed](https://eclipse-foundation.blog/2019/05/03/jakarta-ee-java-trademarks), I'd like to kindly ask all JAX-RS committers to cast the final vote in this issue ASAP, so we can proceed with the needed renaming. This discussion is open for 29 days already, but it is still active, so I'd like to propose that we do the final count in one week (Saturday Morning).

**Comment by jansupol** [comment]
+1 for Jakarta RESTful Web Services

**Comment by mkarg** [comment]
@spericas I have checked all the votes again and agree that there is a slight preference for "Jakarta RESTful Web Services". So I'd say I will close this issue hereby with that result. If somebody thinks that we identified the false winner, then please feel free to comment.

**Comment by chkal** [comment]
What's the final decision regarding the acronyms? Is it explicitly forbidden to use the acronym JAX-RS?

**Comment by mkarg** [comment]
@chkal That would be really sad, and frankly I doubt that *the user community* actually would care about such a constraint and simply continue to use the acronym, even if *we* would abstaint. JAX-RS is not a registered trademark nor mentioned in [the trademarks file](https://github.com/eclipse-ee4j/jaxrs-api/blob/master/NOTICE.md#trademarks) [Oracle](https://github.com/eclipse-ee4j/jaxrs-api/commits/master/NOTICE.md) provided. So I doubt that there is really a legal way to prevent us using the acronym of "Jakarta Api for Xxml Restful web Service". But to be true, I expect some people will chime in soon saying that it *is* forbidden, just out of fear.

**Comment by chkal** [comment]
@mkarg I absolutely agree on everything you wrote. I'm just curious what the official response regarding this is from the EF/PMC/etc.

**Comment by ivargrimstad** [comment]
@mkarg and @chkal Whatever you decide to call it in your daily speech or communicating between peers is totally up to you and nobody could care less. Call it BOB if you like.

Personally, I will probably use JAX-RS when talking about the Java EE 8 API and Jakarta REST or similar when talking about the Jakarta API, just to avoid confusion.

Whether there will be any guidelines, recommendations, restrictions or whatever imposed on the released artifacts is up to the Jakarta EE Specification Committee. A reasonable requirement would, in my opinion, be to always write the complete name out (i.e. Jakarta RESTful Web Services). Which is pretty common and not that controversial.

**Comment by spericas** [comment]
Thanks for the clarification @ivargrimstad

**Comment by bshannon** [comment]
> What's the final decision regarding the acronyms? Is it explicitly forbidden to use the acronym JAX-RS?

Yes.

**Comment by chkal** [comment]
> > What's the final decision regarding the acronyms? Is it explicitly forbidden to use the acronym JAX-RS?
> 
> Yes.

Could you provide a reference? If I understood @ivargrimstad correctly, there isn't any guideline or restriction yet. I'm confused.

**Comment by bshannon** [comment]
Sadly, no.  The details are wrapped up in the negotiations between Oracle and Eclipse that ultimately failed.

**Comment by mkarg** [comment]
@bshannon I think we could simply say, Oracle claims "JAX-RS" as one of its unregistered trademarks, so it is not possible to use it without written permission, right?

**Comment by spericas** [comment]
@eclipse-ee4j/eclipse-jaxrs Suggestions for an acronym to use instead of JAX-RS?

**Comment by ggam** [comment]
What about promoting "Jakarta Rest" instead of a new acronym? It's short
enough to officially use it, and people will probably refer to it as JAX-RS
for some time anyway.

**Comment by bshannon** [comment]
> What about promoting "Jakarta Rest" instead of a new acronym?

I agree.  (Or "Jakarta REST".)  That's the way we've been heading with most of the other
projects/specs, which avoids the acronym issue.

**Comment by spericas** [comment]
+1 on "Jakarta REST" to replace "JAX-RS"

**Comment by chkal** [comment]
As this issue is mostly about the full project name and we identified "Jakarta RESTful Web Services" as the winner, I'm moving this to "Ready for approval" in the [corresponding board](https://github.com/orgs/eclipse-ee4j/projects/11).

**Comment by mkarg** [comment]
@ivargrimstad What shall we change for the "Github" item in your checklist?
> Checklist:
>* [ ]  **GitHub**

**Comment by chkal** [comment]
@mkarg Maybe the repository description (which is "Jaxrs" ATM) and the wiki content?

**Comment by mkarg** [comment]
@chkal Repo description and wiki don't contain neither project name nor scope. There is no decision about what to do with acronyms, as the official answer from the PMC still is open (announced for June).

**Comment by chkal** [comment]
@mkarg In this case IMO there is nothing to do on the GitHub side for now. So this task can be considered to be completed.

**Comment by kwsutter** [comment]
I just read through all of the comments on this issue and, tbh, I can't figure out what the consensus is from this group concerning the name of the project.  My personal favorite is Jakarta REST.  I really think you want to be as concise and "catchy" as you can since the use of acronyms is still in the air...

**Comment by mkarg** [comment]
@kwsutter This discussion ended with a democratic vote leading to the renaming already done, see https://github.com/eclipse-ee4j/jaxrs-api/pull/763. Since then, the project is named "Jakarta RESTful Web Services".
