### ISSUE TITLE
Reducing number of labels

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#756]
Github says we are using 132 labels. I want to kindly ask to allow me to clean this up. Proposal: Remove all "grey" labels, keep just "colored" labels. +1 from all?

**Comment by chkal** [comment]
AFAIK all the gray labels were created as part of the migration from java.net and represent priority, component, labels and other information from JIRA.

I'm fine with cleaning this up. 132 labels is too much. And there are many redundant labels. I think the important question is whether we want to keep some labels like the "Component: *" ones.

**Comment by mkarg** [comment]
@eclipse-ee4j/eclipse-jaxrs Any more opinions?

**Comment by arjantijms** [comment]
I agree there are far too many labels (and perhaps a few too many open issues, but that's another discussion). Many of the grey ones look like they could be removed, especially things like "adoptajsr" etc.

**Comment by mkarg** [comment]
@eclipse-ee4j/eclipse-jaxrs Committers, actively please list the names of those grey labels in this issues comments that you personally want to keep. So I know which ones (besides the colored ones) are still needed. According to our committer conventions, I will keep this issue open for collecting proposals for two full weeks (i. e. **only four more days from now**). After that, **I will remove all non-mentioned grey labels**. Christian, yours is already counted. Thanks. :-)

**Comment by spericas** [comment]
@mkarg I'm OK with removing all grey labels.

**Comment by arjantijms** [comment]
I just went through them again, and I think all grey ones can be removed indeed.

**Comment by mkarg** [comment]
As announced, I have removed all labels but kept the following:
* Coloured labels
* Component: labels

**Comment by chkal** [comment]
Thanks, @mkarg.
