### ISSUE TITLE
Passing name-value pair from a map as query parameters in JAX-RS client

### ISSUE THREAD

**Issue by bappajubcse05** [eclipse-ee4j/jaxrs-api#757]
I am trying to access one existing REST service from my client side using JAX-RS client as below-
```
public interface ServerApi {
      @POST
      @Path("/server/{type}/add")
      void addServer(@PathParam("type") String type);
}
```

Here I want to pass a map as method parameter and JAX-RS client will convert that to query parameters. 

For example, if I pass a map (`[name=test, vendor=top1]`) as parameter (i,e, `serverApi.addServer("linux", map);`), JAX-RS client will transform it to `/server/linux/add?name=test&vendor=top1`

Can anyone please help me to achieve (to write the client method) this using JAX-RS client

**Comment by mkarg** [comment]
If you want a *query* parameter why do you specificy `@PathParameter`?

If you want *dynamic* parameter names, why do you specifiy the *static* name `map`?

What do you expect a machine to imply from those constraints?

**Comment by bappajubcse05** [comment]
@mkarg Probably some part of my query was confusing. I have removed that part. 
I am trying to build query-parameters from the key value pairs of a map as stated above.

Could you please help me to achieve this.

**Comment by mkarg** [comment]
There is no map-to-multiple-*different*-parameters conversion defined by the JAX-RS 2.1 specification. You need to multiply invoke [WebTarget#queryParam(String, String...)](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/client/WebTarget.html#queryParam-java.lang.String-java.lang.Object...-) with *different* parameter names.

**Comment by spericas** [comment]
@bappajubcse05 The declarative style of the interface above suggests that you're using MP REST Client, is that so? JAX-RS does not currently support that. See https://github.com/eclipse/microprofile-rest-client

**Comment by mkarg** [comment]
@bappajubcse05 Apparently your question was not directly related to JAX-RS but more to MP REST Client, and you did not respond for five days, so I will close your issue. Feel free to reopen it if needed.
