### ISSUE TITLE
Jakarta EE 8 TCK job

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#766]
@m0mus provided instructions regarding TCK transfer:

To test Jakarta EE 8 compatibility we need to create a Jenkins job on project's Cloud Jenkins instance formally testing the API against the relevant TCK and as needed, relevant CTS subset tests.

For projects that do not already have automated testing, there is provided parameterized Jenkins job that can be invoked to perform these tests. User provides a link to an Eclipse GlassFish test build and sets the test sub-set parameters:

For CTS -- https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification/
For Stand-alone TCKs -- https://ci.eclipse.org/jakartaee-tck/job/standalonetck-certification/

Additional instructions and guidance for using and directly running TCKs is available on [this wiki](https://wiki.eclipse.org/TCK:Build_From_Jakarta_EE_TCK_Repo_And_Run). Also in the [jakartaee-tck](https://github.com/eclipse-ee4j/jakartaee-tck) project repository.

**Comment by jansupol** [comment]
I have created a bunch of jobs available at https://jenkins.eclipse.org/jaxrs/view/TCK/.

There is a job for:
- [building a JAX-RS 2.1.6](https://jenkins.eclipse.org/jaxrs/view/TCK/job/JAX-RS_EE4J_8_branch_build/)
- [building a ts.jte configuration file](https://jenkins.eclipse.org/jaxrs/view/TCK/job/ts_jte_alter/)
- [integration of JAX-RS to Glassfish](https://jenkins.eclipse.org/jaxrs/view/TCK/job/JAX-RS_GF_Integration/)
- [Building a TCK bundle](https://jenkins.eclipse.org/jaxrs/view/TCK/job/TCK_build/)
- [Running the TCK bundle](https://jenkins.eclipse.org/jaxrs/view/TCK/job/TCK_run/)
- [Doing it all](https://jenkins.eclipse.org/jaxrs/view/TCK/job/TCK_main/)

**Comment by jansupol** [comment]
Note that there is a documentation for the TCK job [available](https://wiki.eclipse.org/TCK:Build_From_Jakarta_EE_TCK_Repo_And_Run).

**Comment by jansupol** [comment]
Note that these jobs are for Jakarta EE compatibility, to test the new JAX-RS built from EE4J_8 is compliant with Java EE JAX-RS RI (Jersey) i.e. the API works with Glassfish 5.1.0.

**Comment by mkarg** [comment]
@jansupol Great, thanks a lot! :-) But I wonder if it is actually the job of the JAX-RS team to check CI with one particular product, here Jersey and GlassFish. I mean, to be fair, we also have to either add RESTeasy, Wildfly, etc. CI jobs then, or drop the Jersey and GlassFish jobs otherwise.

**Comment by jansupol** [comment]
The TCK always was tested against RI. Once the RI passed the TCK, the RI was marked as compatible with JAX-RS Spec of the version corresponding to the TCK version. 

Here, there is a different use case. The new API is tested with the RI to check the compatibility. Once it passes with RI (or any other VI, does not matter), it can be said it is compatible. If any other VI (such as 
 RestEasy) fails the test, the test can be challenged, and the test needs to be fixed or excluded. Of course, this is the old Java EE compatibility testing. In Jakarta EE, it depends on the new process.

RestEasy and other JAX-RS compatible implementation (CXF,...) usually has its own proprietary jobs, scripts, or porting package used for the TCK to be run. This is especially essential for deployment. The TCK repository contains just the mechanism to run with Glassfish. It is out of the scope of the TCK to be run against the VIs. For this, the JAX-RS TCK will never be able to be run against other VIs, unless they make all the necessary bit free of use and someone will set up the job. 

It never should be an ambition of the Specification project (JAX-RS) to run the TCK against any other vendor implementations. Again, this depends on the new Jakarta Specification process, however.

**Comment by jansupol** [comment]
> It is out of the scope of the TCK to be run against the VIs

Sorry for the confusion. The TCK is, of course, meant to be run against all the implementations. Out of the box, it worked with the Java EE RI only (i.e. Glassfish), though. The licensees were responsible for running the TCK on their implementation and TCK defined a set of files that could have been changed for the TCK to be run and it also provided an API that the vendors could implement for the TCK to work on their implementation.
