### ISSUE TITLE
Convert "Eclipse Project for JAX-RS" into a specification project

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/jaxrs-api#767]
In order to prepare this project to engage in specification work, we need to convert it into a specification project as defined by the Eclipse Foundation Specification Process (EFSP). As part of this work, we will change the project name per #753 and the scope per #752.

We'll use this issue to capture the work that needs to be done as part of this effort. We'll update the following task list with details as they become available.

- [x] Resolve #752 
- [x] Resolve #753 
- [x] Successful complete a restructuring review
- [x] Designate the project as a specification project of the Jakarta EE Working Group
- [x] Change project name
- [x] Change project and specification scope

**Comment by mkarg** [comment]
@waynebeaton PR #763 implies the solution for #752 and #753 and will get merged ASAP.

**Comment by mkarg** [comment]
@waynebeaton Why create a different repository for the spec? It makes sense to keep it in the API repository to have both in sync / be able to add new features in both in a single commit.

**Comment by waynebeaton** [comment]
@mkarg we discussed this on the PMC call today. I believe that this requirement is from a point in time when we thought that specification document would be under a different license than the API. This is no longer the case.

The minutes will show that the PMC is of the opinion that the Specification Document and API can be kept in a single repository if that's what the team wants to do.

**Comment by mkarg** [comment]
@waynebeaton Thanks for this clarification. I marked that bullet as optional in the checklist.

**Comment by waynebeaton** [comment]
I've tweaked the plan a bit. I removed the bullet about creating a separate repository, I added a change of project id to "ee4j.rest", and repository name to "rest-spec". Feel free to suggest an alternative repository name ("jaxrs" is, unfortunately, off the table)

**Comment by mkarg** [comment]
@waynebeaton AFAIK we still had not been shown the proof that JAX-RS is an Oracle trademark hence why keeping "jaxrs" is off the table.

**Comment by mkarg** [comment]
Regarding the Gitlab URL I do not see a need to repeat "ee4j" as it is already contained in the prefix "eclipse-ee4j". Why not simply doing "gitlab.com/jakarta/rest"?

**Comment by chkal** [comment]
> AFAIK we still had not been shown the proof that JAX-RS is an Oracle trademark hence why keeping "jaxrs" is off the table.

Agreed. @kwsutter [mentioned](https://www.eclipse.org/lists/jakarta.ee-community/msg01177.html) that there will be some official statement about the requirements for acronyms. Any news on this?

**Comment by spericas** [comment]
@chkal Even after learning about any such requirements, it's unlikely JAX-RS will be on the table. I think we should move on from this discussion and use "Jakarta REST". It is a fresh start after all.

**Comment by waynebeaton** [comment]
> Regarding the Gitlab URL I do not see a need to repeat "ee4j" as it is already contained in the prefix "eclipse-ee4j". Why not simply doing "gitlab.com/jakarta/rest"?

@mkarg do you really mean "Gitlab"?

The project id is something that we (mostly) use internally. You'll see it in the PMI URL and in IPZilla. The repository URL that I've suggested is github.com/eclipse-ee4j/rest-spec

**Comment by mkarg** [comment]
@waynebeaton Sorry, certainly I meant "Github".

If the ID is just used internally, how can it be a trademark problem to keep jaxrs there?

**Comment by waynebeaton** [comment]
> If the ID is just used internally, how can it be a trademark problem to keep jaxrs there?

I did say "mostly". The id (e.g. "ee4j.rest") and the short name that comes from it ("rest") is used in some URLs.

**Comment by chkal** [comment]
@spericas 

> Even after learning about any such requirements, it's unlikely JAX-RS will be on the table.

I don't think so. At least there seems to be no trademark registered for JAX-RS. And @kwsutter [mentioned](https://www.eclipse.org/lists/jakarta.ee-community/msg01157.html) that most of the acronyms are NOT trademarked. As mentioned before, IMO we should only change the acronym if there are legal reasons to do so.

**Comment by waynebeaton** [comment]
Unfortunately none of us (including me) get a vote in this. The name "JAX", and by extension, "JAX-RS" cannot be used moving forward and must be changed.

**Comment by jansupol** [comment]
This sounds like an opportunity to rename the `JAXRS` interface with some meaningful name. It bootstraps the JAX-RS application in Java SE environment. I would not mind something like `StandaloneBoostrap`  or just `Bootstrap`.

**Comment by mkarg** [comment]
@waynebeaton Who does have a vote on this?

**Comment by mkarg** [comment]
@jansupol Can you please open a separate issue for the renaming to `Bootstrap` so we can separate the discussion threads?

**Comment by jansupol** [comment]
@mkarg I have filed the [issue](https://github.com/eclipse-ee4j/jaxrs-api/issues/770) for renaming the `JAXRS` interface

**Comment by waynebeaton** [comment]
@mkarg I used a turn of speech. There's no actual vote.

**Comment by mkarg** [comment]
@waynebeaton What we still have not seen after asking for it many times, is *the actual reason* why JAX-RS must not be used. It is *not* a registered trademark, and so far Oracle has *not* shown a public proof that they claimed it as a trademark. It is *not* mentioned as a trademark in the JAX-RS 2.1 Specification itself, and it is *not* mentioned on Oracle's [former](https://github.com/jax-rs/api) GitHub repository. So what is the *actual* reason why we, the committers, do *not* have the final say in that?

**Comment by spericas** [comment]
@waynebeaton Any update on the use of acronyms? Thanks

**Comment by mkarg** [comment]
@spericas Meanwhile I asked Oracle's Trademarks office to confirm that JAX-RS is a trademark. Today they sent an answer which does NOT imply that it is a trademark, NOR that it is NOT. Hence I wrote back that they shall be unambiguous. Let's see what happens.

**Comment by waynebeaton** [comment]
It is the position of the Jakarta EE Steering Committee that "JAX-RS" cannot be used as a project name, or to otherwise refer to the Jakarta RESTful Web Services specification or project. 

The position has changed regarding the use of acronyms in project ids and short names: existing usage will be allowed to continue. So... the name of the Git repository will not be changed as part of this set of changes. Likewise, project website URLs, mailing lists, etc. will be left as-is. I've updated the checklist accordingly.

The Steering Committee will publish more specific guidance shortly.

**Comment by waynebeaton** [comment]
I have implemented the changes. We're done here.

Please monitor the [PMC mailing list](https://accounts.eclipse.org/mailing-list/ee4j-pmc) for next steps.
