### ISSUE TITLE
Rename JAXRS interface 

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/jaxrs-api#770]
JAX-RS 2.2 branch contains [`JAXRS`](https://github.com/eclipse-ee4j/jaxrs-api/blob/master/jaxrs-api/src/main/java/jakarta/ws/rs/JAXRS.java) interface. Along with renaming JAX-RS, the interface name should be renamed. 

As it is responsible for bootstrapping a JAX-RS application in Java SE environment, a name reflecting that functionality should be chosen. Possibilities are:
- `Bootstrap` - simple and short, but does not reflect the fact it is for a standalone Java SE application bootstrap only
- `SeBootstrap` - Aligned with CDI `Se` prefixed [classes](https://docs.jboss.org/cdi/api/2.0/javax/enterprise/inject/se/SeContainer.html)
- `StandardBootstrap` - reflects usage in plain _Java Standard Edition_ environment
- `StandaloneBoostrap` - reflects the fact it does not need a support of a ServletContainer/ApplicationServer, but JAX-RS Spec. does not use the `Standalone` term (yet)
- or any other name

**Comment by mkarg** [comment]
+1 for keeping `JAXRS` as-is unless a public proof is shown of *a real legal reason* that we MUST NOT keep this acronym. Otherwise +1 for `SeBootstrap` or `SeServer` to be aligned with CDI.

**Comment by mkarg** [comment]
According to the Jakarta EE Working Group Steering Committee [Acronym Guidelines](https://jakarta.ee/legal/acronym_guidelines/) we are officially allowed to further use the class name `JAXRS`, hence I hereby vote -1 on this issue.

**Comment by spericas** [comment]
Those guidelines clearly state:

> For maximum flexibility and clarity, we encourage projects to change their short names to more closely correspond to the new specification names, if applicable, and avoid the Oracle/JCP acronyms where possible.

Keeping the same acronym will create confusion going forward. As I stated before, now is the best time to make a change this. So -1 for _not_ renaming the _new_ `JAXRS` interface.

**Comment by chkal** [comment]
> Keeping the same acronym will create confusion going forward.

Could you explain this in more detail? What kind of confusion? Java EE will continue to exist as Jakarta EE under the umbrella of the Eclipse Foundation. Beside the package renaming aspect, nothing will change from the user perspective. Users expect new versions of JAX-RS as part of Jakarta EE. 

IMO it is the other way around: All this renaming creates the confusion for users.

**Comment by jansupol** [comment]
> IMO it is the other way around: All this renaming creates the confusion for users.

No, the interface is not public, yet, no confusion in renaming it.

**Comment by chkal** [comment]
> No, the interface is not public, yet, no confusion in renaming it.

Agreed! However, my statement was more about the general "avoid the JAX-RS acronym" strategy.

**Comment by jansupol** [comment]
> my statement was more about the general "avoid the JAX-RS acronym" strategy.

There is a [guideline](https://jakarta.ee/legal/acronym_guidelines/) that says:
>Contact trademark_us@oracle.com before using Acronyms Used by Oracle or the JCP. 

I do not know whether it means there is a way to continue using JAX-RS acronym. But it's likely a different issue.

**Comment by spericas** [comment]
@chkal  Please read the first sentence of that document:

> The goal of these guidelines is to avoid confusion and ensure that the developer community can easily identify whether a Jakarta EE project, specification, test suite, or other related item originates from Oracle/JCP or from the Eclipse/Jakarta EE process.

  If a new acronym or short name is used going forward, the Jakarta context will be clear and unambiguous.

**Comment by mkarg** [comment]
> > my statement was more about the general "avoid the JAX-RS acronym" strategy.
> 
> There is a [guideline](https://jakarta.ee/legal/acronym_guidelines/) that says:
> 
> > Contact [trademark_us@oracle.com](mailto:trademark_us@oracle.com) before using Acronyms Used by Oracle or the JCP.
> 
> I do not know whether it means there is a way to continue using JAX-RS acronym. But it's likely a different issue.

I have contacted that address and was replied by an Oracle lawyer allowing us to continue the use of JAX-RS.

**Comment by mkarg** [comment]
BTW, cannot see how keeping `JAXRS` could confuse anybody.

**Comment by jansupol** [comment]
> BTW, cannot see how keeping `JAXRS` could confuse anybody.

Truth to be told, I am in a puzzle over the expected functionality of such a named interface since the first moment I saw that name.

**Comment by jansupol** [comment]
Thought I have said that back then when we had the discussion. Yes, I admit, I prefer the names that do describe the functionality. I know you have provided examples, but those names are not the best-chosen names either. Since 1999, [the name convention] (https://www.oracle.com/technetwork/java/codeconventions-135099.html) says the same:
> Try to keep your class names simple and descriptive.

Not descriptive to me.

> Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form)

It is an acronym to me.

**Comment by mkarg** [comment]
That might be that case, but as those discussion came to the end that we stick with the name `JAXRS` by an official vote (otherwise it could not be part of `master` right now). So you will need to find at least two people with +1 and you need to convince me not to -1. The latter will become a problem. ;-)

**Comment by spericas** [comment]
I did not vote against that name at the time, but this was way before the Eclipse guidelines related to the use of acronyms were written. Given that we are now _not_ encouraged to use the acronym anymore, we should _not_ introduce a type of that name. Hence the need to revisit this topic.

**Comment by mkarg** [comment]
Actually there is no *need*. We explicitly *may* use the acronym as a class name according to the guidelines. So let's stay clear with our phrases: You just WANT to change it. ;-) Its easier to discuss things if we all are frank about our intentions. Mine is that I do not want to stick any more work into an already finished feature, and looking at the recent change in the Jersey roadmap, I wonder that Team Jersey actually wants to carry this burden? I would be happy with the name `SeBootstrap`  and donate the PR for JAX-RS if Team Jersey agrees to rebase `JAXRS_2_2` ontop `master` **now**, so there is at least an actual benefit of the additional effort.

**Comment by spericas** [comment]
I'm being perfectly frank, I didn't vote against it back then, but I am now after reading the guidelines. I think it's a bad idea to use the acronym to name a class now.

**Comment by mkarg** [comment]
What about my above proposal? Deal?

**Comment by mxmlnglt** [comment]
By the way using `Bootstrap` (in any combination as suggested above) would be counterproductive to me as it's been widely used for years to name a CSS framework. Almost every search engine has this page as 1st result when searching for "Bootstrap": https://getbootstrap.com

**Comment by jansupol** [comment]
>  to rebase JAXRS_2_2 ontop master
I am sorry to be swamped with the Jakarta/Jersey 2.29.1 release. Will get to it immediately when that's done

**Comment by jansupol** [comment]
>  I would be happy with the name SeBootstrap and donate the PR for JAX-RS
@mkarg I have merged master to JAXRS_2_2 branch. Can we proceed with your proposal?

**Comment by mkarg** [comment]
@jansupol (Almost forgot about this thread...) Sure. And thanks for the merge. I will rename the class to SeBootstrap and publish a PR this week against JAXRS_2_2 branch, ok for everybody?

**Comment by mkarg** [comment]
Please review #799. :-)

**Comment by mkarg** [comment]
> > I would be happy with the name SeBootstrap and donate the PR for JAX-RS
> > @mkarg I have merged master to JAXRS_2_2 branch. Can we proceed with your proposal?

@jansupol I'm stuck with preparing the SeBootstrap rename PR for Jersey due to the missing package rename to jakarta.ws.rs. Tried to do that but failed hopelessly. Can you please put a commit into JAXRS_2_2 for using that package, so I can put the SeBootstrap PR ontop? :-)
