### ISSUE TITLE
Make Client AutoCloseable

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#781]
As there is a `Client#close()` method, I think it makes sense if we declare it `AutoCloseable` in a future release, so it works with try-with-resources.

**Comment by mkarg** [comment]
@spericas What do you think?

**Comment by spericas** [comment]
Yes, I don't see a problem with that. OTOH, hopefully this will not encourage developers to create lots of short-lived `Client` instances, which as explained in the Javadocs already, are expensive.

**Comment by mkarg** [comment]
I don't think it will encourage people for short living instances. In the end, creating a client needs lots of time, so people will notice that this would be a very bad practice.

**Comment by MarkusKull** [comment]
Some tests (without injected client) create a new client. So yes, this would be useful.

**Comment by mkarg** [comment]
Guys, we all had been blind: We already did that in f3fa7d03f91a7d44984659774406d1c2bbce3b65. At least good to know that we still want it! ;-)
