### ISSUE TITLE
@ApplicationPath in Java SE deployments

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#787]
Apparently (at least) Jersey does not respect the `@ApplicationPath`'s [value](https://github.com/eclipse-ee4j/jaxrs-api/blob/66ce6b3b9ea61daab64153789bababc2c14a3d84/jaxrs-api/src/main/java/jakarta/ws/rs/ApplicationPath.java#L57) *in Java SE deployments*, see [Jersey issue #4205](https://github.com/eclipse-ee4j/jersey/issues/4205).

The JAX-RS specification clearly tells how to use this annotation with *Servlet deployments*. Maybe we should add a clarifying statement *for Java SE deployments*, too?

**Comment by mkarg** [comment]
@eclipse-ee4j/eclipse-jaxrs Committers, please discuss! :-)

**Comment by chkal** [comment]
IMO `@ApplicationPath` should also be supported in SE environments. Not sure if we need to be more explicit about the fact that it also works in SE environments. At least I would have expected that.

**Comment by mkarg** [comment]
@chkal Apparently you are not alone with your expectations, but indeed Jersey behaves differently. Hence it would be great to hear some kind of "justification" of team Jersey.

**Comment by mkarg** [comment]
@eclipse-ee4j/eclipse-jaxrs More opinions, particularly from the vendors?

**Comment by andymc12** [comment]
+1 - I agree that `@ApplicationPath` should be supported in SE environments.

**Comment by mkarg** [comment]
@andymc12 Do you know whether IBM and Apache products actually do support this *already*?

**Comment by andymc12** [comment]
> @andymc12 Do you know whether IBM and Apache products actually do support this already?

They do not currently support the Jakarta Java SE APIs.

**Comment by mkarg** [comment]
@jansupol @asoldano Would be great if you could post you opinion. Thanks. :-)

**Comment by ronsigal** [comment]
Well, it looks like August is gone. Sorry.

There isn't **necessarily** a single answer since RESTEasy has a variety of embedded servers:

 * SunHttpJaxrsServer
 * UndertowJaxrsServer
 * NettyJaxrsServer
 * VertsJaxrsServer
 
As it happens, my colleague Rebecca Searls recently reorganized them so that they all implement a single interface, EmbeddedJaxrsServer. In any case, given the following:

      @ApplicationPath("application")
      public static class MyApp extends Application {
         ...
      }
      
      EmbeddedJaxrsServer server = new <...>JaxrsServer();
      ResteasyDeployment deployment = server.getDeployment();
      deployment.setApplicationClass(MyApp.class.getName());
      server.start();
      
the value of @ApplicationPath on MyApp will be honored for any of them.

**Comment by mkarg** [comment]
Apparently there are had been only +1 votes within the last months and no -1 votes. According to our voting rules this means that **all compliant implementations MUST respect `@ApplicationPath` in Java SE deployments**.

We now have to add a TCK test for this. Anybody like to volunteer?

**Comment by mkarg** [comment]
I will open a PR for this as soon as https://github.com/eclipse-ee4j/jaxrs-api/pull/931 is generally approved, as I plan to put the tests ontop of it.

**Comment by mkarg** [comment]
Correcting myself: The existing `SeBootstrapIT` contained in the new TCK for 3.1-SNAPSHOT already *implies* this check already, as it is using `@ApplicationPath("application")` everywhere. So there is neither a need nor a benefit from an *explicit* test. Hence I am closing this issue hereby.
