### ISSUE TITLE
Create gh_pages branch in the Project

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/jaxrs-api#788]
It is a **goal** for every Jakarta EE project to contain **project pages**, similarly to [JSON-B](https://eclipse-ee4j.github.io/jsonb-api), for instance. This is done through creating a new branch in the project, called **[gh-pages](https://github.com/eclipse-ee4j/jsonb-api/tree/gh-pages)**.

The immediate reason for this is to store the **results of the TCK** run for the upcoming 2.1.6 release, similarly to [JSON-B](https://github.com/eclipse-ee4j/jsonb-api/blob/gh-pages/tck_results_summary.txt).

While it is possible to just create the branch (and consequently a PR that puts the required web-page files into the branch) for a committer, I'd assume this is better to be announced and approved by the community, first. I'd propose this to be fast-track approve.

Note that in order to have this web pages branch to work, it needs to be allowed in the Project settings by an account with administrative privileges to the Project (unless I am mistaken)

**Comment by chkal** [comment]
+1

AFAIK we can just ask the EF web masters to enable GH pages support for the repository.

BTW: I just learned that there are even other ways than having a separate `gh-pages` to set up GitHub pages today:

> You can configure GitHub Pages to publish your site's source files from master, gh-pages, or a /docs folder on your master branch for Project Pages and other Pages sites that meet certain criteria.

**Comment by mkarg** [comment]
I think `gh-pages` is the most typical way, but a `/docs` folder sounds sweet. The problem is that we might also like to publish JavaDocs and Spec PDFs and possibly some static landing page there, so how can we mix it? Can we tell the TCK job to put the result in some subfolder?

BTW, I have not yet focused on the TCKs, but what actually tests the TCK here in our API project? I always thought the TCK is good for testing the implementating products...?

**Comment by jansupol** [comment]
> BTW, I have not yet focused on the TCKs, but what actually tests the TCK here in our API project? I always thought the TCK is good for testing the implementating products...?

Yes, TCK was designed to have implementation tested for compatibility with the Specification. However, for Jakarta EE 8 release, the plan was to release just the APIs, so that the release is as fast as possible. Since the API should be compatible with the previous API released in January, there already is an implementation that passed the TCK. So the idea was to just rerun the TCKs to check the new API by mistake does not contain any change that would break the TCK tests.

As time goes, I hear some voices saying the implementations will need to be released as well. Anyway, with Jakarta EE 9, the TCK should be used the same way people are used to.

**Comment by mkarg** [comment]
@jansupol I understand what you like to reach with that test, but I do not see why the result needs to be stored or published.

**Comment by chkal** [comment]
> but I do not see why the result needs to be stored or published.

AFAIK this was decided by the spec committee.

**Comment by mkarg** [comment]
The spec committee can only decide what *they* will do, not *who* will it do.

**Comment by spericas** [comment]
+1 for the creation of the new branch.

**Comment by jansupol** [comment]
> I do not see why the result needs to be stored or published.

Would you not want a prove the API + Compatible Implementation passed the TCK?

**Comment by mkarg** [comment]
I want to proof that Jersey passed the TCK, i. e. store the proof *there*. I do not want to proof JAX-RS itself, so I do not want to store this Jersey-specific information in the JAX-RS repo.

**Comment by jansupol** [comment]
> I do not want to store this Jersey-specific information in the JAX-RS repo.

The original information I got that the TCK result is to be stored in the API repository was changed. The information is [stored in Jersey repo](https://github.com/eclipse-ee4j/jersey/blob/gh-pages/tck/jakarta-restful-web-services-2.1.md) indeed. 

The branch for the web pages for the API still makes sense to me, to store some API specific information there.

**Comment by mkarg** [comment]
It might be useful to have JavaDocs, for example. :-)

**Comment by mkarg** [comment]
Seems we lost track of the original issue... IIUC then we all agree that it would be fine to have a `gh-pages` branch hosting our web site. So I will ask the EF admins to do that for us now.

**Please vote. As this is not API change, the vote is open for one day.** :-)

**Comment by andymc12** [comment]
I’m +1, but I think we might want to leave the vote open a little longer due to the holidays.  Thanks, Andy

**Comment by chkal** [comment]
+1 for creating the `gh-pages` branch

**Comment by mkarg** [comment]
The majority is +1, there is no -1.  I have created that branch. If someone after the holidays votes -1, we can simply remove it.

**Comment by mkarg** [comment]
Meanwhile the EF admins have enabled the Github Pages feature for us. So https://eclipse-ee4j.github.io/jaxrs-api/ now gets automatically updated each time (after some cache delay) from our `gh-pages` branch. Feel free to open PRs agains that branch if you have an idea how to improve the content! :-)
