### ISSUE TITLE
Update Cookie and NewCookie to support Same-Site 

### ISSUE THREAD

**Issue by rschildmeijer** [eclipse-ee4j/jaxrs-api#811]
Even though the Same-Site (Cookie Attribute) RFC is still only a draft [1] I propose that jaxrs should support the Same-Site cookie attribute. As explained in this blogpost https://web.dev/samesite-cookies-explained:

> Both Chrome and Firefox have this functionality available to test now and will be making this their default behavior in future releases. Edge also plans to make this their default behavior.

[1] https://tools.ietf.org/html/draft-west-first-party-cookies-07

**Comment by chkal** [comment]
Sorry, I created #862 a few days ago and missed that this issue already exists. As there is already some discussion happening in the second issue, I'll close this one in favor of #862.
