### ISSUE TITLE
Update the license names in pom.xml  to use proper SPDX identifier

### ISSUE THREAD

**Issue by sabgit** [eclipse-ee4j/jaxrs-api#816]
https://github.com/eclipse-ee4j/jaxrs-api/blob/8d16c8a9df6f3e86dc57f3a9cdc3378142ab999e/jaxrs-api/pom.xml#L60

Can you please update the license names used in the `pom.xml`  to be proper SPDX identifiers?

```xml
    <licenses>
        <license>
            <name>EPL 2.0</name>
            <url>http://www.eclipse.org/legal/epl-2.0</url>
            <distribution>repo</distribution>
        </license>
        <license>
            <name>GPL2 w/ CPE</name>
            <url>https://www.gnu.org/software/classpath/license.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
```

https://spdx.org/licenses/EPL-2.0.html ---> `EPL-2.0`

https://spdx.org/licenses/GPL-2.0-with-classpath-exception.html ---> `GPL-2.0-with-classpath-exception`

**Comment by chkal** [comment]
I agree that using SPDX would be better.

Feel free to provide a pull request. All information about how to contribute can be found [here](https://github.com/eclipse-ee4j/jaxrs-api/blob/master/CONTRIBUTING.md).

**Comment by mkarg** [comment]
> I agree that using SPDX would be better.
> 
> Feel free to provide a pull request. All information about how to contribute can be found [here](https://github.com/eclipse-ee4j/jaxrs-api/blob/master/CONTRIBUTING.md).

What actual benefit does this bring?

**Comment by chkal** [comment]
> > I agree that using SPDX would be better.
> > Feel free to provide a pull request. All information about how to contribute can be found [here](https://github.com/eclipse-ee4j/jaxrs-api/blob/master/CONTRIBUTING.md).
> 
> What actual benefit does this bring?

Maven plugins which analyze licenses of your dependencies work much better if the license name is something like the SPDX identifier instead of some arbitrary text.

**Comment by mkarg** [comment]
> > What actual benefit does this bring?
> 
> Maven plugins which analyze licenses of your dependencies work much better if the license name is something like the SPDX identifier instead of some arbitrary text.

Sounds interesting. Can you point me to such a plugin which actally works much better thanks to that? I'm also contributor to Apache Maven so I could use that as a claim to request a change of the POM reference (i. e. to clearly point out that *always* a SPDX ID SHOULD get used in *all* POMs).

**Comment by chkal** [comment]
I'm using [license-maven-plugin](https://www.mojohaus.org/license-maven-plugin/) in a few projects. And as dependencies typically use some arbitrary label to refer to the license, I had to configure it to merge a ton of strings to clean up the report.

Example:

```xml
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <version>1.9</version>
        <executions>
          <execution>
            <id>create-license-list</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>add-third-party</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <includedScopes>compile,runtime</includedScopes>
          <failIfWarning>false</failIfWarning>
          <fileTemplate>${basedir}/src/license/license.ftl</fileTemplate>
          <sortArtifactByName>true</sortArtifactByName>
          <generateBundle>true</generateBundle>
          <licenseMerges>
            <licenseMerge>
              The Apache Software License, Version 2.0
              |Apache License, Version 2.0
              |Apache 2
              |Apache 2.0
              |Apache License 2.0
              |AL 2.0
              |Apache License
              |Apache License Version 2.0
              |Apache License, version 2.0
              |Apache License, 2.0
            </licenseMerge>
            <licenseMerge>
              CDDL + GPLv2 with classpath exception
              |CDDL or GPLv2 with exceptions
            </licenseMerge>
            <licenseMerge>
              GNU General Public License, Version 2 with the Classpath Exception
              |GNU General Public License v2.0 only, with Classpath exception
              |GNU General Public License, version 2 (GPL2), with the classpath exception
              |GPL2 w/ CPE
            </licenseMerge>
            <licenseMerge>
              BSD License
              |BSD
            </licenseMerge>
            <licenseMerge>
              Eclipse Public License Version 1.0
              |Eclipse Public License v1.0
              |EDL 1.0
            </licenseMerge>
            <licenseMerge>
              MIT License
              |MIT license
              |The MIT License
            </licenseMerge>
            <licenseMerge>
              W3C license
              |The W3C License
            </licenseMerge>
          </licenseMerges>
        </configuration>
      </plugin>
```

Obviously, if the pom would confirm a standard identifier (like SPDX), creating license reports would be much easier.

**Comment by mkarg** [comment]
> I'm using [license-maven-plugin](https://www.mojohaus.org/license-maven-plugin/) in a few projects. And as dependencies typically use some arbitrary label to refer to the license, I had to configure it to merge a ton of strings to clean up the report.

I see. So the "much better" is only true when *all* projects would use SPDX (it's worth nothing to just have *us* do that in JAX-RS). I will open an issue with Apache Maven to propose this as a best practice.
