### ISSUE TITLE
Preparation of Jakarta EE 9 

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jaxrs-api#819]
Jakarta EE 9's [proposed release plan](https://docs.google.com/document/d/18cwfYhEqv_msIdH1DSVDXJc-QaUJ6zjPgmG6JHfLRrA) mandates that, due to the package migration, all specs have to increase the major version. As a consequence, we need to discuss:
- how to update our [roadmap](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Roadmap), and [milestones](https://github.com/eclipse-ee4j/jaxrs-api/milestones).
- how to to create a release branch fulfilling the rules of Jakarta EE 9: By branching off [master](https://github.com/eclipse-ee4j/jaxrs-api/tree/master) or by cherry-picking particular commits.
- how to update the TCK, if needed

See also the Jakarta EE 9 Platform's [release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).

**Comment by andymc12** [comment]
Thanks for starting this discussion.

I updated the [roadmap](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Roadmap) based on the EE 9 release plan.  In an [email conversation](https://www.eclipse.org/lists/jaxrs-dev/msg00726.html) on this topic, Ivar suggested that we publish both a 3.0 release with only the package rename (no API changes, though I think spec/javadoc clarifications and TCK fixes are ok to include) and the 3.1 release that includes new features (like the SE API, etc.).  That allows the EE 9 platform team the option to include the new features or not.

If we are ok with the version numbers of my proposed roadmap changes (dates are still very tentative), then I can update the [milestones](https://github.com/eclipse-ee4j/jaxrs-api/milestones).

I think we are making good progress on the "jakarta-fication" of JAX-RS, but we are blocked by dependencies like Activation and JAXB.  We cannot release until they have published a jakarta-fied release.  

> how to to create a release branch fulfilling the rules of Jakarta EE 9: By branching off master or by cherry-picking particular commits.

I propose that we create a separate `3.0` branch that would include the package renames and other non-API changes.  We could continue to use `master` for the 3.1 work.  I don't have a strong opinion either way whether we cherry-pick the changes we want for 3.0 vs branching off of master and undoing/reverting the API changes.

> how to update the TCK, if needed

I haven't looked into this much yet, but I think that this might be a matter of changing `javax` to `jakarta`.  Hopefully it is not much more than that.

Thanks again!

**Comment by mkarg** [comment]
@andymc12 I didn't find much time to spend into this issue, so I'd like to transfer it. May I assign it to you?

**Comment by andymc12** [comment]
@mkarg Sure - I should have some time later this week to look into this further.  Thanks!

**Comment by mkarg** [comment]
> @mkarg Sure - I should have some time later this week to look into this further. Thanks!

Great, thanks a lot!

**Comment by arjantijms** [comment]
Closing this issues as 3.0 for Jakarta EE 9 has been delivered.
