### ISSUE TITLE
Standard for problem details [rfc-7807]

### ISSUE THREAD

**Issue by t1** [eclipse-ee4j/jaxrs-api#839]
I'm working on producing and consuming problem details as specified in [RFC-7807](https://tools.ietf.org/html/rfc7807) for better generation and handling of http entities for application error conditions. I’ve just blogged about it: https://blog.codecentric.de/en/2020/01/rfc-7807-problem-details-with-spring-boot-and-jax-rs/

tl;dr: exceptions get mapped to rfc-7807 compliant application/problem+json http bodies on the server side and/or back to exceptions on the client side. You can rely on useful defaults for the fields or annotate your exceptions when you have specific requirements.

I have a potential implementation that runs on Payara and Open Liberty, and mostly on Widlfly 18... and on Spring Boot. I'd like this to become a standard in some form. I can see two options:

*Option 1*

Create a new MicroProfile standard, so it could be simply implemented also by Spring Boot. To hide the technical details the implementation, I'd like to [hide the ResponseProcessingException](https://github.com/eclipse-ee4j/jaxrs-api/issues/838). This option is what I'm currently working on.

*Option 2*

Integrate it directly into JAX-RS

What do you say?

**Comment by spericas** [comment]
Hi,

 I’ll respond to Option 2 as this would not be the right mailing list to discuss Option 1 … JAX-RS is a core Java API to build RESTful services; what you’re describing here seems like something that can be built on top of JAX-RS or simply provided as a library in a framework. I.e., at least at first glance, I don’t think JAX-RS is the correct place for this.

— Santiago

**Comment by chkal** [comment]
I'm not entirely sure if JAX-RS is the best place for this. On the one hand every application has to deal with problem/error reporting and people usually reinvent the wheel to implement it. So having out of the box support for such a standard would be great. On the other hand JAX-RS focuses on the core HTTP aspects of RESTful services and additional features like this are usually added by addon libraries or Microprofile (like the REST client for example).

Other thoughts?

**Comment by mkarg** [comment]
JAX-RS should concentrate on the core of REST-over-HTTP, evertyhing else should be done by standards built ontop (like it was done for MVC, or like Microprofile does). It might happen (like it was the case for MVC) that JAX-RS needs to provide new extension points; I would be happy to discuss them once the need actually arises.

**Comment by t1** [comment]
@mkarg : that's perfectly fine with me. One change to JAX-RS would make the integration even easier: if there was a way to _not_ wrap exceptions coming from filters, the mechanics could be hidden completely, as requested in #838.

**Comment by spericas** [comment]
@t1 Could we close this issue then?

**Comment by t1** [comment]
@spericas : I'm closing the issue now, as it seems to be the common thinking that it's nothing for jax-rs at the moment.
