### ISSUE TITLE
Update dependencies to Jakarta EE 9 levels - JAXB and Jakarta Activation

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxrs-api#845]
For the 3.0 release, we will need to ensure that our dependencies are at the Jakarta EE 9 levels.  Currently, we depend on JAXB and Jakarta Activation, both of which have release candidate builds after renaming the `javax` packages to `jakarta`. 

We also have one unit test, `JaxbLinkTest` that depends on the JAXB-RI - this will require that the JAXB-RI also have a build published that works with the renamed packages.

**Comment by chkal** [comment]
@andymc12 I guess this one can be closed, correct?

**Comment by andymc12** [comment]
@chkal yes, thanks for mentioning it.
