### ISSUE TITLE
Annotations on methods of interface

### ISSUE THREAD

**Issue by gergelymolnarpro** [eclipse-ee4j/jaxrs-api#847]
Could support to separate JAX-RS annotations from implementation. If an interface has JAX-RS annotations and a class implements that interface then the class need to duplicate annotations from interface for compatibility. The class should inherit annotations from the interface or enable to override those.

Example:
https://github.com/eclipse/microprofile-rest-client/issues/254#issuecomment-587182063

**Comment by chkal** [comment]
JAX-RS already supports annotations on interfaces. See section 3.6 of the specification:

> JAX-RS annotations may be used on the methods and method parameters of a super-class or an implemented interface. Such annotations are inherited by a corresponding sub-class or implementation class method provided that the method and its parameters do not have any JAX-RS annotations of their own. [...]

**Comment by gergelymolnarpro** [comment]
Thanks!
