### ISSUE TITLE
Deprecate JAXB usage in `Link` class.

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxrs-api#853]
Issue #815 is intended to make the JAXB APIs/impl optional for JAX-RS implementations, but the JAX-RS still has a dependency on JAXB from inner classes in the `Link` class.  Per discussion in #815, these inner classes should be deprecated and ultimately removed.

**Comment by mkarg** [comment]
@andymc12 Do you like to assign this issue to yourself?

**Comment by andymc12** [comment]
@mkarg yes, thanks for the nudge.
