### ISSUE TITLE
Mandate default ExceptionMapper

### ISSUE THREAD

**Issue by ronsigal** [eclipse-ee4j/jaxrs-api#855]
There are two ways for a request to exit a JAX-RS server:

 1. through the ContainerResponse filter chain, or
 2. by way of an unhandled Exception thrown up to the container.

The possibility of bypassing the filter chain can lead to problems. For example, the SmallRye Metrics implementation of the JAX-RS metrics resorts to using both a JAX-RS filter and a servlet filter. From the io.smallrye.metrics.jaxrs.JaxRsMetricsFilter javadoc:
```
**
 * Filter for measuring JAX-RS metrics, together with {@link JaxRsMetricsServletFilter}.
 * The reason for having two filters (one based on Servlet API, one on JAX-RS API)
 * is to overcome the limitation of JAX-RS specification in that it does not require
 * implementations to call a ContainerResponseFilter to finish exchanges that led
 * to an unmapped exception. That's why we can't use a ContainerResponseFilter to
 * 'finish' the tracking of a REST call and update the corresponding metrics.
 * For that reason, we have {@link JaxRsMetricsServletFilter}, which is a Servlet Filter,
 * to hook into the responses in this case.
```
Mandating the presence of a default ExceptionMapper would entail *all* requests to exit by way of the ContainerResponse filter chain and eliminate this problem.

What should the default ExceptionMapper do? Given that the result of an unhandled Exception is currently unspecified and dependent on the outer container, I would suggest that the behavior of the default ExceptionMapper remain unspecified.

**Comment by andymc12** [comment]
+1

OpenLiberty's MP Metric implementation does something similar, although probably worse than SmallRye - it registers a filter and an `ExceptionMapper<Throwable>`.  I don't like the way that is done because now users get different exception-handling behavior depending on whether they have enabled MP OpenTracing or not.

My only concern about this issue is that I think it would be better to specify the default ExceptionMapper's behavior - even if it is only a recommendation for implementors.  My thought is that if an exception is not handled by the application, then it probably _should_ be mapped to an Internal Server Error (500) and the root cause _should_ be logged on the server (but not propagated to the client as that could be a security vulnerability).  

There will be cases where the root cause of the problem is a client issue (where the response should be a 400-level status - like invalid content-type, etc.), but the solution to that would be to add better validation checking in the MessageBodyReaders and/or ContainerRequestFilters.

Thanks for the suggestion!

**Comment by ggam** [comment]
> There will be cases where the root cause of the problem is a client issue (where the response should be a 400-level status - like invalid content-type, etc.), but the solution to that would be to add better validation checking in the MessageBodyReaders and/or ContainerRequestFilters.

I just recently opened an OpenLiberty issue about that exactly: https://github.com/OpenLiberty/open-liberty/issues/11408

When the unhandled exception is a `WebApplicationException`, it will already contain a response with headers and status code that should be respected IMO.

**Comment by spericas** [comment]
Seems like a good suggestion to support a default exception mapper. I think we'll need to say something about the mapped response, not sure if we can leave that completely open ended. 

@ronsigal Would you be interested in making a concrete proposal? Perhaps in the form a PR?

**Comment by ronsigal** [comment]
So, something like

A JAX-RS implementation MUST include a default ExceptionMapper that implements ExceptionMapper&lt;Throwable&gt; and which SHOULD
1. log the exception
2. set the response status to 500
3. set the response content to a string that contains at least the message of the Throwable.

If the unhandled exception is a `WebApplicationException`, its embedded Response MUST be returned.

Once we agree, I would be happy to submit a PR to update the spec document and add a test to the TCK.

**Comment by andymc12** [comment]
I think that looks good, but I don't think that the message of the Throwable should be part of the response - I'm mainly concerned about security.  I can live with it if everybody else wants it though.  Thanks Ron!

**Comment by ronsigal** [comment]
@andymc12, you're right about the message. There's no reason to expect it to be meaningful to the user. I note that WebApplicationException just sends 
```
HTTP 500 Internal Server Error
```
for a 500 status.

**Comment by ggam** [comment]
One can understand NotFoundException would return 500, as happens in
OpenLiberty when Opentracing is enabled.

I'd rephrase the last sentence: "If the unhandled exception is a
WebApplicationException, its embedded Response MUST be returned, and its
status code MUST be respected".

**Comment by spericas** [comment]
@ronsigal I agree with the proposal and the feedback by @andymc12 and @ggam

**Comment by ronsigal** [comment]
@ggam, I didn't mention the status in the WebApplicationException because it's inside the Response, but it doesn't hurt to be explicit. Ok.

Thanks, @spericas, I'll work on a pull request.

**Comment by ronsigal** [comment]
@ggam, I didn't mention the status in the WebApplicationException because it's inside the Response, but it doesn't hurt to be explicit. Ok.

Thanks, @spericas, I'll work on a pull request.

**Comment by ronsigal** [comment]
Pull request: https://github.com/eclipse-ee4j/jaxrs-api/pull/857

I wasn't sure how to handle an addition to the Change Log, so I just added an entry to "Changes Since 2.1 Public Review". I can change that if.

**Comment by ronsigal** [comment]
https://github.com/eclipse-ee4j/jaxrs-api/pull/857 replaced by https://github.com/eclipse-ee4j/jaxrs-api/pull/858.

**Comment by ronsigal** [comment]
TCK test: https://github.com/eclipse-ee4j/jakartaee-tck/pull/191

**Comment by ronsigal** [comment]
@scottmarlow has asked on https://github.com/eclipse-ee4j/jakartaee-tck/pull/191 which release of JAX-RS this change might target.

**Comment by chkal** [comment]
@ronsigal I guess we can close this one as #858 is already merged?

**Comment by chkal** [comment]
Closing this one now. Feel free to reopen if anything is still missing.
