### ISSUE TITLE
Allow overridden @Path class by method

### ISSUE THREAD

**Issue by Zorin95670** [eclipse-ee4j/jaxrs-api#864]
In some cases, we can have two ressources
- user defined by `/users` (UsersController)
- cars defined by `/cars` (CarsController)

And we want to have a specific endpoint `/users/{usersID}/cars` with Patch to
Patch all cars of selected user.

But we want that endpoint is in Cars controllers not in UsersController. Because the service that is used is the CarsService.

May be it's possible to add an attribut in @Path, to overide default path class like : 

```java
@Path("cars")
public class CarsController {
    // ...
    @PATCH
    @Path("/users/{user_id}/cars", true)
    public void updateUsersCars(...);
}
```

Or something else can permit this, will be appreciated.

**Comment by NicoNes** [comment]
Hi @Zorin95670,

It sounds like you need to use "Sub-resources-locator". 
I invite you to read section ["3.4.1 Sub Resources"](https://download.oracle.com/otn-pub/jcp/jaxrs-2_1-final-eval-spec/jaxrs-2_1-final-spec.pdf?AuthParam=1587413651_3b155dac89cec2451c931f99c3868639) of the JAX-RS spec to get more details about it.

Using this concept your code should looks like:
```
@Path("users")
public class UserController {

	@Path("{userId}/cars")
	public void cars(@PathParam("userId")String userId) {
	   return new CarController(userId);		
	}

}

```

```
@Path("cars")
public class CarController {
	
	private final CarFinderService carFinderService;
	
	public CarController(String userId) {
		// Init carFinderService to find cars of the given userId
		this.carFinderService=...
	}
	
	public CarController() {
		// Init carFinderService to find cars of anybody
		this.carFinderService=...
	}

	@GET
	public Response getAllCars() {
		return carFinderService.findAllCars();
	}

	@GET
	@Path("{carId}")
	public Response getCarById(@PathParam("carId")String carId) {
		return carFinderService.findCarByid(carId);
	}
	
	@PATCH
	@Path("{carId}")
	public Response getCarById(@PathParam("carId")String carId, Car car) {
		return carFinderService.updateCarByid(carId);
	}

}
```
Hope it helps.

-Nicolas

**Comment by Zorin95670** [comment]
Hi, thanks for your answers. It seems good.

**Comment by Zorin95670** [comment]
Thank's for your answer, It's a working trick.

But, I think it would be nice, that @Path annotation permit overridden or do not include default url.

Because, I use swagger annotation for api documentation, and it's destabilizing to have documentation of "cars" controller in "users" controller.

Another point, when you want to fix or add feature to this patch endpoint. Your first think is to go in cars controller not in user controller.

That's why, it would be better that's is a global change. I know it's not a simple change.

We can consider that if path doesn't have url value, we do check all path in method that correspond to our url.

It would be more permissive.

**Comment by NicoNes** [comment]
Hey @Zorin95670 

> Because, I use swagger annotation for api documentation, and it's destabilizing to have documentation of "cars" controller in "users" controller.

Well AFAIK, Swagger handles the "Sub resource locator"concept pretty well and you do not have to annotate the "sub resource locator" method. As you said it will be weird.

On both of your `UserController` and `CarController` you only need to add Swagger annotations on the java method annotated with `@GET`, `@POST`, `@PUT`...
This way Swagger will generate something like:

```
paths:
	/cars:
		get:
			summary: {Documentation from Swagger annot on CarController.getAllCars()}
	/cars/{carsId}:
		get:
			summary: {Documentation from Swagger annot on CarController.getCarById()}
	/cars/{carsId}:
		patch:
			summary: {Documentation from Swagger annot on CarController.patchCarById()}	

	/users:
		get:
			summary: {Documentation from Swagger annot on UserController.getAllUsers()}
	/users/{userId}:
		get:
			summary: {Documentation from Swagger annot on UserController.getUserById()}		
	/users/{userId}/cars:
		get:
			summary: {Documentation from Swagger annot on CarController.getAllCars()}
	/users/{userId}/cars/{carsId}:
		get:
			summary: {Documentation from Swagger annot on CarController.getCarById()}
	/users/{userId}/cars/{carsId}:
		patch:
			summary: {Documentation from Swagger annot on CarController.patchCarById()}					
```

> Another point, when you want to fix or add feature to this endpoint. Your first think is to go in cars controller not in user controller.

Yep and you first impression is the right one: the java method endpoint is in `CarController` not in `UserController`.
The java method endpoint, the one that will perform the job, is the method annotated with `@GET`, `@POST`, `@PUT` etc in `CarController` not in `UserController`. 
By the way as you may have noticed that sub-resource locator in `UserController` is only annotated with `@Path` and  no `@GET`, `@POST`, `@PUT` etc.

About your proposal, I personnaly dont like the mix in and the complexity it introduces.
Now things are pretty simple:
When you have a `UserController` registered on path `users` and another one `CarController` registered on path `cars`, anytime you see a path starting with `users` it means that the class entry point to look for the java method is `UserController`.
So when I see a path like `users/{userId}/cars`, the class entry point is `UserController` and in this class I look for a java method with path `{userId}/cars`. 
If this method is annotated with any of `@GET`, `@POST`, `@PUT` etc I use it. Else it means that it is a "sub-resource locator" and then I have to look for the java method endpoint in the returned type and so on...

**Comment by spericas** [comment]
> Thank's for your answer, It's a working trick.
> 
> But, I think it would be nice, that @path annotation permit overridden or do not include default url.

 If you look at the matching algorithm in the spec, you'd realize that your "feature request" is not compatible with the current approach. The matching algorithm isn't perfect, but has been around for like a decade. Changes that risk backward compatibility would very likely be rejected.

**Comment by Zorin95670** [comment]
@spericas @NicoNes I understand what you say and I'm agree with that :) 

But my intend, is to have more flexibility in future in rest management, like other language/framework.

Like I says before, I know it's not easy to come and say "Hey it would be nice to …" or to do / think about the feature.

So, thank's for your support, the ticket can be closed, because my problem is solved.

May be open an another ticket to medicate on path flexibility ^^.
