### ISSUE TITLE
Update EFSL for Specifications and Javadoc

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jaxrs-api#871]
Per the discussions on the Spec Committee and Platform Dev mailing lists, it's been discovered that many of the Javadoc and Spec references to the EFSL need updating. Please reference the following required updates and keep them in mind as your Spec Project is updating the files for Jakarta EE 9.

Note: Some Spec Projects have already started or even completed these updates. If so, just kindly return/close this Issue. Thanks!

**Required EFSL updates for Javadoc**

For javadoc, the EFSL.html located in src/main/javadoc/doc-files should be modified as follows:
* the `<<url to this license>>` needs to be replaced with efsl.php link[1]
* the `[title and URI of the Eclipse Foundation specification document]` needs to be replaced with the Specification Name and URL (Reference [2] for an example.)
* The javadoc footer copyright year needs to be updated to 2018, 2020 as defined in the pom.xml

**Required EFSL updates for Specifications**

For specification, the license-efsl.adoc located in src/main/asciidoc should be modified as follows:
* Update copyright year to 2018, 2020 from 2019. Add link to EFSL.
* the `<<url to this license>>` needs to be replaced with efsl.php link[1]
* the `[title and URI of the Eclipse Foundation specification document]` needs to be replaced with the Specification Name and URL (Reference [2] for an example.)

[1] https://www.eclipse.org/legal/efsl.php  
[2] https://jakarta.ee/specifications/enterprise-beans/4.0/

**Comment by chkal** [comment]
See pull request #874.

**Comment by chkal** [comment]
#874 has been merged. So we can close this one as fixed.
