### ISSUE TITLE
Missing Tag for 3.0.0-M1

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/jaxrs-api#873]
The API 3.0.0-M1 is in maven central, but there is missing a tag for it in the repo.

**Comment by chkal** [comment]
@andymc12 AFAIK you performed the release, correct? Any idea why the tag is missing?

**Comment by spericas** [comment]
Yes, seems to be missing. Here is the job:

https://ci.eclipse.org/jaxrs/job/Publish%20Release/32/

**Comment by andymc12** [comment]
Thanks for catching that.  I'm not sure what happened during the release, but I just pushed the tag ([3.0.0-m1](https://github.com/eclipse-ee4j/jaxrs-api/tree/3.0.0-m1)) now using the commit @spericas mentioned (from the build).

**Comment by andymc12** [comment]
Along the same lines, I'm planning to add the spec PDF and HTML and Javadocs to the specification page ( https://github.com/jakartaee/specifications/blob/master/restful-ws/3.0/_index.md ), as Kevin requested at https://www.eclipse.org/lists/jakartaee-platform-dev/msg01836.html

**Comment by spericas** [comment]
Thanks @andymc12 !
