### ISSUE TITLE
Support for arrays as parameters

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxrs-api#890]
Section 3.2 says the following:

> Valid parameter types for each of the above annotations are listed in
the corresponding Javadoc, however in general (excluding `@Context`) the
following types are supported:
> 1.  Types for which a `ParamConverter` is available via
a registered `ParamConverterProvider`. See Javadoc for these classes for
more information.
> 2.  Primitive types.
> 3.  Types that have a constructor that accepts a single
`String` argument.
> 4.  Types that have a static method named `valueOf` or
`fromString` with a single `String` argument that return an instance of
the type. If both methods are present then `valueOf` MUST be used unless
the type is an enum in which case `fromString` MUST be usedfootnote:[Due
to limitations of the built-in `valueOf` method that is part of all Java
enumerations, a `fromString` method is often defined by the enum
writers. Consequently, the `fromString` method is preferred when
available.].
> 5.  `List<T>`, `Set<T>`, or `SortedSet<T>`, where `T` satisfies
1,3 or 4 above.

It seems like we should support array types in places where we support `List` types (e.g. `@CookieParam`, `@FormParam`, `@HeaderParam`, `@MatrixParam`, and `@QueryParam` - `@BeanParam` and `@PathParam` do not support Lists, so should not support arrays either).

The MicroProfile Metrics community incorrectly assumed that arrays were already supported (see conversation here: https://groups.google.com/forum/#!topic/microprofile/yxoelXvk3o8 ).  

Arrays already seem to be supported in Apache CXF and RESTEasy. I have not tested Jersey, but I assume that they are not supported based on the MP Metrics conversation.

If nobody objects, I can open a PR to update the spec text and Javadoc.  Since this changes behavior, it would need to be released post-EE9.

**Comment by mkarg** [comment]
Sounds reasonable. Thank your for bringing this forward.
