### ISSUE TITLE
Final 3.0.0 API jar delivered to Staging repo

### ISSUE THREAD

**Issue by spericas** [eclipse-ee4j/jaxrs-api#898]
Created this issue to discuss any final steps needed to push the final 3.0.0 bits to staging. See #832.

**Comment by chkal** [comment]
Any idea what we can do regarding the PDF rendering issue? See #876 for details.

**Comment by spericas** [comment]
@chkal Don't have any suggestions. But that shouldn't prevent us from pushing the API jar to staging, right?

**Comment by chkal** [comment]
Yes, sure. I just wanted to mention it, as the spec document will be part of the final release.

**Comment by spericas** [comment]
I'll start with the release/staging process over the weekend.

**Comment by spericas** [comment]
> Yes, sure. I just wanted to mention it, as the spec document will be part of the final release.

Is it not an option to do Asciidoc -> HTML -> PDF until we find something better?

**Comment by chkal** [comment]
> Is it not an option to do Asciidoc -> HTML -> PDF until we find something better?

Yes, this may be possible. Not sure how good the results are, but it is worth a try.

**Comment by spericas** [comment]
See PR #899

**Comment by spericas** [comment]
We need to re-stage after after #906, #907 and #909

**Comment by spericas** [comment]
Staging release has been updated and spec docs pushed with fix to `Source` class.
