### ISSUE TITLE
Declare XML Binding packages as optional in JPMS and OSGi

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxrs-api#907]
Per the [thread on the Jakarta Platform mail list](https://www.eclipse.org/lists/jakartaee-platform-dev/msg02182.html), we may need to make it more clear that Jakarta XML Binding is optional. We addressed this initially in issue #815 and PR #854  
However, we need to make it more clear for JPMS and OSGi users that these packages are optional.

Per Lukas's comment in the mail thread, this can be done by updating the pom.xml and module-info.java files:
> replace `requires transitive jakarta.xml.bind;` with `requires static 
jakarta.xml.bind;` in module-info[1]. That will do the trick for JPMS. 
Marking dependency on xml.bind-api optional in project's pom[2] should 
resolve the problem for OSGi.

**Comment by kwsutter** [comment]
This issue looks to supersede or, at least, is related to Issue #906.  Just connecting the dots....
