### ISSUE TITLE
Compatibility Certification Request for Eclipse Jersey 3.0.0-RC2

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/jaxrs-api#912]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  Eclipse Jersey 3.0.0-RC2, see TCK Result Summary for the download links
- [x] Specification Name, Version and download URL\
   [Jakarta RESTful Web Services 3.0](https://jakarta.ee/specifications/restful-ws/3.0/)
- [x]  TCK Version, digital SHA-256 fingerprint and download URL
[Jakarta RESTful Web Services TCK 3.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0.zip), SHA-256: 39081f393f495d2363ae66c487f83a171cb52a8038930bd1af7829f5757a9aa7
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/jersey/tck/eclipse-jersey-3.0.0-RC2)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 1.8.0_265
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
   Linux basic-dqbt6 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 GNU/Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by jansupol** [comment]
A new TCK has been promoted, so after rerunning the TCK I have updated the [TCK Results Summary](https://eclipse-ee4j.github.io/jersey/tck/eclipse-jersey-3.0.0-RC2). 
Now we have 
- [x]  TCK Version, digital SHA-256 fingerprint and download URL
[Jakarta RESTful Web Services TCK 3.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0.zip), SHA-256: 39081f393f495d2363ae66c487f83a171cb52a8038930bd1af7829f5757a9aa7

**Comment by spericas** [comment]
Great, thanks Jan!

**Comment by arjantijms** [comment]
As committer for Jakarta RESTful Web Services I assert this is complete and can be accepted. I don't believe the project lead, @spericas , will have any objections to this.
