### ISSUE TITLE
Release tasks for Jakarta RESTful Web Services 3.0 

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jaxrs-api#916]
The following tasks need to be completed in order to complete the Jakarta RESTful Web Services 3.0 spec release:
- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x]  go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x]  approve the compatibility request.
- [x]   The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
- [x]  merge any final release branch as appropriate for the branch management for the project.

**Comment by mkarg** [comment]
@spericas @andymc12 Somebody already working on these tasks?

**Comment by arjantijms** [comment]
API available at: https://repo1.maven.org/maven2/jakarta/ws/rs/jakarta.ws.rs-api/3.0.0/

All links on https://jakarta.ee/specifications/restful-ws/3.0 look fine

**Comment by arjantijms** [comment]
> merge any final release branch as appropriate for the branch management for the project.

I think the project didn't create a release branch.

**Comment by arjantijms** [comment]
CCR accepted and closed: https://github.com/eclipse-ee4j/jaxrs-api/issues/912

**Comment by arjantijms** [comment]
Email sent. CC'ed @jansupol @spericas

**Comment by arjantijms** [comment]
All tasks have been completed, closing this issue.

**Comment by mkarg** [comment]
@arjantijms @spericas Thank you for finishing this task. But is it really the way we want to work together as committers that we just act on a Saturday night (while the project lead is not in office) but do not discuss before?

**Comment by mkarg** [comment]
> > merge any final release branch as appropriate for the branch management for the project.
> 
> I think the project didn't create a release branch. Checking the item, since there's noting to do, and nothing has been done.

I think what could count here is that branch `3.1-SNAPSHOT` should be rebased ontop `master` now.

**Comment by spericas** [comment]
> > > merge any final release branch as appropriate for the branch management for the project.
> > 
> > 
> > I think the project didn't create a release branch. Checking the item, since there's noting to do, and nothing has been done.
> 
> I think what could count here is that branch `3.1-SNAPSHOT` should be rebased ontop `master` now.

Feel free to do that @mkarg. Otherwise, let me know. We should tag 3.0 too.

**Comment by mkarg** [comment]
> > I think what could count here is that branch `3.1-SNAPSHOT` should be rebased ontop `master` now.
> Feel free to do that @mkarg. Otherwise, let me know. We should tag 3.0 too.

Created [tag 3.0.0](https://github.com/eclipse-ee4j/jaxrs-api/tags).

Rebasing is under construction, stay tuned.

**Comment by mkarg** [comment]
> Rebasing is under construction, stay tuned.

Rebasing done. Branch "2.1-SNAPSHOT" now is based on branch "master". As a result, a lot of duplicate commits have been collapsed. If somebody feels like there is something missing, don't hesitate to report.
