### ISSUE TITLE
Missing API documentation for JAXRS-API 3.0 (jakartified)

### ISSUE THREAD

**Issue by senivam** [eclipse-ee4j/jaxrs-api#928]
There are no API docs published for jakartified JAXRS API at https://eclipse-ee4j.github.io/jaxrs-api/apidocs.
The latest version shows only 2.1.6 API docs.

**Comment by mkarg** [comment]
Can anybody remember they technical way how to put the current docs there?

**Comment by mkarg** [comment]
> I guess it is the `gh-pages` branch of this repo?

Ah... right. You added it manually there back then. I will provide a PR doing the same for 3.0.0.

**Comment by senivam** [comment]
this can be closed as fixed.
