### ISSUE TITLE
TCK Challenge: `isRegisteredRuntimeExceptionExceptionMapperTest ` testing for exact class when should check for `instanceof`

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxrs-api#937]
**Specification:**
Jakarta RESTful Web Services 3.0 (EE 9.0) Full Platform TCK

**Challenged test(s):**
[com.sun.ts.tests.jaxrs.ee.rs.ext.providers.JAXRSProvidersClient#isRegisteredRuntimeExceptionExceptionMapperTest](https://github.com/eclipse-ee4j/jakartaee-tck/blob/adf6ca2beb09b72a77e685d5ec1ad425e0782bc3/src/com/sun/ts/tests/jaxrs/ee/rs/ext/providers/JAXRSProvidersClient.java#L158)

**TCK version:**
9.0.0

**Tested implementation:**
Open Liberty using RESTEasy + Weld

**Description:**

The specification allows CDI to manage the dependency lifecycle of resources and provider if present. When running the TCK on the (still under development) EE 9 version of Open Liberty, the `isRegisteredRuntimeExceptionMapper` test fails because it checks that the underlying implementation of the `Providers` interface returns the _exact_ exception mapper class used.  When CDI is in play, the object returned is often a Java dynamic proxy instance, so it's class would be a sub-class of the exception mapper class, but not necessarily that exact class.

This issue has been addressed in the TCK for the next version (9.1), but this challenge exists to exclude it from the 9.0 version.  The issue has been discussed in the TCK repo at issue https://github.com/eclipse-ee4j/jakartaee-tck/issues/587 / PR  https://github.com/eclipse-ee4j/jakartaee-tck/pull/588

I'm pulling this "form" from other TCK challenges in other EE9 projects.  If there is a better way, please let me know.  We may also want to create a "challenge" label, but I'm using "tck" for now.

**Comment by spericas** [comment]
As discussed in eclipse-ee4j/jakartaee-tck#587, this is a valid challenge.

**Comment by scottmarlow** [comment]
@spericas as per your comment that the challenge is valid, please do mark the challenge as `accepted`.

**Comment by scottmarlow** [comment]
Does anyone here volunteer to create a `jakartaee-tck` pull request to exclude the test mentioned above?  This would be similar to https://github.com/eclipse-ee4j/jakartaee-tck/pull/601

**Comment by brideck** [comment]
@scottmarlow Sure, I've got one here for the 9.0.x branch: https://github.com/eclipse-ee4j/jakartaee-tck/pull/603

**Comment by jansupol** [comment]
To continue with the discussion, based on #939 it is not clear what should be CDI bean and what it should not. Should the ExceptionMapper be not a CDI bean, for the same reasons as in #939, this challenge should not be accepted. If it is completely possible for the CDI to handle the ExceptionMapper as a CDI bean then let's exclude this.

**Comment by andymc12** [comment]
@jansupol even if CDI is not in the picture, I believe that this is a valid challenge.  Section 4.1 says:
> An implementation MAY offer other provider lifecycles, mechanisms for specifying these are outside the scope of this specification. E.g. an implementation based on an inversion-of-control framework may support all of the lifecycle options provided by that framework.

I read that as an implementor has the right to provide a dynamic proxy to the exception mapper for things like tracing mapped exceptions, enforcing synchronized access, etc. AFAICT, there is no hard requirement in the spec or javadoc that says `Providers` must return the exact instance of the exception mapper (meeting an identity check).  Checking that the returned exception mapper is an instanceof the specified provider type is a better test, regardless of the use of CDI.

**Comment by jansupol** [comment]
@andymc12 This sounds correct and I agree with the exclude.

**Comment by scottmarlow** [comment]
@andymc12 the spelling of the excluded test is missing some information, could you please check the .jtr files for the failing tests and update `com.sun.ts.tests.jaxrs.ee.rs.ext.providers#isRegisteredRuntimeExceptionMapper` to be the full test name which is identified by the line that starts with `test=`.  Some examples are in https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jakartaee/bin/ts.jtx

**Comment by andymc12** [comment]
@scottmarlow - updated it to `com.sun.ts.tests.jaxrs.ee.rs.ext.providers.JAXRSProvidersClient#isRegisteredRuntimeExceptionMapper` - hopefully that's right.

**Comment by scottmarlow** [comment]
@andymc12 feel free to attach the .jtr test (should be able to drag + drop into a comment) result file that contains the test name.  For future TCK challenges, we should include the .jtr files.

**Comment by brideck** [comment]
Uploaded JTR file
[JAXRSProvidersClient_isRegisteredRuntimeExceptionExceptionMapperTest_from_standalone.jtr.log](https://github.com/eclipse-ee4j/jaxrs-api/files/5895029/JAXRSProvidersClient_isRegisteredRuntimeExceptionExceptionMapperTest_from_standalone.jtr.log)

**Comment by scottmarlow** [comment]
https://github.com/jakartaee/specifications/pull/330 is merged and https://download.eclipse.org/jakartaee/platform/9/jakarta-jakartaeetck-9.0.2.zip is available with the exclusion applied.  As well as https://download.eclipse.org/jakartaee/restful-ws/3.0/jakarta-restful-ws-tck-3.0.1.zip

@spericas could you please close this TCK challenge issue as it is now complete.
