### ISSUE TITLE
TCK Challenge: Using `@Context` parameters in resource constructors should be optional

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxrs-api#938]
**Specification:**
Jakarta RESTful Web Services 3.0 (EE 9.0) Full Platform TCK

**Challenged test(s):**
[com.sun.ts.tests.jaxrs.spec.resourceconstructor#visibleTest](https://github.com/eclipse-ee4j/jakartaee-tck/blob/adf6ca2beb09b72a77e685d5ec1ad425e0782bc3/src/com/sun/ts/tests/jaxrs/spec/resourceconstructor/JAXRSClient.java#L48)

**TCK version:**
9.0.0

**Tested implementation:**
Open Liberty using RESTEasy + Weld tested by IBM

**Description:**

The specification allows CDI to manage the dependency lifecycle of resources and provider if present. This test exists to verify that the proper constructor is invoked.  Per the spec, the constructor with the most arguments annotated with `@Context` should be invoked.  However, when CDI is in play, then the rules of [section 11.2.9](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#additional_reqs) take effect, specifically:
> Support for constructor injection of JAX-RS resources is OPTIONAL. Portable applications MUST instead use fields or bean properties in conjunction with a @PostConstruct annotated method. Implementations SHOULD warn users about use of non-portable constructor injection.

In the (still under development) EE 9 version of Open Liberty that uses RESTEasy and Weld, the CDI implementation creates the instance of the resource class using normal CDI rules (invoking the no-arg constructor) which fails the test.  I think that in the long run, the test should be modified to check whether CDI is enabled and then determine the appropriate constructor to be invoked - though these rules may change significantly if future versions of RESTful WS will require CDI.

I'm pulling this "form" from other TCK challenges in other EE9 projects.  If there is a better way, please let me know.  We may also want to create a "challenge" label, but I'm using "tck" for now.

**Comment by jansupol** [comment]
I agree that Section 11.2.9 makes CDI behave in contradiction to Section 3.1.2 which says:
> If more than one public constructor is suitable then an implementation MUST use the one with the most
parameters.

I agree that CDI will be the first-class-citizen in the next Jakarta REST release, Section 11.2.9 should take precedence over 3.1.2, and Section 3.1.2 should be reformulated, perhaps the requirement can be dropped.

The cause of this challenge seems to be the fact that the CDI is used, no matter the beans.xml is not included. I am aware that beans.xml was mandatory in CDI 1.0, but in the Glassfish 4 and 5 environment, CDI did not work for me unless beans.xml was present. I'd welcome it if anyone can enlighten me.

For 3.1, the fix can perhaps be to use beans.xml to explicitly disable CDI for the test? The test was designed to test the requirement from 3.1.2.

**Comment by scottmarlow** [comment]
As per https://jakarta.ee/committees/specification/tckprocess, please use `challenge` label:
```
Filing a Challenge

Challenges MUST be filed via the specification project’s issue tracker using the label `challenge` and include the following information:

*   The relevant specification version and section number(s)
*   The coordinates of the challenged test(s)
*   The exact TCK version
*   The implementation being tested, including name and company
*   A full description of why the test is invalid and what the correct behavior is believed to be
*   Any supporting material; debug logs, test output, test logs, run scripts, etc.
```

**Comment by spericas** [comment]
Incidentally, this is one of a few problems related to supporting multiple DI mechanisms in Jakarta REST, and a good reason to continue working on moving to a CDI-only architecture. I agree with @jansupol's suggestion to possibly _turn off_ CDI for this test.

**Comment by andymc12** [comment]
@spericas @jansupol thanks for the suggestion.  I've been working with @brideck on this, and he confirmed that the test passes for us when we add a beans.xml file with `bean-discovery-mode="none"`.  I'm not sure if that is allowed for CTS compliance testing on 9.0.0, but I think it makes sense to add that beans.xml for future versions of the TCK.  If we're in agreement on this challenge, I can create a PR with the beans.xml fix for TCK 9.1.

**Comment by scottmarlow** [comment]
Unrelated to the comments above, I wanted to give some guidance based on my understanding of the current [TCK Process](https://jakarta.ee/committees/specification/tckprocess).  In general, this TCK challenge should be either `accepted` or `denied` within 2 weeks.  If the challenge is `denied`, this issue should be labelled `invalid`.  If the challenge is `accepted`, this issue should be labelled `accepted`.

Assuming this TCK challenge is accepted, the expected outcomes are:
- A 3.0.x Jakarta REST TCK is released with the `com.sun.ts.tests.jaxrs.spec.resourceconstructor#visibleTest` test excluded.
- A 9.0.x Jakarta EE Platform TCK is released with the `com.sun.ts.tests.jaxrs.spec.resourceconstructor#visibleTest` test excluded.
- Upstream changes would be made (asynchronously as in when possible and time permitting) to improve the tests.  The issue for the test improvement should be labelled `enhancement` (I just noticed this part being mentioned in the TCK Process).

**Comment by scottmarlow** [comment]
> Unrelated to the comments above, I wanted to give some guidance based on my understanding of the current [TCK Process](https://jakarta.ee/committees/specification/tckprocess). In general, this TCK challenge should be either `accepted` or `denied` within 2 weeks. If the challenge is `denied`, this issue should be labelled `invalid`. If the challenge is `accepted`, this issue should be labelled `accepted`.
> 
> Assuming this TCK challenge is accepted, the expected outcomes are:
> 
>     * A 3.0.x Jakarta REST TCK is released with the `com.sun.ts.tests.jaxrs.spec.resourceconstructor#visibleTest` test excluded.
> 
>     * A 9.0.x Jakarta EE Platform TCK is released with the `com.sun.ts.tests.jaxrs.spec.resourceconstructor#visibleTest` test excluded.
> 
>     * Upstream changes would be made (asynchronously as in when possible and time permitting) to improve the tests.  The issue for the test improvement should be labelled `enhancement` (I just noticed this part being mentioned in the TCK Process).

I'm responding to my own comment, as I just noticed something related in the TCK Process:
```
Improvement

Requests for improvement to tests MUST simply be created as issues with a label of enhancement in the specification project’s TCK issue tracker.
```

**Comment by scottmarlow** [comment]
> @spericas @jansupol thanks for the suggestion. I've been working with @brideck on this, and he confirmed that the test passes for us when we add a beans.xml file with `bean-discovery-mode="none"`. I'm not sure if that is allowed for CTS compliance testing on 9.0.0, but I think it makes sense to add that beans.xml for future versions of the TCK. 

@andymc12 Adding a beans.xml to the 9.0.0 Platform TCK test archive is not allowed or expected to be done.  The only test modification that you are expected to make is to somehow add vendor specific deployment descriptors.

**Comment by brideck** [comment]
> 
> @andymc12 Adding a beans.xml to the 9.0.0 Platform TCK test archive is not allowed or expected to be done. The only test modification that you are expected to make is to somehow add vendor specific deployment descriptors.

If this is the case, then we have a truly unfortunate challenge coming your way that will cause the exclusion of 32 tests in the jaxrs bucket.  I view a beans.xml used in such a manner as a server config tweak because we're just telling CDI how to process applications.  Apparently that is not the case.

**Comment by scottmarlow** [comment]
> > @andymc12 Adding a beans.xml to the 9.0.0 Platform TCK test archive is not allowed or expected to be done. The only test modification that you are expected to make is to somehow add vendor specific deployment descriptors.
> 
> If this is the case, then we have a truly unfortunate challenge coming your way that will cause the exclusion of 32 tests in the jaxrs bucket. I view a beans.xml used in such a manner as a server config tweak because we're just telling CDI how to process applications. Apparently that is not the case.

@brideck I'll look for more details to clarify.

**Comment by kwsutter** [comment]
Isn't the addition of this beans.xml file the proposed "workaround" or "solution" for this challenge?  Until it can become the real answer in a future version of the TCK?  I can appreciate that we don't want this type of addition to be a general practice.  But, it seems that in this case, this is the suggested "fix" for the problem until the proper solution is figured out and delivered.

**Comment by kwsutter** [comment]
@scottmarlow I thought we decided at a Spec Committee meeting that this approach was an acceptable approach...
`Acceptable if the TCK challenge is accepted by the spec project and spec project agrees that is a valid workaround of adding the (described challenge) Jakarta deployment descriptor (e.g. with agreement for that specific deployment descriptor contents).`

So, if the use of the beans.xml file is the proposed workaround by the jaxrs project team (for this challenge), then are we good with this particular Issue?

**Comment by scottmarlow** [comment]
> @scottmarlow I thought we decided at a Spec Committee meeting that this approach was an acceptable approach...
> `Acceptable if the TCK challenge is accepted by the spec project and spec project agrees that is a valid workaround of adding the (described challenge) Jakarta deployment descriptor (e.g. with agreement for that specific deployment descriptor contents).`

Good point, so I guess we can catch up on updating the TCK process document to reflect what we agreed on at the SPEC call.

So, on each TCK challenge that the SPEC lead does agree to resolve via a workaround, we need the SPEC lead to state so.

> 
> So, if the use of the beans.xml file is the proposed workaround by the jaxrs project team (for this challenge), then are we good with this particular Issue?

@spericas could you please respond again on this TCK challenge on whether the suggested workaround (e.g. use of beans.xml with `bean-discovery-mode="none"` is accepted. Thanks!

**Comment by spericas** [comment]
> 
> > So, if the use of the beans.xml file is the proposed workaround by the jaxrs project team (for this challenge), then are we good with this particular Issue?
> 
> @spericas could you please respond again on this TCK challenge on whether the suggested workaround (e.g. use of beans.xml with `bean-discovery-mode="none"` is accepted. Thanks!

 The suggested workaround to use a `beans.xml` with with `bean-discovery-mode="none"` is accepted.

**Comment by scottmarlow** [comment]
Since the workaround is accepted by the SPEC lead, the tests do not need to be excluded (since there is a workaround).  I do not think any further action is needed on this challenge at this time.  This issue can be closed.

**Comment by andymc12** [comment]
Thanks @scottmarlow and all!

**Comment by brideck** [comment]
@spericas

I've made a prospective update to the 9.1 TCK (https://github.com/eclipse-ee4j/jakartaee-tck/pull/635) to always include beans.xml files for these applications.  Please take a look and provide a review approval, if you agree with the approach.

**Comment by spericas** [comment]
> @spericas
> 
> I've made a prospective update to the 9.1 TCK ([eclipse-ee4j/jakartaee-tck#635](https://github.com/eclipse-ee4j/jakartaee-tck/pull/635)) to always include beans.xml files for these applications. Please take a look and provide a review approval, if you agree with the approach.

Done.
