### ISSUE TITLE
TCK Challenge: CDI deployment failure prevents app start for JAX-RS / BeanValidation TCK tests

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxrs-api#939]
**Specification:**
Jakarta RESTful Web Services 3.0 (EE 9.0) Full Platform TCK

**Challenged test(s):**
All tests in [com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/JAXRSClient.java):
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanAnnotatedIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanAnnotatedIsValidEvenBeingOneCharLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanAnnotatedIsValidTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanAnnotatedReturnIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanAnnotatedReturnIsInvalidForBeingNullTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanAnnotatedReturnIsValidEvenBeingOneCharLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanAnnotatedReturnIsValidTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanIsInvalidForBeingOneCharLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#beanIsValidTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#constraintDeclarationExceptionThrownTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#constraintDefinitionExceptionThrownTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#returnIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#returnIsInvalidForBeingNullTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#returnIsInvalidForBeingOneCharLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#returnIsValidTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#validateExecutableIsInvalidForBeingShortTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation#validateExecutableIsNotValidatedTest

All tests in [com.sun.ts.tests.jaxrs.platform.beanvalidation.constraintviolationexceptionmapper](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxrs/platform/beanvalidation/constraintviolationexceptionmapper/JAXRSClient.java):
com.sun.ts.tests.jaxrs.platform.beanvalidation.constraintviolationexceptionmapper#beanAnnotatedIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.constraintviolationexceptionmapper#beanAnnotatedReturnIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.constraintviolationexceptionmapper#beanIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.constraintviolationexceptionmapper#constraintDeclarationExceptionThrownTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.constraintviolationexceptionmapper#constraintDefinitionExceptionThrownTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.constraintviolationexceptionmapper#returnIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.constraintviolationexceptionmapper#validateExecutableIsInvalidForBeingShortTest

All tests in [com.sun.ts.tests.jaxrs.platform.beanvalidation.validationexceptionmapper](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxrs/platform/beanvalidation/validationexceptionmapper/JAXRSClient.java):
com.sun.ts.tests.jaxrs.platform.beanvalidation.validationexceptionmapper#beanAnnotatedIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.validationexceptionmapper#beanAnnotatedReturnIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.validationexceptionmapper#beanIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.validationexceptionmapper#constraintDeclarationExceptionThrownTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.validationexceptionmapper#constraintDefinitionExceptionThrownTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.validationexceptionmapper#returnIsInvalidForBeingFiveCharsLongTest
com.sun.ts.tests.jaxrs.platform.beanvalidation.validationexceptionmapper#validateExecutableIsInvalidForBeingShortTest

**TCK version:**
9.0.0 and 9.0.1

**Tested implementation:**
Open Liberty using RESTEasy + Weld + Hibernate Validator tested by IBM

**Description:**

This is an unfortunate and fairly complex challenge. The short of it is that when combining CDI + BeanValidation + RESTful WS + an app with something wrong with it, the app fails to start - and that means that all other tests depending on that app to be running will fail.

These 32 tests are intended to test the interaction between Bean Validation and RESTful WS. Open Liberty's implementation uses RESTful WS (RESTEasy) in conjunction with CDI (Weld).  [Section 2.9 of the CDI spec](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#exceptions) says:

> * Definition errors - occur when a single bean definition violates the rules of this specification. If a definition error exists, the container must throw a subclass of `jakarta.enterprise.inject.spi.DefinitionException`.

...

> Definition errors are _developer errors_. They may be detected by tooling at development time, and are also detected by the container at initialization time. If a definition error exists in a deployment, initialization will be aborted by the container.

As required by the CDI spec, Weld identifies the intentionally-broken application code and throws a `DefinitionException`  preventing the application from starting.  The DefinitionException is caused by the a constraint annotation lacking a message parameter - iiuc, this is intentional, and is expected to verify that the RESTful WS implementation handles a bean validation error correctly at runtime. I'm attaching logs and FFDC files from Open Liberty attempting to start the three apps involved in these tests.
[messages.log](https://github.com/eclipse-ee4j/jaxrs-api/files/5817419/messages.log)
[ffdc_21.01.14_16.53.16.0.log](https://github.com/eclipse-ee4j/jaxrs-api/files/5817420/ffdc_21.01.14_16.53.16.0.log)

Like challenge issue #938, if we disable CDI for these applications by adding a beans.xml with `bean-discovery-mode="none"`, then the tests pass.  But (1) it sounds like that is not allowed, and (2) implementations are allowed to depend on CDI for injection as stated in [section 11.2.3 of the RESTful WS spec](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#cdi).

I'm afraid that this means we will need to exclude all 32 bean validation tests - at least for the 9.0 TCK.  For future releases, we could change the test to either add beans.xml to disable CDI or just remove the intentionally-broken pieces to a separate app that either disables CDI or passes with or without CDI.

**Comment by scottmarlow** [comment]
@andymc12 we are working on a revision to the TCK process via https://github.com/jakartaee/jakarta.ee/pull/1018 which I think will help make it possible for the (relevant) SPEC team to approve use of a workaround (and the rules for that).

**Comment by spericas** [comment]
@andymc12 Where is that constraint annotation that causes the `DefinitionException`? Any thoughts about this @jansupol?

**Comment by brideck** [comment]
[ConstraintDefinitionAnnotation](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/ConstraintDefinitionAnnotation.java) is missing the required message(), groups(), payload() methods.

**Comment by jansupol** [comment]
When no beans.xml is defined, the default beandiscovery mode is annotated per CDI 2.0. However, the tests do not use any bean defining annotation. Should CDI be enabled in that case?

**Comment by andymc12** [comment]
@jansupol
> When no beans.xml is defined, the default beandiscovery mode is annotated per CDI 2.0. However, the tests do not use any bean defining annotation. Should CDI be enabled for the test classes in that case?

Section 11.2.3 says:
> In a product that supports CDI, implementations MUST support the use of CDI-style Beans as root re- source classes, providers and Application subclasses. Providers and Application subclasses MUST be singletons or use application scope.

In this case, since the product supports CDI, I take that to mean that `@Path` and `@Provider` should be treated effectively as bean-defining applications. RESTEasy uses a CDI portable extension to add the scoping annotations appropriately.  HTH

**Comment by jansupol** [comment]
@andymc12 My understanding is that `CDI-style Beans` are CDI managed-beans, i.e. beans with bean defining annotations. That corresponds with the second sentence:
> Providers and Application subclasses MUST be singletons or use application scope.

i.e. only `@Provider` with either `@jakarta.inject.Singleton` or `@ApplicationScoped` annotations are supported as CDI-style Beans.

**Comment by andymc12** [comment]
It definitely could use some clarification.  RESTEasy was able to pass the TCK for Java EE 8 using this same code (we're just taking the EE8 version and transforming it to use the new namespace), but my guess is that they only ran the Web Profile suite of tests (which doesn't seem to have many CDI-related tests - at least nothing that would verify one interpretation over the other).  These tests are part of the Full Profile suite.

**Comment by scottmarlow** [comment]
> It definitely could use some clarification. RESTEasy was able to pass the TCK for Java EE 8 using this same code (we're just taking the EE8 version and transforming it to use the new namespace), but my guess is that they only ran the Web Profile suite of tests (which doesn't seem to have many CDI-related tests - at least nothing that would verify one interpretation over the other). These tests are part of the Full Profile suite.

WildFly is passing the Jakarta EE Platform 8.0.2 TCK which includes these tests (e.g. I just verified that test=com/sun/ts/tests/jaxrs/platform/beanvalidation/annotation/JAXRSClient.java\#beanAnnotatedIsInvalidForBeingFiveCharsLongTest_from_standalone and others are passing).  I'm not disagreeing with the discussion here but am responding since I do help run these tests. :-)

**Comment by andymc12** [comment]
@scottmarlow interesting.  Do you know if Wildfly uses the RESTEasy CDI module?  If so, then I would expect the behavior to be the same as what we're seeing.  Or does Wildfly disable CDI for certain tests/archives?  We have a `<cdi12 enableImplicitBeanArchives="false"/>` config setting that can disable CDI annotation scanning.  I'm wondering if we need to configure that setting to match Wildfly's results.  Thanks for the info!

**Comment by scottmarlow** [comment]
> @scottmarlow interesting. Do you know if Wildfly uses the RESTEasy CDI module?

Yes, WildFly master branch is using resteasy-cdi-3.14.0.Final.jar currently.

> If so, then I would expect the behavior to be the same as what we're seeing. 

> Or does Wildfly disable CDI for certain tests/archives?
I looked to see if we have any similar hacks in place and did not find anything in my search.  

> We have a `<cdi12 enableImplicitBeanArchives="false"/>` config setting that can disable CDI annotation scanning. I'm wondering if we need to configure that setting to match Wildfly's results. Thanks for the info!

I looked in various (WildFly TCK) scripting/xml/configuration/other files and do not see that would influence the com.sun.ts.tests.jaxrs.platform.beanvalidation.annotation tests.

I'm guessing that it could be some WildFly integration code (either CDI/Weld or RESTEasy related) that is different.

Scott

**Comment by spericas** [comment]
> @jansupol
> 
> > When no beans.xml is defined, the default beandiscovery mode is annotated per CDI 2.0. However, the tests do not use any bean defining annotation. Should CDI be enabled for the test classes in that case?
> 
> Section 11.2.3 says:
> 
> > In a product that supports CDI, implementations MUST support the use of CDI-style Beans as root re- source classes, providers and Application subclasses. Providers and Application subclasses MUST be singletons or use application scope.
> 
> In this case, since the product supports CDI, I take that to mean that `@Path` and `@Provider` should be treated effectively as bean-defining applications. RESTEasy uses a CDI portable extension to add the scoping annotations appropriately. HTH

 This statement is about allowing providers and classes to be CDI beans, not about discovery or implying that our annotations are bean defining. OTOH, this is something we should support when we do a full CDI integration, but it raises some questions about how to reconcile discovery vs. whatever is returned by the applications subclass methods.

**Comment by andymc12** [comment]
Likewise to @scottmarlow's [comment in challenge issue 938](https://github.com/eclipse-ee4j/jaxrs-api/issues/938#issuecomment-768428567), @spericas are you ok with working around this challenge by using a beans.xml that contains `bean-discovery-mode="none"` ?  Thanks

**Comment by spericas** [comment]
@andymc12 Do we have an explanation as to why WildFly with RestEasy passes this test? I'm generally OK with using a beans.xml, but I'm curious as to why there's a difference in behavior with these tests.

**Comment by andymc12** [comment]
> @andymc12 Do we have an explanation as to why WildFly with RestEasy passes this test? I'm generally OK with using a beans.xml, but I'm curious as to why there's a difference in behavior with these tests.

I don't have a good explanation...  Our version of RESTEasy (currently 4.5.8) is newer than Wildfly's (3.14), but the [RestEasyCdiExtension class](https://github.com/resteasy/Resteasy/blob/master/resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/ResteasyCdiExtension.java) is the same - this is the code that makes `@Path` and `@Provider` bean defining annotations.

My guess is that either Wildfly doesn't use this extension by default or that there is some config setting that disables it or disables bean scanning in the applications.  @scottmarlow mentioned that it's possible Wildfly does something different when it consumes RESTEasy.

**Comment by spericas** [comment]
> > @andymc12 Do we have an explanation as to why WildFly with RestEasy passes this test? I'm generally OK with using a beans.xml, but I'm curious as to why there's a difference in behavior with these tests.
> 
> I don't have a good explanation... Our version of RESTEasy (currently 4.5.8) is newer than Wildfly's (3.14), but the [RestEasyCdiExtension class](https://github.com/resteasy/Resteasy/blob/master/resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/ResteasyCdiExtension.java) is the same - this is the code that makes `@Path` and `@Provider` bean defining annotations.
> 
> My guess is that either Wildfly doesn't use this extension by default or that there is some config setting that disables it or disables bean scanning in the applications. @scottmarlow mentioned that it's possible Wildfly does something different when it consumes RESTEasy.

 OK, I understand. I haven't looked at these tests in great detail, but are there any negative implications on the _good validation tests_ if we turn off bean discovery?

**Comment by andymc12** [comment]
> OK, I understand. I haven't looked at these tests in great detail, but are there any negative implications on the good validation tests if we turn off bean discovery?

I don't think so. When I was researching this challenge, I checked that none of the classes in the test use any other bean defining annotations, and when we disable bean discovery, all of the tests pass.  So I think the good tests are fine either way.

**Comment by spericas** [comment]
I have marked the challenge as accepted with the proposed workaround of turning off bean discovery.

**Comment by andymc12** [comment]
Thanks!

**Comment by andymc12** [comment]
Thanks all!
