### ISSUE TITLE
Clarification and test of `HttpHeaders.getRequestHeader(String)` when header does not exist 

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxrs-api#944]
Per the [javadocs](https://jakarta.ee/specifications/restful-ws/3.0/apidocs/jakarta/ws/rs/core/httpheaders#getRequestHeader(java.lang.String)) for `HttpHeaders.getRequestHeader(String)`:
> List<String> getRequestHeader​(String name)
Get the values of a HTTP request header. The returned List is read-only. This is a shortcut for getRequestHeaders().get(name).
...
Returns:
a read-only list of header values.
...

There is a slight conflict in the text.  On the one hand, the description and "Returns:" section say that this method must return a read-only list.  On the other hand, the description says that this method is a shortcut for `getRequestHeaders().get(name)` which would return null if the specified key does not exist in the map.

I mention this because a user testing their app on CXF was checking for null, and then their app broke when it was getting an empty list in RESTEasy. For the short term, I've advised the user to check for null and for an empty list, but ideally this would be clarified and tested in the TCK.

IMO, either option (returning null or returning an empty list) is fine (as long as it is one or the other), but I tend to prefer returning null if the header key does not. If we wanted to be more Java 8-friendly, we could return an `Optional<List<String>>`, but that would be a breaking change...

I'll plan to code up PRs with the change to the javadoc and TCK.  If anybody has strong opinions about returning an empty list instead of null, please let me know.  Thanks!

**Comment by chkal** [comment]
I generally prefer to return an empty list in these situations. But IMO it would be more important to be consistent with `MultivaluedMap.get(String)`. So +1 for `null`.
