### ISSUE TITLE
Clarification: jaxrs/spec/provider/standardhaspriority readWriteBooleanProviderTest

### ISSUE THREAD

**Issue by dblevins** [eclipse-ee4j/jaxrs-api#958]
We're down to our last 23 JAX-RS failures against the 9.1 TCK and 43 failures overall.  We really need some clarification on how this test is supposed to work/pass:

 - `com/sun/ts/tests/jaxrs/spec/provider/standardhaspriority/JAXRSClient#readWriteBooleanProviderTest_from_standalone`

The text from the assertion is as follows:

> An implementation MUST support application-provided entity providers and MUST use those in preference to its own pre-packaged providers when either could handle the same request. More precisely, step 4 in Section 4.2.1 and step 5 in Section 4.2.2 MUST prefer application-provided over pre-packaged entity providers.

In our implementation the `TckUniversalProvider` is properly selected over any built-in providers.  It's `readFrom` method is called and does delegate to `TckBooleanProvider`.  What's very confusing is `TckBooleanProvider.readFrom` is [hardcoded to return](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxrs/spec/provider/standardhaspriority/TckBooleanProvider.java#L65) `true`, so that is what is passed into `Resource.bool` which is hardcoded to return HTTP `406` [if true is passed in](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxrs/spec/provider/standardhaspriority/Resource.java#L60-L61).

The assertion says the application-supplied provider must be selected, however, the test appears to be explicitly written to fail if that actually happens.  There appears to be a conflict.

Can we get some clarification on what this test is asserting and how the test case is supposed to work?

**Comment by chkal** [comment]
@jansupol Any thoughts?

**Comment by jansupol** [comment]
The JAX-RS Spec, Section 4.2.4 requires the standard provider for Boolean, MediaType text/plain. The test uses MediaType.TEXT_PLAIN_TYPE, but the TckUniversalProvider is for */*. The standard priority package prefers the built-in providers over the TCK providers because of the media type. The `TckUniversalProvider` ought not to be used I believe.

**Comment by jansupol** [comment]
Even better, the TckUniversalProvider implements `MessageBodyReader<Object>, MessageBodyWriter<Object>`, which is far worse than the `MessageBodyReader<Boolean>, MessageBodyWriter<Boolean>` required by the vendor's implementation.

**Comment by scottmarlow** [comment]
CC @spericas

**Comment by spericas** [comment]
I'd need to review the code in more detail (any links we can attach here would be useful). I think the original intent was to first sort based on MBR's capabilities and then priorities. Ordering was better clarified in the matching algorithm in version 2.0, but it isn't as clear in the MBR selection if I recall correctly.

**Comment by dblevins** [comment]
Thank you so much, everyone!  I'm really touched by the number of responses in such a short period of time!  It is truly appreciated. :)

Test now passing and there are no serious regressions from implementing as suggested.

I've created a ticket so I don't forget to come back and help improve the description/assertion for the test: #959
