### ISSUE TITLE
Clarify behavior when SseEvent source onEvent throws and exception

### ISSUE THREAD

**Issue by NicoNes** [eclipse-ee4j/jaxrs-api#992]
Hi guys,

The spec does not clearly state what to do when `SseEventSource` `onEvent` listener throws an exception, especially

-  if `onError` listeners must be invoked or not.
-  if the event processing must be stopped or not

In my opinion, if the inspiration of the Java `SseEventSource`  is the JavaScript's `EventSource` then `onError` listener must not be invoked in this case. As discussed [here](https://github.com/eclipse-ee4j/jaxrs-api/issues/606#issuecomment-574234819) already , it is not the purpose of the the `onError` listener described in the JavaScript's `EventSource` docs.

So to stay consitent with the JavaScript's `EventSource`  I suggest to add a clarification in the javadoc saying something like:

> If an  `onEvent` listener throws an exception, `onError` listeners is not invoked and event processing is not stopped. It is encouraged that `onEvent` listener catches and handles exception itself. 

Vendors on their side can decide to trace the exception or not.

WDYT ?

Thanks

**Comment by spericas** [comment]
On Jul 6, 2021, at 7:34 PM, NicoNes ***@***.******@***.***>> wrote:

Hi guys,

The spec does not clearly state what to do when SseEventSource onEvent listener throws an exception especially if onError listeners must be invoked or not.

In my opinion, if the inspiration of the Java SseEventSource is the JavaScript's EventSource then onError listener must not be invoked in this case. As discussed here<https://urldefense.com/v3/__https://github.com/eclipse-ee4j/jaxrs-api/issues/606*issuecomment-574234819__;Iw!!ACWV5N9M2RV99hQ!YuL4uogwmnR9_NHp8HfVlUkqoZYjgo0PMjUYLCSdfYtWRTaszSJd6A26hi5ZTx-TOorE01UVlQ$> already , it is not the purpose of the the onError listener described in the JavaScript's EventSource docs.

So to stay consitent with the JavaScript's EventSource I suggest to add a clarification in the javadoc saying something like:

If an onEvent listener throws an exception, resulting behavior is not guaranteed, but onError listeners wont' be invoked. It is encouraged that onEvent listener catches and handles exception itself.

Vendors on their side can decide to trace the exception or not.

WDYT ?


 I agree with your analysis. Would create an issue and PR for this and link the EventSource doc describing the behavior? The intent is really to handle _connection events_ not internal errors IMO.

— Santiago

**Comment by spericas** [comment]
I agree with your analysis. Do you want to submit a PR for this?
